window.__NP_GAMES_CACHE__ = [
  {
    "id": "hang-rong",
    "title": "Hàng Rong",
    "tagline": "Gánh hàng vỉa hè, gom tiền mở rộng tiệm.",
    "category": "Quản lý",
    "section": "hot",
    "players": "1 người",
    "duration": "3-5 phút",
    "mechanic": "Nấu món ăn vặt, phục vụ khách theo kiên nhẫn, nâng cấp khay và dụng cụ",
    "badge": "Huyền thoại",
    "color": "#C75B3A"
  },
  {
    "id": "dao-vang",
    "title": "Vực Ngọc",
    "tagline": "Canh con lắc, kéo vật sáng trước khi hết giờ.",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1 người",
    "duration": "2-4 phút",
    "mechanic": "Thả dây vào ngọc biển; vật nặng kéo chậm hơn",
    "badge": "Bản thử",
    "color": "#3c7880"
  },
  {
    "id": "ban-trung-khung-long",
    "title": "Mảnh Sao",
    "tagline": "Nối cụm tinh thể, chặn triều sao rơi.",
    "category": "Giải đố",
    "section": "all",
    "players": "1 người",
    "duration": "2-4 phút",
    "mechanic": "Ngắm, bắn và nối ba mảnh cùng biểu tượng; cụm rời rơi theo trọng lực",
    "badge": "Bản thử",
    "color": "#526b9f"
  },
  {
    "id": "kim-cuong-bejeweled",
    "title": "Kính Khảm",
    "tagline": "Ghép mảnh kính, hoàn thiện ba ô cửa.",
    "category": "Giải đố",
    "section": "all",
    "players": "1 người",
    "duration": "3-5 phút",
    "mechanic": "Ghép ba biểu tượng liền hàng; mảnh được tự bù và rơi xuống",
    "badge": "Bản thử",
    "color": "#638c91"
  },
  {
    "id": "line-98",
    "title": "Line 98 Cổ Điển",
    "tagline": "Xếp 5 quả thẳng hàng, không để kín bàn cờ.",
    "category": "Giải đố",
    "section": "hot",
    "players": "1 người",
    "duration": "5-15 phút",
    "mechanic": "Di chuyển bóng trên lưới 9x9 tạo đường 5 quả cùng màu, xem trước 3 bóng",
    "badge": "Huyền thoại",
    "color": "#183D32"
  },
  {
    "id": "dat-bom-bomberman",
    "title": "Bom Vườn",
    "tagline": "Đặt bom, né lửa, dọn sạch sâu bọ.",
    "category": "Hành động",
    "section": "hot",
    "players": "1 người",
    "duration": "5-10 phút",
    "mechanic": "Đi quanh thùng, đặt bom hẹn giờ, tránh luồng nổ, dọn sâu bọ để mở cổng",
    "badge": "Bản thử",
    "color": "#527b59"
  },
  {
    "id": "ban-xe-tang-1990",
    "title": "Xe Săn Bụi",
    "tagline": "Lái xe, ngắm hướng, giữ lõi tín hiệu.",
    "category": "Hành động",
    "section": "all",
    "players": "1 người",
    "duration": "2-4 phút",
    "mechanic": "Bắn drone tuần tra trước khi chúng chạm lõi; đá chắn đường đạn",
    "badge": "Bản thử",
    "color": "#4d8e83"
  },
  {
    "id": "nong-trai-vui-ve",
    "title": "Vườn Nắng",
    "tagline": "Gieo hạt, ngắm cây lớn, gom mùa thu hoạch.",
    "category": "Quản lý",
    "section": "quick",
    "players": "1 người",
    "duration": "1-2 phút",
    "mechanic": "Chọn hạt, chạm luống để trồng; cây lớn theo thời gian, nông sản chín tự vào giỏ.",
    "badge": "Bản thử",
    "color": "#74A25B"
  },
  {
    "id": "gunny-2d",
    "title": "Gió Ngang",
    "tagline": "Đọc gió, chỉnh góc và lực, phá đồi đối thủ.",
    "category": "Kỹ năng",
    "section": "quick",
    "players": "1 người",
    "duration": "2-4 phút",
    "mechanic": "Di chuyển, căn góc và lực theo gió; bắn phá địa hình để hạ 3 tim.",
    "badge": "Bản thử",
    "color": "#5E8A84"
  },
  {
    "id": "nuoi-ca-nemo",
    "title": "Bể Sao",
    "tagline": "Thả mồi, chăm cá, đuổi sinh vật lạ.",
    "category": "Mô phỏng",
    "section": "quick",
    "players": "1 người",
    "duration": "1 phút",
    "mechanic": "Thả mồi cho cá lớn lên; ngọc tự thu, chạm sinh vật lạ để xua đi.",
    "badge": "Bản thử",
    "color": "#1787A3"
  },
  {
    "id": "diner-dash",
    "title": "Tiệm Lá Trà",
    "tagline": "Sắp bàn, nhận món, phục vụ đúng lúc.",
    "category": "Quản lý",
    "section": "quick",
    "players": "1 người",
    "duration": "3-8 phút",
    "mechanic": "Chọn khách, xếp bàn, lấy món ở bếp và giao trước khi hết chờ",
    "badge": "Bản thử",
    "color": "#557d62"
  },
  {
    "id": "zuma-ech-ban-ngoc",
    "title": "Đường Ngọc",
    "tagline": "Bắn ghép màu, dọn sạch đường.",
    "category": "Kỹ năng",
    "section": "quick",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Game bắn chuỗi ngọc nguyên bản: ghép 3, đổi ngọc, kéo chuỗi và hoàn thành 3 đường.",
    "badge": "Bản thử",
    "color": "#183D32"
  },
  {
    "id": "co-caro",
    "title": "Cờ Caro",
    "tagline": "Nối đúng 5 dấu, lượt X rồi O.",
    "category": "Chiến thuật",
    "section": "friends",
    "players": "2 người",
    "duration": "3-10 phút",
    "mechanic": "Hai người cùng bàn; nối đúng 5 dấu để thắng, bàn kín không có hàng thắng thì hòa.",
    "badge": "Bản thử",
    "color": "#315BB5"
  },
  {
    "id": "co-tuong",
    "title": "Cờ Tướng",
    "tagline": "Đỏ đi trước. Chiếu bí để thắng.",
    "category": "Chiến thuật",
    "section": "friends",
    "players": "2 người",
    "duration": "5-30 phút",
    "mechanic": "Đấu cờ tướng hai người trên cùng một bàn",
    "badge": "Trí tuệ",
    "color": "#C75B3A"
  },
  {
    "id": "ban-bi-ve",
    "title": "Bắn Bi Ve Tuổi Thơ",
    "tagline": "Căn góc búng bi đẩy bi đối thủ ra khỏi vòng.",
    "category": "Kỹ năng",
    "section": "friends",
    "players": "2-4 người",
    "duration": "3-5 phút",
    "mechanic": "Vật lý va chạm bi ve căn góc và lực búng ngón tay",
    "badge": "Dân gian",
    "color": "#3B82F6"
  },
  {
    "id": "o-an-quan",
    "title": "Ô Ăn Quan",
    "tagline": "Rải từng viên sỏi, vét sạch ô quan.",
    "category": "Chiến thuật",
    "section": "friends",
    "players": "2 người",
    "duration": "5-10 phút",
    "mechanic": "Rải quân theo vòng tròn ô bàn cờ tính nước đi",
    "badge": "Dân gian",
    "color": "#F4A261"
  },
  {
    "id": "do-min-minesweeper",
    "title": "Dò Mìn (Minesweeper)",
    "tagline": "Mở ô, đọc số, gỡ từng nút thắt.",
    "category": "Giải đố",
    "section": "quick",
    "players": "1 người",
    "duration": "2-5 phút",
    "mechanic": "Suy luận logic tìm mìn xung quanh các ô số 1-8",
    "badge": "Kinh điển",
    "color": "#183D32"
  },
  {
    "id": "xep-gach-tetris",
    "title": "Xếp Khối",
    "tagline": "Xếp kín hàng, giữ bàn trống.",
    "category": "Giải đố",
    "section": "quick",
    "players": "1 người",
    "duration": "3-8 phút",
    "mechanic": "Xoay và thả khối để dọn hàng trong vòng chơi nguyên bản.",
    "badge": "Bản thử",
    "color": "#3B82F6"
  },
  {
    "id": "pac-man",
    "title": "Lối Sáng",
    "tagline": "Gom ánh sáng, lách qua lính gác.",
    "category": "Hành động",
    "section": "quick",
    "players": "1 người",
    "duration": "3-5 phút",
    "mechanic": "Dẫn đèn qua ba mê lộ nguyên bản, gom tinh thể và tránh lính gác.",
    "badge": "Bản thử",
    "color": "#F4A261"
  },
  {
    "id": "ran-san-moi-snake",
    "title": "Rắn Săn Mồi (Snake)",
    "tagline": "Ăn hạt để dài thêm, tránh tường và thân.",
    "category": "Kỹ năng",
    "section": "quick",
    "players": "1 người",
    "duration": "2-5 phút",
    "mechanic": "Điều hướng rắn 4 chiều ăn mồi tăng chiều dài",
    "badge": "Bản thử",
    "color": "#C8FF4A"
  },
  {
    "id": "plants-vs-zombies-2d",
    "title": "Bờ Kè Sao",
    "tagline": "Đặt đèn, hãm sương, giữ hải đăng.",
    "category": "Chiến thuật",
    "section": "all",
    "players": "1 người",
    "duration": "2-4 phút",
    "mechanic": "Đặt khí cụ tự động, giữ năm hành lang trước bốn làn sương",
    "badge": "Bản thử",
    "color": "#5d8390"
  },
  {
    "id": "feeding-frenzy",
    "title": "Cá Lớn Nuốt Cá Bé",
    "tagline": "Nuốt sinh vật nhỏ hơn để tiến hóa cá mập.",
    "category": "Hành động",
    "section": "all",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Bơi dưới đại dương ăn cá nhỏ hơn tránh cá khổng lồ",
    "badge": "PopCap",
    "color": "#3B82F6"
  },
  {
    "id": "peggle-pachinko",
    "title": "Bật Chốt",
    "tagline": "Bắn bi nảy qua chốt cam; khay cho thêm lượt.",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1 người",
    "duration": "3-5 phút",
    "mechanic": "Dọn 25 chốt cam trong 10 bi; khay di động bắt bi để hoàn lượt.",
    "badge": "Bản thử",
    "color": "#d57a46"
  },
  {
    "id": "lemonade-tycoon",
    "title": "Quầy Nước Chanh",
    "tagline": "Chọn vị chanh và giá bán theo thời tiết.",
    "category": "Quản lý",
    "section": "all",
    "players": "1 người",
    "duration": "45 giây",
    "mechanic": "Chọn tỷ lệ chanh, đường, đá và giá; chạm mục tiêu lãi trong một ca ngắn.",
    "badge": "Bản thử",
    "color": "#e6ad4b"
  },
  {
    "id": "pizza-frenzy",
    "title": "Pizza Frenzy Giao Bánh",
    "tagline": "Nghe chuông đặt hàng, giao pizza nóng hổi.",
    "category": "Quản lý",
    "section": "all",
    "players": "1 người",
    "duration": "3-5 phút",
    "mechanic": "Ghép đơn pizza và điều xe giao đúng nhà trên bản đồ",
    "badge": "PopCap",
    "color": "#C75B3A"
  },
  {
    "id": "heavy-weapon",
    "title": "Heavy Weapon Xe Tăng",
    "tagline": "Bắn hạ trực thăng và máy bay ném bom địch.",
    "category": "Hành động",
    "section": "all",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Xe tăng bắn đạn phòng không quét sạch bầu trời",
    "badge": "PopCap",
    "color": "#EF4444"
  },
  {
    "id": "typer-shark",
    "title": "Typer Shark Luyện Gõ",
    "tagline": "Gõ đúng chữ trên lưng cá mập trước khi bị cắn!",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1 người",
    "duration": "3-5 phút",
    "mechanic": "Gõ phím theo ký tự bơi của đàn cá mập đại dương",
    "badge": "PopCap",
    "color": "#3B82F6"
  },
  {
    "id": "chuzzle",
    "title": "Chuzzle Sinh Vật Lông",
    "tagline": "Trượt các sinh vật lông xù mắt nhấp nháy.",
    "category": "Giải đố",
    "section": "all",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Trượt nguyên hàng/cột ghép 3 sinh vật cùng màu",
    "badge": "PopCap",
    "color": "#C8FF4A"
  },
  {
    "id": "flappy-bird",
    "title": "Mạch Gió",
    "tagline": "Vỗ một nhịp, lướt qua khe đá.",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1 người",
    "duration": "1-3 phút",
    "mechanic": "Chạm nhịp bay giữ thăng bằng vượt qua chướng ngại",
    "badge": "Việt Nam",
    "color": "#C8FF4A"
  },
  {
    "id": "chem-hoa-qua",
    "title": "Vườn Bật Nảy",
    "tagline": "Vuốt qua quả bay, né vật nguy hiểm.",
    "category": "Hành động",
    "section": "all",
    "players": "1 người",
    "duration": "2-4 phút",
    "mechanic": "Vuốt quả bay để ghi điểm, tránh vật nguy hiểm",
    "badge": "Bản thử",
    "color": "#EF4444"
  },
  {
    "id": "lua-va-nuoc",
    "title": "Lửa & Nước (Fireboy & Watergirl)",
    "tagline": "Hai đứa phối hợp nhịp nhàng vượt đầm hồ.",
    "category": "Giải đố",
    "section": "all",
    "players": "2 người",
    "duration": "5-12 phút",
    "mechanic": "Co-op 2 nhân vật gạt cần, đạp nút mở cửa",
    "badge": "Flash",
    "color": "#3B82F6"
  },
  {
    "id": "mario-co-dien",
    "title": "Vòm Mây",
    "tagline": "Lướt qua các mỏm mây, gom chuông gió, tìm cổng sáng.",
    "category": "Hành động",
    "section": "all",
    "players": "1 người",
    "duration": "3-8 phút",
    "mechanic": "Platformer ngang với nhảy giữ-nút, gió đẩy và chuông gió để mở cổng",
    "badge": "Bản thử",
    "color": "#426c78"
  },
  {
    "id": "nguoi-tuyet-snow-bros",
    "title": "Người Tuyết (Snow Bros)",
    "tagline": "Lăn quả cầu tuyết đè bẹp yêu quái.",
    "category": "Hành động",
    "section": "all",
    "players": "1-2 người",
    "duration": "4-8 phút",
    "mechanic": "Bắn tuyết bọc quái vật thành khối tròn rồi đẩy lăn",
    "badge": "Arcade",
    "color": "#3B82F6"
  },
  {
    "id": "angry-birds-mini",
    "title": "Bắn Chim Angry Birds",
    "tagline": "Kéo súng cao su bắn sập chuồng heo xanh.",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Vật lý động năng kéo thả góc bắn phá hủy cấu trúc",
    "badge": "Kinh điển",
    "color": "#EF4444"
  },
  {
    "id": "cut-the-rope",
    "title": "Cắt Dây Cho Ếch Om Nom",
    "tagline": "Cắt dây đưa kẹo ngọt vào miệng chú ếch.",
    "category": "Giải đố",
    "section": "all",
    "players": "1 người",
    "duration": "2-5 phút",
    "mechanic": "Cắt dây trọng lực kết hợp bong bóng bay ăn 3 ngôi sao",
    "badge": "Kinh điển",
    "color": "#183D32"
  },
  {
    "id": "ban-ruoi-galaga",
    "title": "Bắn Ruồi (Galaga)",
    "tagline": "Phi thuyền đáy màn hình bắn bầy bọ vũ trụ.",
    "category": "Hành động",
    "section": "all",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Di chuyển ngang né đạn và bắn phi đội quái vật lượn vòng",
    "badge": "Arcade",
    "color": "#3B82F6"
  },
  {
    "id": "pha-gach-dx-ball",
    "title": "Phá Gạch",
    "tagline": "Đỡ bóng, phá gạch, giữ lượt.",
    "category": "Hành động",
    "section": "all",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Đỡ bóng bằng thanh trượt, phá hết gạch để sang màn.",
    "badge": "Bản thử",
    "color": "#3B82F6"
  },
  {
    "id": "day-thung-sokoban",
    "title": "Đẩy Thùng",
    "tagline": "Đẩy hòm gỗ vào đúng ô đích, không kéo.",
    "category": "Giải đố",
    "section": "all",
    "players": "1 người",
    "duration": "4-8 phút",
    "mechanic": "Đẩy thùng lên ô đích, không thể kéo",
    "badge": "Bản thử",
    "color": "#183D32"
  },
  {
    "id": "noi-ong-nuoc-pipemania",
    "title": "Nối Ống Nước",
    "tagline": "Xoay khớp nối, dẫn nước qua lưới trước khi cạn áp lực.",
    "category": "Giải đố",
    "section": "all",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Xoay các đoạn ống vuông góc để dẫn nước từ vòi đến bể trước khi hết áp lực.",
    "badge": "Logic",
    "color": "#3B82F6"
  },
  {
    "id": "tro-choi-2048",
    "title": "Trò Chơi 2048",
    "tagline": "Trượt 4 hướng gộp đôi số tạo khối 2048.",
    "category": "Giải đố",
    "section": "all",
    "players": "1 người",
    "duration": "5-15 phút",
    "mechanic": "Trượt các số lũy thừa 2 hợp nhất thành số lớn hơn",
    "badge": "Logic",
    "color": "#F4A261"
  },
  {
    "id": "xep-bai-nhen-spider",
    "title": "Bài Nhện",
    "tagline": "Gom dãy cùng chất từ K xuống A.",
    "category": "Giải đố",
    "section": "all",
    "players": "1 người",
    "duration": "5-10 phút",
    "mechanic": "Xếp tám dãy 13 lá cùng chất; dọn hết bài.",
    "badge": "Bản thử",
    "color": "#286153"
  },
  {
    "id": "xep-bai-solitaire",
    "title": "Bảy Cột",
    "tagline": "Lật bài, mở lối và xếp đủ bốn chất.",
    "category": "Giải đố",
    "section": "quick",
    "players": "1 người",
    "duration": "4-8 phút",
    "mechanic": "Xếp bảy cột giảm dần xen kẽ màu, lật từng lá và hoàn thành bốn nền Át–K.",
    "badge": "Windows",
    "color": "#3B82F6"
  },
  {
    "id": "xep-bai-freecell",
    "title": "Bốn Ô",
    "tagline": "Dọn lối bốn ô, xếp hết bộ bài theo chất.",
    "category": "Giải đố",
    "section": "quick",
    "players": "1 người",
    "duration": "4-8 phút",
    "mechanic": "Sắp đủ bốn nền từ Át lên K; dùng bốn ô trống để xoay bài.",
    "badge": "Windows",
    "color": "#3B82F6"
  },
  {
    "id": "pinball-3d-space-cadet",
    "title": "Pinball 3D Space Cadet",
    "tagline": "Phóng quả bi sắt nảy ăn điểm trạm vũ trụ.",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1 người",
    "duration": "3-7 phút",
    "mechanic": "Hai cần gạt hứng bóng sắt va đập còi hụ nhân điểm",
    "badge": "Windows",
    "color": "#C8FF4A"
  },
  {
    "id": "danh-bai-uno",
    "title": "Sắc Chuyền",
    "tagline": "Ghép mùa hoặc số, thoát bài trước đối thủ.",
    "category": "Party",
    "section": "all",
    "players": "1 người",
    "duration": "1-3 phút",
    "mechanic": "Ghép biểu tượng mùa hoặc số; lá gió rút hai, giọt sương đổi mùa",
    "badge": "Bản thử",
    "color": "#597a69"
  },
  {
    "id": "dap-chuot-chui",
    "title": "Đập Chuột Chũi Whac-A-Mole",
    "tagline": "Bắt 12 mục tiêu trước ba lần sượt.",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1 người",
    "duration": "1 phút",
    "mechanic": "Nhấp chuột cực nhanh khi chuột nhô đầu lên",
    "badge": "Arcade",
    "color": "#C75B3A"
  },
  {
    "id": "xay-cau-bridge-builder",
    "title": "Xây Cầu Vật Lý (Bridge Builder)",
    "tagline": "Nối dầm thép chịu tải trọng tàu xe lăn qua.",
    "category": "Giải đố",
    "section": "all",
    "players": "1 người",
    "duration": "5-10 phút",
    "mechanic": "Thiết kế kết cấu giàn chịu ứng suất nén và kéo",
    "badge": "Physics",
    "color": "#C75B3A"
  },
  {
    "id": "truc-thang-heli-attack",
    "title": "Trực Thăng Bắn Súng (Heli Attack)",
    "tagline": "Né tên lửa tầm nhiệt bắn phá mục tiêu đất.",
    "category": "Hành động",
    "section": "all",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Lượn trực thăng nhặt vũ khí đạn chùm và súng máy",
    "badge": "Flash",
    "color": "#EF4444"
  },
  {
    "id": "thu-thanh-bloons-td",
    "title": "Thủ Thành Khỉ Ném Phi Tiêu",
    "tagline": "Đặt tháp khỉ làm nổ các đợt bóng bay.",
    "category": "Chiến thuật",
    "section": "all",
    "players": "1 người",
    "duration": "5-12 phút",
    "mechanic": "Xây dựng tháp canh phòng thủ theo tuyến đường đi",
    "badge": "Thủ thành",
    "color": "#F4A261"
  },
  {
    "id": "contra-2d",
    "title": "Contra 2D Cổ Điển",
    "tagline": "Nhảy bắn súng đạn S tiêu diệt trùm đảo.",
    "category": "Hành động",
    "section": "all",
    "players": "1-2 người",
    "duration": "5-10 phút",
    "mechanic": "Chạy nhảy bắn súng 8 hướng ăn đạn lan và đạn laze",
    "badge": "NES",
    "color": "#3B82F6"
  },
  {
    "id": "bong-bong-nuoc-bubble-trouble",
    "title": "Bắn Bong Bóng Nước (Bubble Trouble)",
    "tagline": "Bắn dây móc chẻ đôi các quả bóng nảy.",
    "category": "Hành động",
    "section": "all",
    "players": "1-2 người",
    "duration": "3-5 phút",
    "mechanic": "Bắn dây lao lên trần nhà chia nhỏ quả bóng nảy",
    "badge": "Flash",
    "color": "#3B82F6"
  },
  {
    "id": "crossy-road",
    "title": "Băng Qua Đường (Crossy Road)",
    "tagline": "Nhảy lách làn xe chạy và khúc gỗ trôi sông.",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1 người",
    "duration": "2-5 phút",
    "mechanic": "Nhảy tiến lùi né dòng xe và xe lửa lao vun vút",
    "badge": "Kỹ năng",
    "color": "#C8FF4A"
  },
  {
    "id": "sonic-chay-nhanh",
    "title": "Nhím Sonic Chạy Nhanh",
    "tagline": "Cuộn tròn tăng tốc ăn nhẫn vàng qua vòng xoáy.",
    "category": "Hành động",
    "section": "all",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Tốc độ siêu thanh nhảy dẫm quái nhặt nhẫn bảo hộ",
    "badge": "Sega",
    "color": "#3B82F6"
  },
  {
    "id": "dua-xe-nam-mario-kart",
    "title": "Đua Xe Nấm Mini",
    "tagline": "Thả vỏ chuối và mai rùa cản đường đối thủ!",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1-4 người",
    "duration": "3-6 phút",
    "mechanic": "Đua xe kart 2D nhặt hộp quà tăng tốc và vũ khí",
    "badge": "Kinh điển",
    "color": "#F4A261"
  },
  {
    "id": "pong-1972",
    "title": "Bóng Bàn Cổ Điển",
    "tagline": "Đỡ bóng nảy, đưa qua vợt đối thủ.",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1-2 người",
    "duration": "2-4 phút",
    "mechanic": "Đỡ bóng trước máy hoặc rủ thêm một người chơi cùng",
    "badge": "Bản thử",
    "color": "#FFFFFF"
  },
  {
    "id": "rambo-lun-metal-slug",
    "title": "Rambo Lùn (Metal Slug Mini)",
    "tagline": "Giải cứu con tin râu bạc, lái xe tăng bọc thép.",
    "category": "Hành động",
    "section": "all",
    "players": "1-2 người",
    "duration": "5-10 phút",
    "mechanic": "Bắn súng đi cảnh ăn lựu đạn và đạn súng máy Heavy Machinegun",
    "badge": "Arcade",
    "color": "#C75B3A"
  },
  {
    "id": "excitebike-dua-xe-dia-hinh",
    "title": "Đua Xe Đạp Địa Hình (Excitebike)",
    "tagline": "Vặn ga nhảy qua các gờ dốc làm mát máy.",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1 người",
    "duration": "3-5 phút",
    "mechanic": "Căn góc tiếp đất xe mô tô vượt địa hình đồi cát",
    "badge": "NES",
    "color": "#C75B3A"
  },
  {
    "id": "dr-mario-diet-khuan",
    "title": "Ống Nghiệm",
    "tagline": "Xoay cặp nang, ghép 4 màu để dọn mầm.",
    "category": "Giải đố",
    "section": "all",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Ghép 4+ nửa nang hoặc mầm cùng màu để dọn sạch ống.",
    "badge": "Bản thử",
    "color": "#c87562"
  },
  {
    "id": "circus-charlie-xiec",
    "title": "Xiếc Khỉ Nhảy Lửa (Circus Charlie)",
    "tagline": "Cưỡi sư tử nhảy qua vòng lửa hội chợ.",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1 người",
    "duration": "2-4 phút",
    "mechanic": "Căn thời điểm nhảy qua các vòng lửa và bình dầu",
    "badge": "NES",
    "color": "#F4A261"
  },
  {
    "id": "kung-fu-master",
    "title": "Kung Fu Thiếu Lâm Tự",
    "tagline": "Đấm đá hạ gục đối thủ leo lên các tầng tháp.",
    "category": "Hành động",
    "section": "all",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Song đấu võ thuật đánh ngã đao phủ giải cứu công chúa",
    "badge": "NES",
    "color": "#C75B3A"
  },
  {
    "id": "nem-lon-truong-lang",
    "title": "Sân Bụi",
    "tagline": "Căn góc và lực ném, hạ đủ lon qua ba chặng.",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1 người",
    "duration": "2-4 phút",
    "mechanic": "Dùng quỹ đạo và va chạm để hạ chồng lon trong số lượt giới hạn.",
    "badge": "Bản thử",
    "color": "#3c7880"
  },
  {
    "id": "tat-lon-via-he",
    "title": "Tạt Lon Vỉa Hè",
    "tagline": "Chạy nhanh cứu bạn khi lon bị tạt đổ!",
    "category": "Hành động",
    "section": "friends",
    "players": "2-4 người",
    "duration": "3-5 phút",
    "mechanic": "Tạt đổ lon và chạy thoát khỏi tầm bắt của người giữ lon",
    "badge": "Dân gian",
    "color": "#F4A261"
  },
  {
    "id": "ban-ga-vu-tru",
    "title": "Tuyến Sáng",
    "tagline": "Lướt ngang, bắn khối sáng, tránh tia cam.",
    "category": "Hành động",
    "section": "all",
    "players": "1-2 người",
    "duration": "4-8 phút",
    "mechanic": "Điều khiển phi thuyền, bắn đội hình địch, tránh đạn",
    "badge": "Bản thử",
    "color": "#F4A261"
  },
  {
    "id": "rong-den-mortal-kombat",
    "title": "Rồng Đen 2D Mini",
    "tagline": "Đấu võ song đấu chưởng quyền tung đòn kết liễu.",
    "category": "Hành động",
    "section": "friends",
    "players": "2 người",
    "duration": "3-5 phút",
    "mechanic": "Bấm tổ hợp phím ra đòn thế võ thuật đối kháng",
    "badge": "Đối kháng",
    "color": "#EF4444"
  },
  {
    "id": "co-ca-ngua",
    "title": "Cờ Cá Ngựa Việt Nam",
    "tagline": "Đổ xúc xắc xuất chuồng đá ngựa về đích.",
    "category": "Party",
    "section": "friends",
    "players": "2-4 người",
    "duration": "5-15 phút",
    "mechanic": "Đổ xúc xắc di chuyển ngựa trên bàn cờ 4 màu",
    "badge": "Dân gian",
    "color": "#3B82F6"
  },
  {
    "id": "co-ty-phu-monopoly",
    "title": "Cờ Tỷ Phú Mini",
    "tagline": "Mua đất xây khách sạn thu tiền thuê của đối thủ.",
    "category": "Chiến thuật",
    "section": "friends",
    "players": "2-4 người",
    "duration": "10-20 phút",
    "mechanic": "Đổ xí ngầu mua bán bất động sản và thu phí thuê đất",
    "badge": "Bàn cờ",
    "color": "#183D32"
  },
  {
    "id": "ai-la-trieu-phu",
    "title": "Ai Là Triệu Phú Mini",
    "tagline": "15 câu hỏi trắc nghiệm kiến thức với 4 quyền trợ giúp.",
    "category": "Trí tuệ",
    "section": "all",
    "players": "1 người",
    "duration": "5-10 phút",
    "mechanic": "Hỏi đáp trắc nghiệm âm thanh giọng đọc kịch tính",
    "badge": "Trí tuệ",
    "color": "#3B82F6"
  },
  {
    "id": "duo-hinh-bat-chu",
    "title": "Đoán Hình Bắt Chữ",
    "tagline": "Ghép 2 bức hình suy luận câu thành ngữ quen.",
    "category": "Giải đố",
    "section": "all",
    "players": "1 người",
    "duration": "3-5 phút",
    "mechanic": "Nhìn hình ảnh gợi ý đoán từ khóa thành ngữ tiếng Việt",
    "badge": "Vui nhộn",
    "color": "#C8FF4A"
  },
  {
    "id": "tim-diem-khac-biet",
    "title": "Tìm Điểm Khác Biệt",
    "tagline": "Soi hai ảnh, tìm 5 chỗ khác trước khi hết giờ.",
    "category": "Chill",
    "section": "all",
    "players": "1 người",
    "duration": "1-2 phút",
    "mechanic": "Quan sát chi tiết hình ảnh nhấp đúng vị trí khác biệt",
    "badge": "Chill",
    "color": "#F4A261"
  },
  {
    "id": "thap-ha-noi-tower",
    "title": "Tháp Ba Cọc",
    "tagline": "Chuyển cả chồng đĩa từng nước một; không đặt đĩa lớn lên đĩa nhỏ.",
    "category": "Giải đố",
    "section": "all",
    "players": "1 người",
    "duration": "3-8 phút",
    "mechanic": "Di chuyển đĩa giữa ba cọc; chỉ đặt đĩa nhỏ lên đĩa lớn.",
    "badge": "Tư duy",
    "color": "#20483D"
  },
  {
    "id": "piano-tiles-phim-nhac",
    "title": "Phím Nhạc Rơi (Piano Tiles)",
    "tagline": "Nhấp đúng phím đen theo nhịp bản nhạc du dương.",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1 người",
    "duration": "2-4 phút",
    "mechanic": "Bấm phím trượt rơi theo tiết tấu giai điệu bài hát",
    "badge": "Âm nhạc",
    "color": "#3B82F6"
  },
  {
    "id": "among-us-impostor",
    "title": "Ai Là Kẻ Giả Mạo? (Among Us)",
    "tagline": "Sửa chữa trạm tàu tìm kẻ giả mạo trong nhóm.",
    "category": "Party",
    "section": "friends",
    "players": "2-6 người",
    "duration": "5-10 phút",
    "mechanic": "Làm nhiệm vụ sinh tồn và bỏ phiếu suy luận",
    "badge": "Party",
    "color": "#EF4444"
  },
  {
    "id": "skribbl-ve-doan-chu",
    "title": "Vẽ Hình Đoán Chữ (Skribbl)",
    "tagline": "Vẽ hình trên bảng cho bạn bè đoán từ khóa.",
    "category": "Party",
    "section": "friends",
    "players": "2-8 người",
    "duration": "5-15 phút",
    "mechanic": "Vẽ nét trên canvas và gõ đáp án trò chuyện",
    "badge": "Party",
    "color": "#3B82F6"
  },
  {
    "id": "bi-lac-ban-go",
    "title": "Bi Lắc Bàn Gỗ (Foosball)",
    "tagline": "Xoay tay cầm sút bóng vào lưới đối thủ.",
    "category": "Hành động",
    "section": "friends",
    "players": "2 người",
    "duration": "3-5 phút",
    "mechanic": "Điều khiển các thanh cầu thủ gạt bóng đối kháng",
    "badge": "Thể thao",
    "color": "#3B82F6"
  },
  {
    "id": "keo-co-doi-khang",
    "title": "Kéo Nhịp",
    "tagline": "Canh phách trái phải, vượt dấu đèn trong trận ba lượt.",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1 người",
    "duration": "2-4 phút",
    "mechanic": "Bước đúng nhịp để đẩy dấu đèn; nghỉ đúng lúc để hồi sức.",
    "badge": "Bản thử",
    "color": "#3c7880"
  },
  {
    "id": "lat-the-tri-nho",
    "title": "Nối Hình",
    "tagline": "Nối hai biểu tượng giống nhau qua đường trống.",
    "category": "Giải đố",
    "section": "all",
    "players": "1 người",
    "duration": "2-5 phút",
    "mechanic": "Nối cặp biểu tượng giống nhau bằng đường ngang dọc tối đa hai lần rẽ.",
    "badge": "Bản thử",
    "color": "#FBBF24"
  },
  {
    "id": "khoi-rubik-mini",
    "title": "Khối Sắc",
    "tagline": "Nối các mẫu tín hiệu bằng vài lượt xoay mặt.",
    "category": "Giải đố",
    "section": "all",
    "players": "1 người",
    "duration": "2-4 phút",
    "mechanic": "Xoay các ô màu trên sáu mặt để ghép mô-típ từng chặng.",
    "badge": "Bản thử",
    "color": "#8A74C6"
  },
  {
    "id": "ninja-cuu-me",
    "title": "Ninja Cứu Mẹ (Legend of Kage)",
    "tagline": "Nhảy ngọn cây phi phi tiêu qua rừng trúc.",
    "category": "Hành động",
    "section": "all",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Nhảy cao lướt qua cành cây chém kiếm tiêu diệt ninja địch",
    "badge": "NES",
    "color": "#183D32"
  },
  {
    "id": "bomberman-93-arena",
    "title": "Đấu Trường Bomberman 4 Người",
    "tagline": "4 người cùng đặt bom sinh tồn trên 1 máy.",
    "category": "Hành động",
    "section": "friends",
    "players": "2-4 người",
    "duration": "3-5 phút",
    "mechanic": "Chạy trốn sóng nổ và đá bom bẫy người chơi khác",
    "badge": "Đấu trường",
    "color": "#EF4444"
  },
  {
    "id": "dua-xe-micro-machines",
    "title": "Đua Xe Đồ Chơi (Micro Machines)",
    "tagline": "Lái xe mini trên bàn ăn né thìa nĩa đĩa súp.",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1-4 người",
    "duration": "3-5 phút",
    "mechanic": "Lái xe góc nhìn trên tránh các chướng ngại bàn ăn",
    "badge": "NES",
    "color": "#C75B3A"
  },
  {
    "id": "puzzle-bobble-khung-long",
    "title": "Bi Vòm",
    "tagline": "Bắn bóng, ghép 3 màu để rơi cụm.",
    "category": "Giải đố",
    "section": "all",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Bắn bóng dội tường, ghép cụm 3+ màu rồi làm rơi phần treo.",
    "badge": "Bản thử",
    "color": "#568d83"
  },
  {
    "id": "arkanoid-dap-gach",
    "title": "Vệ Tinh Giữ Quỹ Đạo",
    "tagline": "Đỡ bóng, xuyên tường bạc, bắt viên nở rộng.",
    "category": "Hành động",
    "section": "all",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Phá tường bằng bóng; bạc chịu hai hit, vàng chặn bóng.",
    "badge": "Bản thử",
    "color": "#35628b"
  },
  {
    "id": "sky-garden-khu-vuon-tren-may",
    "title": "Khu Vườn Trên Mây",
    "tagline": "Trồng hoa cúc, hoa hồng trên các tầng mây.",
    "category": "Chill",
    "section": "all",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Chăm sóc chậu hoa trên mây, thu hoạch ép nước hoa",
    "badge": "Zing Me",
    "color": "#C8FF4A"
  },
  {
    "id": "dao-rong-dragon-island",
    "title": "Ấp Trứng Đảo Rồng",
    "tagline": "Ấp trứng rồng lửa, lai tạo giống rồng thần thoại.",
    "category": "Quản lý",
    "section": "all",
    "players": "1 người",
    "duration": "4-8 phút",
    "mechanic": "Nuôi dưỡng và lai tạo các hệ rồng chiến đấu",
    "badge": "Zing Me",
    "color": "#EF4444"
  },
  {
    "id": "tien-len-mien-nam",
    "title": "Tiến Lên Miền Nam Cổ Điển",
    "tagline": "Sảnh rồng, đôi thông, tứ quý chặt heo đỏ!",
    "category": "Party",
    "section": "friends",
    "players": "2-4 người",
    "duration": "5-10 phút",
    "mechanic": "Đánh bài dân gian 52 lá chặt heo tới trắng",
    "badge": "Dân gian",
    "color": "#EF4444"
  },
  {
    "id": "phi-tieu-bong-bong",
    "title": "Phi Tiêu Nổ Bóng Bay",
    "tagline": "Căn góc ném phi tiêu nổ bóng hội chợ.",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1 người",
    "duration": "2-4 phút",
    "mechanic": "Căn tọa độ ném phi tiêu nổ bóng chuyển động",
    "badge": "Hội chợ",
    "color": "#EF4444"
  },
  {
    "id": "gap-thu-bong-dien-tu",
    "title": "Gắp Thú Bông Điện Tử",
    "tagline": "Căn cần gạt gắp đúng chú gấu bông xinh.",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1 người",
    "duration": "2-4 phút",
    "mechanic": "Điều khiển cần gạt 2D gắp gấu bông thả vào hộc",
    "badge": "Kỹ năng",
    "color": "#F4A261"
  },
  {
    "id": "tam-cuc-co-dien",
    "title": "Tổ Tôm Tam Cúc",
    "tagline": "Trò chơi thẻ bài cổ truyền ngày tết.",
    "category": "Chiến thuật",
    "section": "all",
    "players": "2-4 người",
    "duration": "5-10 phút",
    "mechanic": "Chơi thẻ bài tướng sĩ tượng xe pháo mã dân tộc",
    "badge": "Dân gian",
    "color": "#C75B3A"
  },
  {
    "id": "nem-vong-co-chai",
    "title": "Ném Vòng Cổ Chai",
    "tagline": "Quăng chiếc vòng tre lọt trúng cổ chai ngọt lịm.",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1 người",
    "duration": "2-4 phút",
    "mechanic": "Vật lý quỹ đạo ném vòng trúng mục tiêu chai",
    "badge": "Hội chợ",
    "color": "#C8FF4A"
  },
  {
    "id": "lac-bau-cua-tom-ca",
    "title": "Lắc Bầu Cua Tôm Cá",
    "tagline": "Lắc 3 quân xúc xắc Bầu, Cua, Tôm, Cá, Gà, Nai.",
    "category": "Party",
    "section": "friends",
    "players": "2-6 người",
    "duration": "3-6 phút",
    "mechanic": "Đặt cược vui nhộn đón tết ngày hội",
    "badge": "Dân gian",
    "color": "#EF4444"
  },
  {
    "id": "chay-tron-canh-sat-subway",
    "title": "Chạy Trên Đường Ray (Subway Runner)",
    "tagline": "Trượt gầm toa tàu, nhảy né rào chắn nhặt xu.",
    "category": "Hành động",
    "section": "all",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Chạy 3 làn né tàu hỏa và hút nam châm nhặt tiền vàng",
    "badge": "Kinh điển",
    "color": "#3B82F6"
  },
  {
    "id": "nguoi-que-ban-cung",
    "title": "Người Que Bắn Cung (Stickman Archer)",
    "tagline": "Kéo cung căn góc bắn hạ cung thủ đối phương.",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1-2 người",
    "duration": "2-5 phút",
    "mechanic": "Kéo căng dây cung căn góc và lực triệt hạ kẻ thù",
    "badge": "Kỹ năng",
    "color": "#183D32"
  },
  {
    "id": "dau-vat-hai-nguoi",
    "title": "Đấu Vật Hai Người (Wrestle Jump)",
    "tagline": "Nhấp một nút duy nhất đạp chân lật đầu đối thủ.",
    "category": "Party",
    "section": "friends",
    "players": "2 người",
    "duration": "1-3 phút",
    "mechanic": "Vật lý khớp xương 1 nút bấm lật ngửa đối thủ",
    "badge": "Vui nhộn",
    "color": "#F4A261"
  },
  {
    "id": "thoi-bong-xa-phong",
    "title": "Thổi Bong Bóng Xà Phòng",
    "tagline": "Chạm ngón tay nổ từng quả bong bóng óng ánh.",
    "category": "Chill",
    "section": "all",
    "players": "1 người",
    "duration": "2-5 phút",
    "mechanic": "Tương tác nổ bong bóng thư giãn giải tỏa căng thẳng",
    "badge": "Chill",
    "color": "#3B82F6"
  },
  {
    "id": "tiem-banh-ngot-ba-baker",
    "title": "Tiệm Bánh Ngọt Cupcake",
    "tagline": "Bắt kem trang trí quả anh đào lên bánh ngọt.",
    "category": "Chill",
    "section": "all",
    "players": "1 người",
    "duration": "3-5 phút",
    "mechanic": "Trang trí bánh kem theo mẫu yêu cầu",
    "badge": "Chill",
    "color": "#F4A261"
  },
  {
    "id": "dap-ruoi-ban-tay",
    "title": "Đập Ruồi Bàn Tay Vàng",
    "tagline": "Canh ruồi vừa đậu là hạ tay đập dính.",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1 người",
    "duration": "1-3 phút",
    "mechanic": "Rèn luyện phản xạ tay mắt cực nhanh",
    "badge": "Kỹ năng",
    "color": "#EF4444"
  },
  {
    "id": "xe-dap-giao-bao",
    "title": "Cậu Bé Giao Báo (Paperboy)",
    "tagline": "Đạp xe ném tờ báo trúng hộp thư trước cửa nhà.",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Đạp xe né chó dữ và xe hơi ném báo trúng hộp thư",
    "badge": "Arcade",
    "color": "#C8FF4A"
  },
  {
    "id": "dau-truong-xe-dung",
    "title": "Xe Đụng Hội Chợ",
    "tagline": "Đạp ga húc xe bạn bè quay cuồng vòng sân.",
    "category": "Hành động",
    "section": "friends",
    "players": "2-4 người",
    "duration": "3-5 phút",
    "mechanic": "Lái xe đụng va chạm vật lý đẩy xe đối thủ",
    "badge": "Hội chợ",
    "color": "#EF4444"
  },
  {
    "id": "gap-chu-cho-qua-duong",
    "title": "Dắt Cún Qua Đường",
    "tagline": "Chờ đèn xanh dắt đàn cún cưng sang đường an toàn.",
    "category": "Chill",
    "section": "all",
    "players": "1 người",
    "duration": "2-4 phút",
    "mechanic": "Căn thời điểm vạch kẻ đường dẫn các chú cún qua phố",
    "badge": "Chill",
    "color": "#183D32"
  },
  {
    "id": "tiem-sach-cu-pho-co",
    "title": "Kệ Sách Ký Ức",
    "tagline": "Đọc manh mối, xếp gáy sách đúng hàng.",
    "category": "Giải đố",
    "section": "all",
    "players": "1 người",
    "duration": "3-5 phút",
    "mechanic": "Dịch từng cuốn liền kề để xếp hàng sách theo manh mối.",
    "badge": "Bản thử",
    "color": "#C75B3A"
  },
  {
    "id": "boom-online-bnb",
    "title": "Đấu Trường Bọt Nước",
    "tagline": "Thả bom nước, né tia bọt, giữ chiếc kim cứu mình.",
    "category": "Hành động",
    "section": "all",
    "players": "1 người + 3 máy",
    "duration": "1-3 phút",
    "mechanic": "Thả bom nước theo lưới để bẫy ba đối thủ máy; một chiếc kim giúp bạn thoát khỏi bọt.",
    "badge": "Bản thử",
    "color": "#0284C7"
  },
  {
    "id": "audition-nhip-dieu",
    "title": "Nhịp Mây",
    "tagline": "Bấm bốn mũi tên theo nốt; chốt nhịp bằng Space.",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1 người",
    "duration": "Khoảng 20 giây",
    "mechanic": "Bấm ba phím D/F/J/K theo nốt, nhấn Space để chốt mỗi câu và ghi điểm theo nhịp.",
    "badge": "Bản thử",
    "color": "#EC4899"
  },
  {
    "id": "road-rash-dua-xe-moto",
    "title": "Đua Gió",
    "tagline": "Giữ ga, né xe, tạt đối thủ áp sát.",
    "category": "Hành động",
    "section": "all",
    "players": "1 người",
    "duration": "Khoảng 1 phút",
    "mechanic": "Tăng tốc, né chướng ngại, tạt đối thủ gần nhất và về đích trong ba vị trí đầu.",
    "badge": "Bản thử",
    "color": "#E98657"
  },
  {
    "id": "rockman-mega-man",
    "title": "Mầm Chớp",
    "tagline": "Đi, nhảy, bắn hạt sáng và nạp đòn mạnh.",
    "category": "Hành động",
    "section": "all",
    "players": "1 người",
    "duration": "1-2 phút",
    "mechanic": "Đi, nhảy và bắn hạt sáng qua vườn hoang; giữ Z để nạp phát mạnh, tới cổng cuối.",
    "badge": "Bản thử",
    "color": "#39A879"
  },
  {
    "id": "duck-hunt-ban-vit",
    "title": "Mục Tiêu Bay",
    "tagline": "Ngắm theo nhịp bay, chọn thời điểm bắn.",
    "category": "Kỹ năng",
    "section": "all",
    "players": "1 người",
    "duration": "Khoảng 20 giây",
    "mechanic": "Ngắm một mục tiêu đang bay, có ba phát bắn và năm lượt ngắn để ghi điểm.",
    "badge": "Bản thử",
    "color": "#2B7085"
  },
  {
    "id": "adventure-island-dao-hoang",
    "title": "Đảo Phiêu Lưu (Adventure Island)",
    "tagline": "Cưỡi ván trượt, ném rìu đá, nhặt chuối giữ thanh sinh mệnh!",
    "category": "Hành động",
    "section": "classic",
    "players": "1 người",
    "duration": "4-8 phút",
    "mechanic": "Chạy vượt chướng ngại cuộn cảnh, ném rìu đá diệt ốc sên/quái vật, liên tục nhặt trái cây để không cạn máu",
    "badge": "Kinh điển",
    "color": "#16A34A"
  },
  {
    "id": "street-fighter-2-doi-khang",
    "title": "Nảy Lửa",
    "tagline": "Đỡ đúng nhịp, nhảy qua đòn và phản công.",
    "category": "Đối kháng",
    "section": "hot",
    "players": "1-2 người",
    "duration": "3-5 phút",
    "mechanic": "Đấu tay đôi theo hiệp; solo đấu máy mặc định, đỡ, nhảy, đấm, đá và dùng ba đòn nguyên bản.",
    "badge": "Huyền thoại",
    "color": "#DC2626"
  },
  {
    "id": "prince-of-persia-1989",
    "title": "Hoàng Tử Ba Tư Cổ Điển",
    "tagline": "60 phút sinh tử, bước chân rón rén né hầm chông và kiếm sĩ!",
    "category": "Hành động",
    "section": "classic",
    "players": "1 người",
    "duration": "5-15 phút",
    "mechanic": "Nhảy bục thực tế vật lý mượt mà (Rotoscoping), đếm ngược đồng hồ 60 phút, né bẫy chông/dao chém và đấu kiếm tay đôi",
    "badge": "Kinh điển",
    "color": "#D97706"
  },
  {
    "id": "bubble-bobble-khung-long-bong-bong",
    "title": "Mầm Gió",
    "tagline": "Bẫy mực rêu trong bọt rồi nhảy qua những tầng lá.",
    "category": "Hành động",
    "section": "quick",
    "players": "1 người",
    "duration": "3-5 phút",
    "mechanic": "Đi và nhảy qua ba sân vườn; thổi bọt bẫy mực rêu rồi chạm bọt để ghi điểm.",
    "badge": "Tuổi thơ",
    "color": "#10B981"
  },
  {
    "id": "age-of-war-thoi-dai-chien-tranh",
    "title": "Ranh Giới Mây",
    "tagline": "Gọi quân qua cầu gỗ, giữ bệ vườn của mình!",
    "category": "Chiến thuật",
    "section": "hot",
    "players": "1 người",
    "duration": "2-5 phút",
    "mechanic": "Một cây cầu nối hai bệ vườn. Chọn ba quân nguyên bản; chúng tự tiến và giao chiến, hạt nảy tự hồi, đối thủ tự gửi quân. Phá bệ bên kia để thắng.",
    "badge": "Thử nghiệm",
    "color": "#43887E"
  },
  {
    "id": "bloxorz-khoi-da-lan",
    "title": "Khối Đá Lăn",
    "tagline": "Lăn khối đá qua lối hẹp, đứng thẳng trên hố đích.",
    "category": "Giải đố",
    "section": "quick",
    "players": "1 người",
    "duration": "2-4 phút",
    "mechanic": "Lăn qua ba bàn tự tạo; khối chiếm một hoặc hai ô, tránh rìa và đứng thẳng trên hố.",
    "badge": "Đỉnh cao",
    "color": "#475569"
  },
  {
    "id": "raft-wars-ban-sung-phao",
    "title": "Đấu Phao Bãi Cạn",
    "tagline": "Giữ thăng bằng trên bè, nạp lực và đẩy đối thủ xuống biển.",
    "category": "Kỹ năng",
    "section": "quick",
    "players": "1 người",
    "duration": "2-4 phút",
    "mechanic": "Tính góc, giữ nạp lực rồi thả bóng xốp theo lượt; làm đối thủ rơi khỏi bè.",
    "badge": "Tuổi thơ",
    "color": "#0284C7"
  },
  {
    "id": "papa-pizzeria-tiem-banh-pizza",
    "title": "Tiệm Bánh Pizza Của Papa",
    "tagline": "Cán bột, rải đều topping, canh lò giòn rụm làm hài lòng thực khách!",
    "category": "Quản lý",
    "section": "hot",
    "players": "1 người",
    "duration": "4-8 phút",
    "mechanic": "Quản lý 4 trạm công đoạn ẩm thực (Order Station, Topping Station, Baking Station, Cutting Station) theo thời gian thực",
    "badge": "Kinh điển",
    "color": "#E11D48"
  },
  {
    "id": "stick-war-chien-tranh-nguoi-que",
    "title": "Chiến Tranh Người Que (Stick War)",
    "tagline": "Đào vàng, rèn kiếm sĩ, giương cung phá hủy tượng đài đối phương!",
    "category": "Chiến thuật",
    "section": "hot",
    "players": "1 người",
    "duration": "6-12 phút",
    "mechanic": "Chiến thuật thời gian thực (RTS) điều khiển dân tộc người que: khai khoáng, luyện quân, điều khiển tướng thủ công",
    "badge": "Huyền thoại",
    "color": "#334155"
  },
  {
    "id": "defend-your-castle-thu-thanh-nguoi-que",
    "title": "Bảo Vệ Lâu Đài (Defend Your Castle)",
    "tagline": "Nắm bổng kẻ địch quăng lên trời, gia cố tường thành trước biển người que!",
    "category": "Kỹ năng",
    "section": "quick",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Tương tác vật lý kéo thả chuột cực nhanh: túm lấy kẻ địch đang xông tới ném bổng lên trời cho rơi tự do",
    "badge": "Tuổi thơ",
    "color": "#78716C"
  },
  {
    "id": "donkey-kong-1981",
    "title": "Vượn Khổng Lồ Ném Thùng",
    "tagline": "Leo giàn giáo, nhảy né thùng gỗ lăn cứu lấy người đẹp!",
    "category": "Hành động",
    "section": "classic",
    "players": "1 người",
    "duration": "3-5 phút",
    "mechanic": "Nhảy bục leo thang tránh né thùng gỗ lăn theo đường dốc ziczac, nhặt búa thần đập tan chướng ngại",
    "badge": "Kinh điển",
    "color": "#C2410C"
  },
  {
    "id": "dig-dug-dao-dat-bom-quai",
    "title": "Đào Hầm Bơm Bong Bóng (Dig Dug)",
    "tagline": "Đào địa đạo lòng đất, cắm ống bơm phồng tiêu diệt quái vật!",
    "category": "Hành động",
    "section": "classic",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Đào hầm ngầm trong các tầng địa chất, phóng ống bơm làm căng phồng quái vật đến phát nổ, hoặc đào rơi đá tảng đè bẹp địch",
    "badge": "Tuổi thơ",
    "color": "#0D9488"
  },
  {
    "id": "pooyan-lon-me-ban-bong",
    "title": "Heo Mẹ Bắn Nỏ (Pooyan)",
    "tagline": "Lên xuống giỏ kéo, bắn rách bóng bay của bầy sói đói!",
    "category": "Kỹ năng",
    "section": "quick",
    "players": "1 người",
    "duration": "3-5 phút",
    "mechanic": "Kéo giỏ thang dây di chuyển theo trục dọc, bắn nỏ làm vỡ bóng bay của bầy sói đang thả dù hoặc leo dây",
    "badge": "Tuổi thơ",
    "color": "#FB7185"
  },
  {
    "id": "yie-ar-kung-fu-vo-dai",
    "title": "Đấu Võ Đường Thiếu Lâm",
    "tagline": "Thập lục tuyệt kỹ đấm đá, tỷ thí từng đệ nhất cao thủ võ lâm!",
    "category": "Đối kháng",
    "section": "classic",
    "players": "1-2 người",
    "duration": "3-5 phút",
    "mechanic": "Đối kháng võ thuật 16 thế đòn biến hóa theo 8 hướng di chuyển kết hợp phím đấm/đá, khắc chế vũ khí đặc thù của từng boss",
    "badge": "Kinh điển",
    "color": "#B91C1C"
  },
  {
    "id": "asteroids-tau-ban-thien-thach",
    "title": "Phi Thuyền Bắn Thiên Thạch",
    "tagline": "Trôi dạt không trọng lực, bắn vỡ đá vụn giữa dải ngân hà!",
    "category": "Kỹ năng",
    "section": "classic",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Vật lý quán tính không gian 2D xoay hướng và phản lực, bắn vỡ các tảng thiên thạch lớn thành các mảnh nhỏ trôi dạt",
    "badge": "Kinh điển",
    "color": "#64748B"
  },
  {
    "id": "frogger-ech-bang-qua-duong",
    "title": "Chú Ếch Sang Sông (Frogger)",
    "tagline": "Canh nhịp qua xa lộ xe cộ, nhảy trên mai rùa về tổ đầm lầy!",
    "category": "Kỹ năng",
    "section": "classic",
    "players": "1 người",
    "duration": "2-4 phút",
    "mechanic": "Nhảy từng ô lưới né tránh dòng xe cộ cao tốc và nhảy lên thân gỗ, mai rùa lặn để vượt dòng sông chảy xiết",
    "badge": "Kinh điển",
    "color": "#22C55E"
  },
  {
    "id": "elevator-action-diep-vien-thang-may",
    "title": "Điệp Viên Thang Máy",
    "tagline": "Đột nhập cửa đỏ bí mật, đu dây thang máy thoát hiểm tầng hầm!",
    "category": "Hành động",
    "section": "classic",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Điệp viên đột nhập tòa nhà 30 tầng bằng hệ thống thang máy và thang cuốn, lấy tài liệu sau các cánh cửa đỏ bí mật",
    "badge": "Kinh điển",
    "color": "#4F46E5"
  },
  {
    "id": "double-dragon-hiep-si-rong-doi",
    "title": "Rồng Đôi Song Thủ",
    "tagline": "Cú hích cùi chỏ, đá xoay người, dẹp loạn đường phố giải cứu mỹ nhân!",
    "category": "Hành động",
    "section": "hot",
    "players": "1-2 người",
    "duration": "4-8 phút",
    "mechanic": "Đi cảnh đấm đá đường phố (Beat 'em up) 2.5D, nhặt vũ khí rơi (gậy bóng chày, roi da, dao găm, thùng phuy) càn quét bang phái",
    "badge": "Huyền thoại",
    "color": "#9333EA"
  },
  {
    "id": "golden-axe-riu-vang",
    "title": "Rìu Vàng Cổ Đại (Golden Axe)",
    "tagline": "Vung búa chiến binh, cưỡi thằn lằn phun lửa, gọi sấm sét trừng phạt!",
    "category": "Hành động",
    "section": "classic",
    "players": "1-2 người",
    "duration": "4-8 phút",
    "mechanic": "Hành động chặt chém thần thoại (Hack and Slash), cưỡi quái thú chiến đấu, thu thập bình phép thuật gọi thần sấm/rồng lửa",
    "badge": "Huyền thoại",
    "color": "#D97706"
  },
  {
    "id": "cadillacs-dinosaurs-bo-doi",
    "title": "Bộ Đội Khủng Long",
    "tagline": "Cú đá lốc Mustapha, xách súng Uzi giải cứu thế giới khủng long!",
    "category": "Hành động",
    "section": "hot",
    "players": "1-2 người",
    "duration": "5-10 phút",
    "mechanic": "Hành động đi cảnh kinh điển nhất làng game thùng Việt Nam: võ thuật cận chiến, nhặt súng máy/lựu đạn bắn xối xả, lái xe Cadillac càn quét",
    "badge": "Huyền thoại",
    "color": "#15803D"
  },
  {
    "id": "snowcraft-nem-tuyet-3v3",
    "title": "Ném Tuyết Tuổi Thơ (Snowcraft)",
    "tagline": "3 chọi 3 sau bức tường tuyết, kéo thả căn lực ném ngã đội đỏ!",
    "category": "Kéo thả",
    "section": "quick",
    "players": "1 người",
    "duration": "2-4 phút",
    "mechanic": "Chiến thuật thời gian thực kéo thả vị trí và căn lực ném bóng tuyết hạ gục 3 đối thủ phe đỏ",
    "badge": "Tuổi thơ",
    "color": "#38BDF8"
  },
  {
    "id": "bowman-nguoi-que-ban-cung",
    "title": "Xạ Thủ Căn Gió Bowman",
    "tagline": "Đo góc bắn, tính độ lệch gió, một mũi tên xuyên qua khoảng cách nghìn mét!",
    "category": "Kỹ năng",
    "section": "quick",
    "players": "1-2 người",
    "duration": "2-5 phút",
    "mechanic": "Bắn cung tọa độ đối kháng 1v1 theo lượt, tính toán góc độ và lực kéo cung ngược chiều gió",
    "badge": "Kinh điển",
    "color": "#64748B"
  },
  {
    "id": "line-rider-truot-tuyet-vat-ly",
    "title": "Bút Vẽ Trượt Ván (Line Rider)",
    "tagline": "Vẽ đường ray cong vút cho cậu bé trượt ván nảy lộn nhào vô tận!",
    "category": "Chill",
    "section": "creative",
    "players": "1 người",
    "duration": "3-10 phút",
    "mechanic": "Hộp cát vật lý sáng tạo (Physics Sandbox): vẽ tự do các đường trượt mượt mà cho nhân vật trượt ván trôi theo quán tính và trọng lực",
    "badge": "Đỉnh cao",
    "color": "#0284C7"
  },
  {
    "id": "boulder-dash-tho-dao-ngoc",
    "title": "Thợ Đào Ngọc Hầm Đá",
    "tagline": "Đào đường ngầm gom kim cương, cẩn thận đá tảng sụp đè bẹp dí!",
    "category": "Giải đố",
    "section": "classic",
    "players": "1 người",
    "duration": "3-7 phút",
    "mechanic": "Đào hầm đất thu gom kim cương theo chỉ tiêu, quản lý vật lý lăn của các tảng đá tròn để không bị đè và bẫy quái vật biến thành ngọc",
    "badge": "Kinh điển",
    "color": "#854D0E"
  },
  {
    "id": "moorhuhn-ban-ga-dam-lay",
    "title": "Thợ Săn Gà Rừng (Moorhuhn)",
    "tagline": "Lia nòng súng 90 giây, bắn hạ đàn gà rừng ngơ ngác trốn bụi rậm!",
    "category": "Kỹ năng",
    "section": "quick",
    "players": "1 người",
    "duration": "2 phút",
    "mechanic": "Bắn súng ngắm săn điểm thời gian thực 90 giây, lia màn hình cuộn ngang tìm kiếm đàn gà bay ở nhiều tầng cự ly và các bí mật ẩn giấu",
    "badge": "Tuổi thơ",
    "color": "#16A34A"
  },
  {
    "id": "gun-mayhem-dau-sung-loan-da",
    "title": "Đấu Súng Loạn Đả Sàn Rơi",
    "tagline": "Đạn nổ giật tung người, bắn hất đối thủ rơi khỏi mép vực sâu!",
    "category": "Hành động",
    "section": "hot",
    "players": "1-4 người",
    "duration": "3-5 phút",
    "mechanic": "Đấu súng bục platformer 4 người hỗn chiến (Smash Bros style), vũ khí có độ giật cực mạnh đẩy lùi đối thủ rơi khỏi sàn",
    "badge": "Huyền thoại",
    "color": "#E11D48"
  },
  {
    "id": "electric-man-2-vo-thuat-nguoi-que",
    "title": "Người Que Ma Trận",
    "tagline": "Đòn thế slow-motion xoay người đạp bay kẻ địch tóe tia điện!",
    "category": "Đối kháng",
    "section": "hot",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Võ thuật đường phố người que kết hợp cơ chế quay chậm Slow-Motion Matrix, tiêu hao pin năng lượng để tung các siêu đòn thế",
    "badge": "Kinh điển",
    "color": "#2563EB"
  },
  {
    "id": "fancy-pants-chay-nhay-quan-cam",
    "title": "Chàng Quần Cam Lướt Gió",
    "tagline": "Trượt dốc uốn lượn, nhảy bực lò xo, bay bổng cùng chiếc quần cam rực rỡ!",
    "category": "Kỹ năng",
    "section": "quick",
    "players": "1 người",
    "duration": "3-7 phút",
    "mechanic": "Nhảy bục vật lý gia tốc mượt mà phong cách Sonic: lướt trên dốc cong, chạy ngược trần nhà, nhào lộn bật tường",
    "badge": "Đỉnh cao",
    "color": "#F97316"
  },
  {
    "id": "impossible-quiz-do-vui-xoan-nao",
    "title": "Đố Mẹo Xoắn Não",
    "tagline": "Suy nghĩ ngược đời, bấm chuột cẩn thận không nổ bom hẹn giờ!",
    "category": "Giải đố",
    "section": "quick",
    "players": "1 người",
    "duration": "3-8 phút",
    "mechanic": "Câu đố mẹo tương tác phá vỡ bức tường thứ tư (Think outside the box): rê chuột né bẫy, gõ chữ bí mật, căn giờ trước khi bom nổ",
    "badge": "Tuổi thơ",
    "color": "#8B5CF6"
  },
  {
    "id": "centipede-ban-sau-ret",
    "title": "Bắn Sâu Rết Nấm Rừng",
    "tagline": "Bắn đứt từng khúc rết uốn éo qua rừng nấm, né bọ chét rơi nhanh!",
    "category": "Kỹ năng",
    "section": "classic",
    "players": "1 người",
    "duration": "2-5 phút",
    "mechanic": "Bắn súng cuộn dọc tốc độ cao, tiêu diệt con rết nhiều khúc: mỗi khúc bị bắn trúng biến thành một cây nấm và tách con rết thành 2 đoạn độc lập",
    "badge": "Kinh điển",
    "color": "#CA8A04"
  },
  {
    "id": "qbert-nhay-khoi-lap-phuong",
    "title": "Nhảy Bậc Kim Tự Tháp",
    "tagline": "Nhảy đổi màu từng ô lập phương, chửi bới ngộ nghĩnh né rắn Coily!",
    "category": "Giải đố",
    "section": "classic",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Nhảy chéo 4 hướng trên kim tự tháp khối lập phương Isometric 3D, đổi màu mặt trên của từng khối lập phương sang màu mục tiêu",
    "badge": "Tuổi thơ",
    "color": "#F59E0B"
  },
  {
    "id": "1942-khong-chien-thai-binh-duong",
    "title": "Không Chiến Thái Bình Dương",
    "tagline": "Nhào lộn lượn vòng né đạn pháo, bắn hạ siêu pháo đài bay địch!",
    "category": "Hành động",
    "section": "classic",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Bắn máy bay cuộn dọc cuộn cảnh biển khơi, kỹ năng nhào lộn 360 độ né mưa đạn (Loop-the-loop), ghép đôi máy bay con yểm trợ",
    "badge": "Kinh điển",
    "color": "#0284C7"
  },
  {
    "id": "shinobi-ninja-phi-tieu",
    "title": "Nhẫn Giả Cứu Con Tin",
    "tagline": "Phóng phi tiêu shuriken, tung nhẫn thuật lốc xoáy quét sạch sơn tặc!",
    "category": "Hành động",
    "section": "classic",
    "players": "1 người",
    "duration": "3-7 phút",
    "mechanic": "Hành động ninja cuộn ngang 2 tầng cao/thấp, giải cứu các võ sinh nhí con tin, cận chiến kiếm katana và tung nhẫn thuật Ninjutsu",
    "badge": "Huyền thoại",
    "color": "#1E293B"
  },
  {
    "id": "chip-dale-soc-chuot-cuu-ho",
    "title": "Sóc Chuột Cứu Hộ Đội",
    "tagline": "Nhấc thùng gỗ ném mèo Mèo Béo, phối hợp cõng bạn vượt bẫy điện!",
    "category": "Hành động",
    "section": "classic",
    "players": "1-2 người",
    "duration": "4-8 phút",
    "mechanic": "Nhảy bục co-op 2 người kinh điển: nhấc thùng gỗ/táo/hộp sắt ném địch, chui vào thùng giả vờ tàng hình, nhấc bổng bạn chơi ném qua chướng ngại",
    "badge": "Tuổi thơ",
    "color": "#D97706"
  },
  {
    "id": "tiny-toon-tho-buster-phieu-luu",
    "title": "Thỏ Nhanh Nhẹn Tiny Toon",
    "tagline": "Lướt chân thỏ Buster, biến hình vịt Plucky bơi lội gom cà rốt vàng!",
    "category": "Hành động",
    "section": "classic",
    "players": "1 người",
    "duration": "4-8 phút",
    "mechanic": "Nhảy bục cuộn ngang đa nhân vật, luân chuyển giữa Thỏ Buster, Vịt Plucky Duck, Quỷ Tasmania Dizzy Devil và Mèo Furrball với bộ kỹ năng độc nhất",
    "badge": "Tuổi thơ",
    "color": "#059669"
  },
  {
    "id": "balloon-fight-dap-bong-bay",
    "title": "Đập Bóng Bay Tầng Không",
    "tagline": "Đập cánh giữ nhịp bay lơ lửng, đạp vỡ bóng đối thủ né cá đớp mồi!",
    "category": "Kỹ năng",
    "section": "quick",
    "players": "1-2 người",
    "duration": "2-5 phút",
    "mechanic": "Vật lý bay lượn quán tính đập cánh nhịp nhàng (Flapping flight do Satoru Iwata lập trình), đạp vỡ bóng bay của địch và tránh cá khổng lồ dưới mặt nước",
    "badge": "Kinh điển",
    "color": "#0284C7"
  },
  {
    "id": "ice-climber-dap-bang-leo-nui",
    "title": "Đập Băng Leo Đỉnh Núi",
    "tagline": "Vung búa đục trần băng, nhảy vọt lên cao chộp lấy chân chim đại bàng!",
    "category": "Hành động",
    "section": "classic",
    "players": "1-2 người",
    "duration": "3-6 phút",
    "mechanic": "Hành động nhảy leo 8 tầng núi băng theo phương đứng, đập vỡ trần băng để mở lối nhảy lên tầng trên, nhặt cà tím và đu chân đại bàng",
    "badge": "Tuổi thơ",
    "color": "#0EA5E9"
  },
  {
    "id": "mappy-chuot-canh-sat-nhay-bat",
    "title": "Chuột Cảnh Sát Đệm Lò Xo",
    "tagline": "Nhún bạt lò xo lầu cao, mở sập cửa vi sóng thổi bay lũ mèo trộm đồ!",
    "category": "Hành động",
    "section": "classic",
    "players": "1 người",
    "duration": "3-5 phút",
    "mechanic": "Chuột cảnh sát nhảy bạt lò xo nhún qua các tầng nhà, thu hồi tài sản bị trộm, đóng mở cánh cửa sóng âm Microwave thổi bay bầy mèo",
    "badge": "Kinh điển",
    "color": "#EC4899"
  },
  {
    "id": "twinbee-ban-chuong-bay",
    "title": "Bắn Chuông Mây Biến Màu",
    "tagline": "Bắn nảy chuông trên mây để đổi màu nhặt cánh tay và khiên hộ vệ!",
    "category": "Hành động",
    "section": "classic",
    "players": "1-2 người",
    "duration": "3-6 phút",
    "mechanic": "Bắn phi thuyền hoạt hình dễ thương (Cute 'em up), bắn các đám mây để nhả chuông, tiếp tục bắn nảy chuông trên không trung để đổi màu tăng cấp",
    "badge": "Tuổi thơ",
    "color": "#F59E0B"
  },
  {
    "id": "worms-armageddon-giun-chien-tranh",
    "title": "Giun Đất Bộc Phá (Worms 2D)",
    "tagline": "Căn góc gió thả cừu nổ, bắn bazooka khoét thủng đảo đất rơi biển!",
    "category": "Chiến thuật",
    "section": "hot",
    "players": "1-4 người",
    "duration": "5-10 phút",
    "mechanic": "Chiến thuật pháo binh theo lượt trên địa hình phá hủy hoàn toàn (Destructible Terrain), kho vũ khí hài hước vô tiền khoáng hậu (Holy Hand Grenade, Super Sheep, Banana Bomb)",
    "badge": "Huyền thoại",
    "color": "#84CC16"
  },
  {
    "id": "digger-xe-ui-dao-ham",
    "title": "Xe Ủi Đào Vàng Hầm Ngầm",
    "tagline": "Ủi hầm ăn ngọc lục bảo, thả túi vàng đè bẹp quái Nobbin rượt đuổi!",
    "category": "Giải đố",
    "section": "classic",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Đào hầm địa đạo thu gom ngọc lục bảo, đẩy túi vàng rơi đè bẹp quái vật rượt đuổi, ăn quả anh đào để đảo ngược tình thế đi săn quái",
    "badge": "Kinh điển",
    "color": "#EAB308"
  },
  {
    "id": "bookworm-sau-noi-chu",
    "title": "Mọt Sách Nối Chữ (Bookworm)",
    "tagline": "Nối từng chữ cái thành từ vựng kỳ diệu, dập tắt khối chữ bốc cháy!",
    "category": "Giải đố",
    "section": "chill",
    "players": "1 người",
    "duration": "4-8 phút",
    "mechanic": "Nối các ô chữ cái liền kề trên lưới tổ ong tạo thành từ vựng tiếng Anh có nghĩa, dập tắt các ô chữ lửa đang cháy lan xuống đáy thư viện",
    "badge": "Kinh điển",
    "color": "#16A34A"
  },
  {
    "id": "atomix-ghep-phan-tu-hoa-hoc",
    "title": "Ghép Phân Tử Hóa Học",
    "tagline": "Đẩy các nguyên tử trượt tự do va tường ghép thành công thức phân tử nước!",
    "category": "Giải đố",
    "section": "quick",
    "players": "1 người",
    "duration": "4-8 phút",
    "mechanic": "Giải đố trượt không gian quán tính: đẩy một nguyên tử theo 4 hướng nó sẽ trượt thẳng tắp cho đến khi va vào tường chướng ngại, lắp ráp thành phân tử hóa học chính xác",
    "badge": "Đỉnh cao",
    "color": "#6366F1"
  },
  {
    "id": "icy-tower-thap-bang-nhay-cao",
    "title": "Tháp Băng Nhảy Cực Hạn",
    "tagline": "Nhảy bật tường lộn nhào, chuỗi Combo Sweet vượt tầng băng đang sụp đổ!",
    "category": "Kỹ năng",
    "section": "hot",
    "players": "1 người",
    "duration": "2-5 phút",
    "mechanic": "Nhảy bục cuộn cảnh thẳng đứng vô tận, tích lũy tốc độ chạy đà để bật tường lộn vòng phóng vọt qua 5 tầng bục cùng lúc tạo chuỗi Combo",
    "badge": "Huyền thoại",
    "color": "#06B6D4"
  },
  {
    "id": "hamsterball-lan-cau-hamster",
    "title": "Lăn Cầu Chuột Hamster",
    "tagline": "Cân bằng quả cầu lăn trên mép vực dốc xoắn ốc chạy đua cùng đồng hồ!",
    "category": "Kỹ năng",
    "section": "quick",
    "players": "1 người",
    "duration": "3-6 phút",
    "mechanic": "Lăn quả cầu thủy tinh vật lý Marble 3D chứa chú chuột hamster bên trong, vượt qua các đoạn dốc hiểm trở không có lan can trước khi cạn giờ",
    "badge": "Tuổi thơ",
    "color": "#F97316"
  }
];
