// UI/session checks use Canvas/event doubles; visual/device acceptance remains pending.
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');
const{harness,assertStopped,read}=require('./support/browser-harness.cjs');
const M=require('../scripts/games/abyss-retrieval-model.js');
const KEY='np_abyss_retrieval_v1',el=(h,id)=>h.container.querySelector('#'+id),view=h=>h.mountResult.getModel().view();
const click=(h,id)=>el(h,id).dispatch('click',{detail:1});
function saved(game){return new Map([[KEY,JSON.stringify({version:1,game})]]);}
function launch(storage=new Map()){const h=harness({loadEngines:false,loadApp:false,storage});vm.runInContext(read('scripts/games/abyss-retrieval.js'),h.context,{filename:'scripts/games/abyss-retrieval.js'});h.mount=()=>{h.mountResult=h.context.NP_AbyssRetrieval.mount(h.container,h.context.NP_GameSession.start(),null);return h.mountResult;};h.mount();h.flushTimeouts();return h;}
function haulingSnapshot({score=0}={}){const s=M.create().serialize();s.score=score;s.phase='reel';s.hookAngle=1;s.hookLength=1;s.caughtId='0-0';return s;}
function close(h){h.context.NP_GameSession.stop();h.container.innerHTML='';h.flushTimeouts();assertStopped(h);assert.deepEqual(h.errors,[]);}

test('Vực Ngọc starts with one clear launch action, compact HUD and an accessible canvas',()=>{const h=launch();assert.equal(view(h).stage,0);assert.equal(view(h).phase,'swing');assert.equal(h.frames.size,1);for(const id of ['vrCanvas','vrLaunch','vrPause','vrNew','vrTarget','vrTime'])assert.ok(el(h,id),id);assert.equal(el(h,'vrStatus').getAttribute('aria-live'),'polite');assert.match(read('scripts/games/abyss-retrieval.css'),/min-height:44px/);assert.match(read('scripts/games/abyss-retrieval.css'),/prefers-reduced-motion/);close(h);});

test('tap and keyboard Space launch once; repeated action waits for the tether to return',()=>{const h=launch();click(h,'vrLaunch');assert.equal(view(h).phase,'outbound');click(h,'vrLaunch');assert.equal(view(h).phase,'outbound');close(h);const key=launch();el(key,'vrCanvas').focus();key.container.dispatch('keydown',{target:el(key,'vrCanvas'),code:'Space',key:' '});assert.equal(view(key).phase,'outbound');close(key);});

test('reeling a captured object updates score automatically and clears a completed site',()=>{const h=launch(saved(haulingSnapshot({score:250})));assert.equal(h.mountResult.isPaused(),true);click(h,'vrContinue');for(let i=0;i<4;i++)h.frame();assert.equal(view(h).status,'cleared');assert.equal(view(h).score,390);assert.equal(el(h,'vrOverlay').hidden,false);click(h,'vrContinue');assert.equal(view(h).stage,1);assert.equal(view(h).bankScore,390);assert.equal(view(h).scoreInRoute,0);close(h);});

test('pause/reopen and reversible restart keep an active tether; confirmation starts a clean probe',()=>{const s=M.create().serialize();s.phase='outbound';s.hookAngle=.55;s.angle=.55;s.hookLength=30;const h=launch(saved(s));click(h,'vrContinue');assert.equal(h.frames.size,1);const before=JSON.stringify(view(h));click(h,'vrNew');assert.equal(el(h,'vrConfirm').hidden,false);click(h,'vrConfirmNo');assert.equal(h.frames.size,1);assert.equal(view(h).hookLength,30);click(h,'vrPause');assert.equal(h.frames.size,0);click(h,'vrNew');click(h,'vrConfirmYes');assert.equal(view(h).phase,'swing');assert.equal(view(h).hookLength,0);assert.notEqual(JSON.stringify(view(h)),before);close(h);});

test('corrupt/future storage remains preserved and the old route launches only Vực Ngọc',()=>{const bad=launch(new Map([[KEY,'bad']]));assert.equal(bad.stored.get(KEY+'_recovery'),'bad');close(bad);const raw=JSON.stringify({version:2,game:{version:2}}),future=launch(new Map([[KEY,raw]]));click(future,'vrLaunch');assert.equal(future.stored.get(KEY),raw);assert.match(el(future,'vrStorage').textContent,/mới hơn/);close(future);const h=harness();assert.equal(h.context.openGameById('dao-vang'),true);assert.ok(h.container.querySelector('#vrCanvas'));h.frame();h.context.closeGameModal();assertStopped(h);h.flushTimeouts();assert.deepEqual(h.errors,[]);close(h);assert.match(read('app.js'),/assets\/abyss-retrieval-original\.svg/);assert.doesNotMatch(read('scripts/engines.js'),/Gold Miner|Dynamite|dvCanvas|dvShop/);});
