const test=require('node:test'),assert=require('node:assert/strict');
const M=require('../scripts/games/abyss-retrieval-model.js'),STEP=M.STEP;
const step=(g,n=1)=>{let e=[];for(let i=0;i<n;i++)e.push(...g.advance(STEP));return e;};
function hauling({stage=0,itemId='0-0',score=0,bankScore=0,hookLength=1}={}){const s=M.create({stage,score:bankScore}).serialize(),item=s.items.find(x=>x.id===itemId);if(!item)throw new Error('no item');s.score=score;s.bankScore=bankScore;s.phase='reel';s.hookAngle=item.angle;s.hookLength=hookLength;s.caughtId=item.id;return M.restore(s);}

test('three original deep-sea routes define clear goals, timers and collectible materials',()=>{assert.equal(M.ROUTES.length,3);assert.equal(M.ROUTES[0].items.length,6);assert.ok(M.ROUTES.every(r=>r.target>0&&r.duration>0));assert.deepEqual(Object.keys(M.LOOT),['pearl','glass','stone']);const g=M.create();assert.equal(M.validSave(g.serialize()),true);assert.equal(g.view().items.length,6);});
test('swinging arm stays bounded and ticks are deterministic',()=>{const a=M.create(),b=M.create();step(a,900);step(b,900);assert.deepEqual(a.serialize(),b.serialize());assert.ok(Math.abs(a.view().angle)<=M.ANGLE_LIMIT);assert.ok(a.view().direction===1||a.view().direction===-1);});
test('launch is one-action, captures an aligned nearby item, and awards value on retrieval',()=>{const initial=M.create();assert.equal(initial.act('launch'),true);assert.equal(initial.act('launch'),false);let s=initial.serialize();s.phase='outbound';s.hookAngle=1;s.angle=1;s.direction=-1;s.hookLength=155-M.OUT_STEP;const g=M.restore(s);assert.ok(g);const events=step(g);assert.equal(g.view().phase,'reel');assert.equal(g.view().caughtId,'0-0');assert.ok(events.some(e=>e.kind==='latch'));assert.equal(g.view().score,0);const hauled=step(g,100);assert.equal(g.view().phase,'swing');assert.equal(g.view().score,M.LOOT.pearl.value);assert.ok(hauled.some(e=>e.kind==='haul'&&e.lootKind==='pearl'));assert.equal(g.view().items.some(i=>i.id==='0-0'),false);});
test('off-axis tether misses; line reels back safely before the next launch',()=>{const s=M.create().serialize();s.phase='outbound';s.angle=0;s.hookAngle=0;s.hookLength=M.MAX_LENGTH-M.OUT_STEP;const g=M.restore(s);assert.ok(g);assert.ok(step(g).some(e=>e.kind==='miss'));assert.equal(g.view().phase,'reel');step(g,100);assert.equal(g.view().phase,'swing');assert.equal(g.view().score,0);});
test('mass changes return time while value is applied only when the object reaches the probe',()=>{const heavy=hauling({itemId:'0-2',hookLength:20}),light=hauling({itemId:'0-0',hookLength:20});assert.ok(heavy&&light);step(heavy);step(light);assert.ok(heavy.view().hookLength>light.view().hookLength);assert.equal(heavy.view().score,0);assert.equal(light.view().score,0);});
test('meeting a site quota banks it and unlocks the next route without a shop',()=>{const g=hauling({itemId:'0-1',score:M.ROUTES[0].target-M.LOOT.glass.value});assert.ok(g);step(g);assert.equal(g.view().status,'cleared');const next=g.next();assert.ok(next);assert.equal(next.view().stage,1);assert.equal(next.view().bankScore,M.ROUTES[0].target);assert.equal(next.view().score,M.ROUTES[0].target);assert.equal(next.view().scoreInRoute,0);});
test('last route quota wins, and a missed target retries the current route from banked score',()=>{const lastId='2-1',last=hauling({stage:2,itemId:lastId,score:M.ROUTES[2].target-M.LOOT.glass.value});assert.ok(last);step(last);assert.equal(last.view().status,'won');assert.equal(last.next(),null);const g=M.create({stage:1,score:250}),s=g.serialize();s.timeTicks=M.ROUTES[1].duration-1;const urgent=M.restore(s);assert.ok(urgent);step(urgent);assert.equal(urgent.view().status,'lost');const retry=urgent.retry();assert.equal(retry.view().stage,1);assert.equal(retry.view().score,250);assert.equal(retry.view().bankScore,250);});
test('time limit ends unattended play and terminal states do not continue simulation',()=>{const g=M.create(),s=g.serialize();s.timeTicks=M.ROUTES[0].duration-1;const last=M.restore(s);assert.ok(last);const events=step(last);assert.equal(last.view().status,'lost');assert.ok(events.some(e=>e.kind==='lost'));const stop=last.serialize();last.advance(STEP*20);assert.deepEqual(last.serialize(),stop);assert.equal(last.act('launch'),false);});
test('saved return cable and partial tick resume with exactly the same result',()=>{const a=hauling({itemId:'0-4'});assert.ok(a);step(a,6);const b=M.restore(a.serialize());assert.ok(b);for(let i=0;i<100;i++)assert.deepEqual(a.advance(STEP),b.advance(STEP));assert.deepEqual(a.serialize(),b.serialize());});
test('splitting elapsed time across common refresh rates preserves the simulation',()=>{const a=M.create(),b=M.create();for(let i=0;i<120;i++)a.advance(1000/60);for(let i=0;i<40;i++)b.advance(50);assert.deepEqual(a.serialize(),b.serialize());});
test('corrupt, future and impossible snapshots reject without mutation',()=>{const src=M.create().serialize();for(const edit of [s=>s.version=2,s=>s.stage=99,s=>s.score=-1,s=>s.direction=0,s=>s.caughtId='missing',s=>s.items[0].id='missing',s=>s.phase='mystery',s=>s.status='won']){const bad=structuredClone(src);edit(bad);const before=structuredClone(bad);assert.equal(M.restore(bad),null);assert.deepEqual(bad,before);}});
