const test=require('node:test'),assert=require('node:assert/strict');
const M=require('../scripts/games/beacon-shore-model.js');
const step=(g,n=1)=>{let events=[];for(let i=0;i<n;i++)events.push(...g.advance(M.STEP));return events;};
function fixture({enemyRows=[1],type='mist',x=5.8,towerType='lamp',towerRow=1,towerCol=6}={}){const s=M.create().serialize();s.tick=1;s.waveTick=1;s.spawnIndex=1;s.energy=80;s.enemies=enemyRows.map((row,i)=>({id:i+1,row,x,type,hp:M.ENEMIES[type].hp,maxHp:M.ENEMIES[type].hp,speed:M.ENEMIES[type].speed,slowTicks:0}));s.towers=[{row:towerRow,col:towerCol,type:towerType,cooldown:0}];s.nextId=enemyRows.length+1;return M.restore(s);}
function solveSimple(){const g=M.create(),order=[1,3,0,4,2];let ticks=0;while(g.view().status==='playing'&&ticks<10000){const v=g.view(),row=order.find(r=>!v.towers.some(t=>t.row===r));if(row!==undefined&&v.energy>=M.DEVICES.lamp.cost){g.act('select','lamp');g.act('place',{row,col:5});}step(g);ticks++;}return{game:g,ticks};}

test('original board, devices, finite waves and starting game are compact and valid',()=>{const g=M.create();assert.equal(M.ROWS,5);assert.equal(M.COLS,7);assert.equal(M.WAVES.length,4);assert.equal(g.view().energy,100);assert.equal(g.view().lives,3);assert.equal(g.view().status,'playing');assert.ok(M.validSave(g.serialize()));});
test('device placement spends energy once, blocks occupied tiles and retains selected device',()=>{const g=M.create();assert.equal(g.act('place',{row:1,col:2}),true);assert.equal(g.view().energy,55);assert.equal(g.view().towers.length,1);assert.equal(g.act('place',{row:1,col:2}),false);assert.equal(g.view().towers.length,1);g.act('select','bell');assert.equal(g.act('place',{row:0,col:0}),false);assert.equal(g.view().selectedType,'bell');assert.equal(g.view().energy,55);assert.equal(g.drain().some(e=>e.reason==='energy'),true);});
test('automatic energy generation is fixed-step and capped without manual pickups',()=>{const g=M.create();assert.deepEqual(step(g,M.ENERGY_INTERVAL).filter(e=>e.kind==='energy').map(e=>e.energy),[114]);const s=g.serialize();s.energy=M.MAX_ENERGY;s.energyTick=M.ENERGY_INTERVAL-1;const full=M.restore(s);assert.ok(full);step(full);assert.equal(full.view().energy,M.MAX_ENERGY);});
test('scheduled enemies arrive in their authored lanes at deterministic times',()=>{const g=M.create();assert.equal(g.view().enemies.length,0);step(g);assert.deepEqual(g.view().enemies.map(e=>[e.row,e.type]),[[1,'mist']]);const events=step(g,114);assert.ok(events.some(e=>e.kind==='spawn'&&e.row===3));assert.equal(g.view().enemies.length,2);});
test('lamp targets the nearest enemy in its own lane and projectiles damage then score',()=>{const g=fixture({enemyRows:[1],type:'mist',towerType:'lamp'});assert.ok(g);const events=step(g);assert.equal(g.view().shots.length,1);assert.ok(events.some(e=>e.kind==='fire'));assert.equal(g.view().enemies[0].hp,3);step(g,220);assert.equal(g.view().enemies.some(e=>e.row===1),false);assert.equal(g.view().score,M.ENEMIES.mist.reward);});
test('devices cannot hit a different lane',()=>{const g=fixture({enemyRows:[1],towerRow:0});step(g,120);assert.equal(g.view().enemies.find(e=>e.row===1).hp,M.ENEMIES.mist.hp);assert.equal(g.view().shots.length,0);});
test('wind fan slows a matching lane target without changing its health',()=>{const g=fixture({enemyRows:[1],type:'gust',towerType:'fan'});step(g);const before=g.view().enemies[0].x;assert.equal(g.view().enemies[0].slowTicks,M.DEVICES.fan.slow);step(g);const moved=before-g.view().enemies[0].x;assert.ok(moved<M.ENEMIES.gust.speed);assert.equal(g.view().enemies[0].hp,M.ENEMIES.gust.hp);});
test('bell ring damages multiple nearby targets in one lane only',()=>{const g=fixture({enemyRows:[1,1],type:'mist',towerType:'bell'});step(g);assert.deepEqual(g.view().enemies.map(e=>e.hp),[1,1]);assert.equal(g.view().shots.length,0);});
test('wave stays active while enemies remain after all scheduled arrivals',()=>{const g=M.create();step(g,461);assert.equal(g.view().spawnIndex,M.WAVES[0].length);assert.equal(g.view().enemies.length,M.WAVES[0].length);assert.equal(g.view().waveIndex,0);assert.equal(g.view().status,'playing');});
test('three breaches end the run; terminal state cannot spawn, fire, or change',()=>{const g=M.create();for(let i=0;i<5000&&g.view().status==='playing';i++)step(g);assert.equal(g.view().status,'lost');assert.equal(g.view().lives,0);const stopped=g.serialize();assert.deepEqual(g.advance(M.STEP*20),[]);assert.deepEqual(g.serialize(),stopped);assert.equal(g.act('select','lamp'),false);});
test('five-lane lamp plan can clear all four waves with one life buffer',()=>{const{game,ticks}=solveSimple();assert.ok(ticks<10000);assert.equal(game.view().status,'won');assert.equal(game.view().waveIndex,M.WAVES.length);assert.equal(game.view().lives,2);assert.ok(game.view().score>0);});
test('same simple campaign replays bit-for-bit with matching score and schedule',()=>{const a=solveSimple().game.serialize(),b=solveSimple().game.serialize();assert.deepEqual(a,b);});
test('restore retains moving threats, shots and cooldowns with deterministic continuation',()=>{const a=fixture({enemyRows:[1],type:'mist'});assert.ok(a);step(a,8);const b=M.restore(a.serialize());assert.ok(b);for(let i=0;i<200;i++)assert.deepEqual(a.advance(M.STEP),b.advance(M.STEP));assert.deepEqual(a.serialize(),b.serialize());});
test('split frame intervals produce the same fixed-step state',()=>{const a=M.create(),b=M.create();for(let i=0;i<120;i++)a.advance(1000/60);for(let i=0;i<40;i++)b.advance(50);assert.deepEqual(a.serialize(),b.serialize());});
test('corrupt, impossible and future saves reject without mutating their input',()=>{const original=M.create().serialize();for(const edit of [x=>x.version=2,x=>x.waveIndex=9,x=>x.energy=-1,x=>x.lives=4,x=>x.selectedType='unknown',x=>x.towers=[{row:9,col:0,type:'lamp',cooldown:0}],x=>x.enemies=[{id:1,row:0,x:1,type:'mist',hp:99,maxHp:3,speed:.1,slowTicks:0}],x=>x.shots=[{id:1,row:0,x:1,targetId:999,damage:1}]]){const bad=structuredClone(original);edit(bad);const copy=structuredClone(bad);assert.equal(M.restore(bad),null);assert.deepEqual(bad,copy);}});
