const test=require('node:test'),assert=require('node:assert/strict');
const M=require('../scripts/games/beacon-shore-model.js');
const step=(g,n=1)=>{let events=[];for(let i=0;i<n;i++)events.push(...g.advance(M.STEP));return events;};
function fixture({enemyRows=[1],type='mist',x=5.8,towerType='lamp',towerRow=1,towerCol=6}={}){const s=M.create().serialize();s.tick=1;s.waveTick=1;s.spawnIndex=1;s.energy=80;s.enemies=enemyRows.map((row,i)=>({id:i+1,row,x,type,hp:M.ENEMIES[type].hp,maxHp:M.ENEMIES[type].hp,speed:M.ENEMIES[type].speed,slowTicks:0}));s.towers=[{row:towerRow,col:towerCol,type:towerType,cooldown:0}];s.nextId=enemyRows.length+1;return M.restore(s);}
const laneOrder=[1,3,0,4,2];
function runPlan(plan){const game=M.create(),events=[];let ticks=0,next=0;while(game.view().status==='playing'&&ticks<10000){while(next<plan.length){const p=plan[next],v=game.view();if(v.energy<M.DEVICES[p.type].cost)break;game.act('select',p.type);if(!game.act('place',{row:p.row,col:p.col}))break;next++;}events.push(...step(game));ticks++;}return{game,events,ticks};}
function uniformPlan(type,rows=laneOrder){return rows.map(row=>({row,col:5,type}));}
function deviceCost(plan){return plan.reduce((total,p)=>total+M.DEVICES[p.type].cost,0);}
function solveSimple(){return runPlan(uniformPlan('lamp'));}

test('original board, devices, finite waves and starting game are compact and valid',()=>{const g=M.create();assert.equal(M.ROWS,5);assert.equal(M.COLS,7);assert.equal(M.WAVES.length,4);assert.equal(g.view().energy,100);assert.equal(g.view().lives,3);assert.equal(g.view().status,'playing');assert.ok(M.validSave(g.serialize()));});
test('device placement spends energy once, blocks occupied tiles and retains selected device',()=>{const g=M.create();assert.equal(g.act('place',{row:1,col:2}),true);assert.equal(g.view().energy,55);assert.equal(g.view().towers.length,1);assert.equal(g.act('place',{row:1,col:2}),false);assert.equal(g.view().towers.length,1);g.act('select','bell');assert.equal(g.act('place',{row:0,col:0}),false);assert.equal(g.view().selectedType,'bell');assert.equal(g.view().energy,55);assert.equal(g.drain().some(e=>e.reason==='energy'),true);});
test('automatic energy generation is fixed-step and capped without manual pickups',()=>{const g=M.create();assert.deepEqual(step(g,M.ENERGY_INTERVAL).filter(e=>e.kind==='energy').map(e=>e.energy),[114]);const s=g.serialize();s.energy=M.MAX_ENERGY;s.energyTick=M.ENERGY_INTERVAL-1;const full=M.restore(s);assert.ok(full);step(full);assert.equal(full.view().energy,M.MAX_ENERGY);});
test('scheduled enemies arrive in their authored lanes at deterministic times',()=>{const g=M.create();assert.equal(g.view().enemies.length,0);step(g);assert.deepEqual(g.view().enemies.map(e=>[e.row,e.type]),[[1,'mist']]);const events=step(g,114);assert.ok(events.some(e=>e.kind==='spawn'&&e.row===3));assert.equal(g.view().enemies.length,2);});
test('lamp targets the nearest enemy in its own lane and projectiles damage then score',()=>{const g=fixture({enemyRows:[1],type:'mist',towerType:'lamp'});assert.ok(g);const events=step(g);assert.equal(g.view().shots.length,1);assert.ok(events.some(e=>e.kind==='fire'));assert.equal(g.view().enemies[0].hp,3);step(g,220);assert.equal(g.view().enemies.some(e=>e.row===1),false);assert.equal(g.view().score,M.ENEMIES.mist.reward);});
test('devices cannot hit a different lane',()=>{const g=fixture({enemyRows:[1],towerRow:0});step(g,120);assert.equal(g.view().enemies.find(e=>e.row===1).hp,M.ENEMIES.mist.hp);assert.equal(g.view().shots.length,0);});
test('wind fan slows a matching lane target without changing its health',()=>{const g=fixture({enemyRows:[1],type:'gust',towerType:'fan'});step(g);const before=g.view().enemies[0].x;assert.equal(g.view().enemies[0].slowTicks,M.DEVICES.fan.slow);step(g);const moved=before-g.view().enemies[0].x;assert.ok(moved<M.ENEMIES.gust.speed);assert.equal(g.view().enemies[0].hp,M.ENEMIES.gust.hp);});
test('bell ring damages multiple nearby targets in one lane only',()=>{const g=fixture({enemyRows:[1,1],type:'mist',towerType:'bell'});step(g);assert.deepEqual(g.view().enemies.map(e=>e.hp),[1,1]);assert.equal(g.view().shots.length,0);});
test('wave stays active while enemies remain after all scheduled arrivals',()=>{const g=M.create();step(g,461);assert.equal(g.view().spawnIndex,M.WAVES[0].length);assert.equal(g.view().enemies.length,M.WAVES[0].length);assert.equal(g.view().waveIndex,0);assert.equal(g.view().status,'playing');});
test('three breaches end the run; terminal state cannot spawn, fire, or change',()=>{const g=M.create();for(let i=0;i<5000&&g.view().status==='playing';i++)step(g);assert.equal(g.view().status,'lost');assert.equal(g.view().lives,0);const stopped=g.serialize();assert.deepEqual(g.advance(M.STEP*20),[]);assert.deepEqual(g.serialize(),stopped);assert.equal(g.act('select','lamp'),false);});
test('the fourth wave keeps its saved spawn clock while grouping a seven-gust lane rush',()=>{assert.deepEqual(M.WAVES[3].map(([tick])=>tick),[1,70,140,210,280,350,420,490,560]);assert.deepEqual(M.WAVES[3].slice(0,7).map(([,row,type])=>[row,type]),Array.from({length:7},()=>[2,'gust']));assert.deepEqual(M.WAVES[3].slice(7).map(([,row,type])=>[row,type]),[[1,'cloud'],[4,'mist']]);});
test('a Bell lane rush clears with fewer placements than a route-aware lamp stack',()=>{
 const simple=runPlan(uniformPlan('lamp'));
 const mixedPlan=[{row:1,col:5,type:'lamp'},{row:3,col:5,type:'lamp'},{row:2,col:6,type:'bell'},{row:0,col:5,type:'lamp'},{row:4,col:5,type:'lamp'}];
 const stackedLampPlan=[{row:1,col:5,type:'lamp'},{row:3,col:5,type:'lamp'},{row:2,col:5,type:'lamp'},{row:4,col:5,type:'lamp'},{row:0,col:5,type:'lamp'},{row:2,col:6,type:'lamp'}];
 const mixed=runPlan(mixedPlan),stacked=runPlan(stackedLampPlan);
 assert.equal(simple.game.view().status,'lost');assert.equal(simple.game.view().lives,0);assert.equal(simple.events.filter(e=>e.kind==='pop').length,22);
 for(const result of [mixed,stacked]){assert.equal(result.game.view().status,'won');assert.equal(result.game.view().waveIndex,M.WAVES.length);assert.equal(result.game.view().lives,3);assert.equal(result.game.view().score,408);assert.equal(result.events.filter(e=>e.kind==='pop').length,27);}
 assert.equal(mixed.game.view().towers.length,5);assert.equal(deviceCost(mixedPlan),250);assert.equal(stacked.game.view().towers.length,6);assert.equal(deviceCost(stackedLampPlan),270);assert.equal(mixed.ticks-stacked.ticks,248);
 assert.equal(mixed.events.filter(e=>e.kind==='ring'&&e.row===2).length,10);
});
test('uniform Fan and Bell placements are useful controls but cannot replace lane damage',()=>{for(const type of ['fan','bell']){const result=runPlan(uniformPlan(type));assert.equal(result.game.view().status,'lost');assert.equal(result.game.view().lives,0);}const fan=runPlan(uniformPlan('fan'));assert.ok(fan.events.some(e=>e.kind==='slow'));const bell=runPlan(uniformPlan('bell'));assert.ok(bell.events.some(e=>e.kind==='ring'));});
test('placing the Fan ahead of the Bell changes rush timing without changing the clear',()=>{const before=runPlan([{row:1,col:5,type:'lamp'},{row:3,col:5,type:'lamp'},{row:2,col:5,type:'bell'},{row:0,col:5,type:'lamp'},{row:4,col:5,type:'lamp'},{row:2,col:6,type:'fan'}]);const after=runPlan([{row:1,col:5,type:'lamp'},{row:3,col:5,type:'lamp'},{row:2,col:6,type:'bell'},{row:0,col:5,type:'lamp'},{row:4,col:5,type:'lamp'},{row:2,col:5,type:'fan'}]);for(const result of [before,after]){assert.equal(result.game.view().status,'won');assert.equal(result.game.view().lives,3);assert.equal(result.game.view().score,408);}assert.equal(before.events.filter(e=>e.kind==='slow').length,15);assert.equal(after.events.filter(e=>e.kind==='slow').length,2);});
test('same mixed campaign replays bit-for-bit with matching score and schedule',()=>{const plan=[{row:1,col:5,type:'lamp'},{row:3,col:5,type:'lamp'},{row:2,col:6,type:'bell'},{row:0,col:5,type:'lamp'},{row:4,col:5,type:'lamp'}],a=runPlan(plan),b=runPlan(plan);assert.deepEqual(a.game.serialize(),b.game.serialize());assert.deepEqual(a.events,b.events);});
test('an in-progress version-one save from the old fourth-wave route still resumes',()=>{const old=M.create().serialize();old.tick=3648;old.waveIndex=3;old.waveTick=1;old.spawnIndex=1;old.enemies=[{id:1,row:0,x:7.2,type:'cloud',hp:7,maxHp:7,speed:M.ENEMIES.cloud.speed,slowTicks:0}];old.nextId=2;const resumed=M.restore(old);assert.ok(resumed);const events=step(resumed,69);assert.ok(events.some(e=>e.kind==='spawn'&&e.row===2&&e.type==='gust'));assert.equal(resumed.view().spawnIndex,2);});
test('restore retains moving threats, shots and cooldowns with deterministic continuation',()=>{const a=fixture({enemyRows:[1],type:'mist'});assert.ok(a);step(a,8);const b=M.restore(a.serialize());assert.ok(b);for(let i=0;i<200;i++)assert.deepEqual(a.advance(M.STEP),b.advance(M.STEP));assert.deepEqual(a.serialize(),b.serialize());});
test('split frame intervals produce the same fixed-step state',()=>{const a=M.create(),b=M.create();for(let i=0;i<120;i++)a.advance(1000/60);for(let i=0;i<40;i++)b.advance(50);assert.deepEqual(a.serialize(),b.serialize());});
test('corrupt, impossible and future saves reject without mutating their input',()=>{const original=M.create().serialize();for(const edit of [x=>x.version=2,x=>x.waveIndex=9,x=>x.energy=-1,x=>x.lives=4,x=>x.selectedType='unknown',x=>x.towers=[{row:9,col:0,type:'lamp',cooldown:0}],x=>x.enemies=[{id:1,row:0,x:1,type:'mist',hp:99,maxHp:3,speed:.1,slowTicks:0}],x=>x.shots=[{id:1,row:0,x:1,targetId:999,damage:1}]]){const bad=structuredClone(original);edit(bad);const copy=structuredClone(bad);assert.equal(M.restore(bad),null);assert.deepEqual(bad,copy);}});
