// Candidate mount tests use the repo DOM/Canvas double; browser visuals remain unverified.
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');
const{harness,assertStopped,read}=require('./support/browser-harness.cjs');
const el=(h,id)=>h.container.querySelector('#'+id);
function open(){const h=harness({loadEngines:false,loadApp:false});vm.runInContext(read('scripts/games/chem-hoa-qua-model.js'),h.context,{filename:'chem-hoa-qua-model.js'});vm.runInContext(read('scripts/games/chem-hoa-qua.js'),h.context,{filename:'chem-hoa-qua.js'});h.mountResult=h.context.NP_FruitSweep.mount(h.container,h.context.NP_GameSession.start());el(h,'fsCanvas').height=420;return h;}
function close(h){h.context.NP_GameSession.stop();h.container.innerHTML='';assertStopped(h);assert.deepEqual(h.errors,[]);}
test('catalog-style mount exposes original title, accessible canvas and starts from keyboard',()=>{const h=open();assert.match(h.container.innerHTML,/Vườn Bật Nảy/);assert.ok(el(h,'fsCanvas').getAttribute('aria-label'));let prevented=false;el(h,'fsCanvas').dispatch('keydown',{key:'ArrowRight',code:'ArrowRight',target:el(h,'fsCanvas'),preventDefault(){prevented=true;}});assert.equal(prevented,true);assert.equal(h.mountResult.getModel().view().status,'playing');assert.equal(h.frames.size,1);close(h);});
test('pointer swipe slices a fruit and pause, resume, restart and close release resources',()=>{const h=open(),canvas=el(h,'fsCanvas');canvas.dispatch('pointerdown',{clientX:320,clientY:200,pointerId:1});for(let i=0;i<30;i++)h.frame();const fruit=h.mountResult.getModel().view().objects.find(o=>o.kind==='fruit');assert.ok(fruit,JSON.stringify(h.mountResult.getModel().view()));canvas.dispatch('pointerdown',{clientX:fruit.x,clientY:fruit.y,pointerId:2});h.window.dispatch('pointermove',{buttons:1,pointerId:2,clientX:fruit.x+1,clientY:fruit.y+1});assert.ok(h.mountResult.getModel().view().score>=10);el(h,'fsPause').click();assert.equal(h.mountResult.isPaused(),true);assert.equal(h.frames.size,0);el(h,'fsResume').click();assert.equal(h.mountResult.isPaused(),false);assert.equal(h.frames.size,1);el(h,'fsRestart').click();assert.equal(h.mountResult.getModel().view().status,'ready');assert.equal(h.frames.size,0);close(h);});

test('exact catalog route opens the original candidate with its cover and compact HUD',()=>{const h=harness();assert.equal(h.context.openGameById('chem-hoa-qua'),true);assert.ok(el(h,'fsCanvas'));assert.ok(el(h,'fsTime'));assert.ok(el(h,'fsMisses'));assert.match(read('app.js'),/'chem-hoa-qua': 'assets\/covers\/vuon-bat-nay\.svg'/);assert.doesNotMatch(h.container.innerHTML,/Fruit Ninja|Halfbrick|dojo/i);h.context.closeGameModal();assertStopped(h);assert.deepEqual(h.errors,[]);});
