const test = require('node:test');
const assert = require('node:assert/strict');
const vm = require('node:vm');
const { harness, read } = require('./support/browser-harness.cjs');

function setup(options = {}) {
  const h = harness({ loadEngines: false, loadApp: false, ...options });
  vm.runInContext(read('scripts/games/day-thung-sokoban-model.js'), h.context, { filename: 'day-thung-sokoban-model.js' });
  vm.runInContext(read('scripts/games/day-thung-sokoban.js'), h.context, { filename: 'day-thung-sokoban.js' });
  const ui = h.context.NP_DayThungSokoban.mount(h.container);
  return { h, ui };
}

const element = (h, selector) => h.container.querySelector(selector);
const cell = (h, x, y) => h.container.querySelectorAll('.np-soko-cell').find(item => Number(item.dataset.x) === x && Number(item.dataset.y) === y);
const key = (target, value) => target.dispatch('keydown', { key: value, preventDefault() { this.prevented = true; } });

function close(h, ui) {
  ui.destroy();
  h.context.NP_GameSession.stop();
  assert.equal(h.container.children.length, 0);
  assert.equal(h.window.listenerCount(), 0);
  assert.deepEqual(h.errors, []);
}

test('mounts instantly with an accessible board, live status, and compact controls', () => {
  const { h, ui } = setup();
  assert.match(h.container.innerHTML, /Đẩy Thùng/);
  assert.equal(element(h, '.np-soko-board').getAttribute('role'), 'grid');
  assert.equal(element(h, '.np-soko-board').getAttribute('tabindex'), '0');
  assert.equal(element(h, '.np-soko-status').getAttribute('aria-live'), 'polite');
  assert.equal(h.container.querySelectorAll('.np-soko-cell').length, 40);
  assert.match(element(h, '.np-soko-status').textContent, /Đẩy từng thùng/);
  assert.equal(element(h, '.np-soko-next').hidden, true);
  close(h, ui);
});

test('arrow keys and WASD move exactly one tile; Z undoes and R restarts', () => {
  const { h, ui } = setup();
  const board = element(h, '.np-soko-board');
  key(board, 'ArrowRight');
  key(board, 'w');
  assert.deepEqual(JSON.parse(JSON.stringify(ui.model.view().player)), { x: 5, y: 2 });
  assert.equal(ui.model.view().moves, 2);
  key(board, 'z');
  assert.equal(ui.model.view().moves, 1);
  key(board, 'R');
  assert.equal(ui.model.view().moves, 0);
  assert.deepEqual(JSON.parse(JSON.stringify(ui.model.view().player)), { x: 4, y: 3 });
  close(h, ui);
});

test('direction buttons move the player and report a blocked step', () => {
  const { h, ui } = setup();
  element(h, '.np-soko-arrow.is-right').click();
  assert.equal(ui.model.view().player.x, 5);
  element(h, '.np-soko-arrow.is-down').click();
  assert.match(element(h, '.np-soko-status').textContent, /Đường bị chặn/);
  close(h, ui);
});

test('tapping a board cell chooses a step toward it', () => {
  const { h, ui } = setup();
  element(h, '.np-soko-board').dispatch('click', { target: cell(h, 5, 3) });
  assert.deepEqual(JSON.parse(JSON.stringify(ui.model.view().player)), { x: 5, y: 3 });
  assert.equal(ui.model.view().moves, 1);
  close(h, ui);
});

test('swipe input uses the dominant direction and ignores short pointer motion', () => {
  const { h, ui } = setup();
  const board = element(h, '.np-soko-board');
  board.dispatch('pointerdown', { pointerId: 7, isPrimary: true, button: 0, clientX: 40, clientY: 50 });
  h.window.dispatch('pointerup', { pointerId: 7, clientX: 44, clientY: 52 });
  assert.equal(ui.model.view().moves, 0);
  board.dispatch('pointerdown', { pointerId: 8, isPrimary: true, button: 0, clientX: 40, clientY: 50 });
  h.window.dispatch('pointerup', { pointerId: 8, clientX: 12, clientY: 50 });
  assert.equal(ui.model.view().player.x, 3);
  assert.equal(ui.model.view().moves, 1);
  board.dispatch('click', { target: cell(h, 2, 3) });
  assert.equal(ui.model.view().player.x, 3, 'the click generated by a swipe must not make a second move');
  close(h, ui);
});

test('undo, restart, and level progression update visible state and win announcement', () => {
  const { h, ui } = setup();
  for (const direction of ['right', 'right', 'up', 'left', 'left', 'left']) element(h, `.np-soko-arrow.is-${direction}`).click();
  assert.equal(ui.model.view().status, 'won');
  assert.equal(element(h, '.np-soko-next').hidden, false);
  assert.match(element(h, '.np-soko-status').textContent, /Màn 1 hoàn thành/);
  element(h, '.np-soko-next').click();
  assert.equal(ui.model.view().levelIndex, 1);
  assert.equal(ui.model.view().moves, 0);
  element(h, '.np-soko-reset').click();
  assert.equal(ui.model.view().levelIndex, 1);
  assert.equal(ui.model.view().moves, 0);
  element(h, '.np-soko-undo').click();
  assert.equal(ui.model.view().moves, 0);
  close(h, ui);
});

test('active puzzle, undo history, unlock, and best moves survive closing and reopening', () => {
  const { h, ui } = setup();
  for (const direction of ['right','right','up','left']) element(h, `.np-soko-arrow.is-${direction}`).click();
  const saved = JSON.parse(h.stored.get('np_day_thung_sokoban_v2'));
  assert.equal(saved.version, 2);
  assert.equal(saved.state.moves, 4);
  assert.equal(saved.history.length, 4);
  close(h, ui);
  const resumed = setup({ storage: h.stored });
  assert.equal(resumed.ui.model.view().moves, 4);
  key(element(resumed.h, '.np-soko-board'), 'z');
  assert.equal(resumed.ui.model.view().moves, 3);
  for (const direction of ['left','left','left']) element(resumed.h, `.np-soko-arrow.is-${direction}`).click();
  assert.equal(resumed.ui.model.view().status, 'won');
  assert.equal(resumed.ui.model.view().unlockedLevel, 1);
  assert.equal(resumed.ui.model.view().bestMoves[0], 6);
  element(resumed.h, '.np-soko-next').click();
  close(resumed.h, resumed.ui);
  const reopened = setup({ storage: resumed.h.stored });
  assert.equal(reopened.ui.model.view().levelIndex, 1);
  assert.equal(reopened.ui.model.view().unlockedLevel, 1);
  assert.equal(reopened.ui.model.view().moves, 0);
  close(reopened.h, reopened.ui);
});

test('future, corrupt, and denied saves remain untouched while a new puzzle stays playable', () => {
  const key = 'np_day_thung_sokoban_v2';
  for (const raw of ['{broken', JSON.stringify({ version: 99 })]) {
    const { h, ui } = setup({ storage: new Map([[key, raw]]) });
    element(h, '.np-soko-arrow.is-right').click();
    assert.equal(h.stored.get(key), raw);
    assert.match(element(h, '.np-soko-status').textContent, /Bản lưu không đọc được|Tiến độ chưa lưu được/);
    close(h, ui);
  }
  const denied = setup();
  denied.h.context.localStorage.setItem = () => { throw Error('quota'); };
  element(denied.h, '.np-soko-arrow.is-right').click();
  assert.equal(denied.ui.model.view().player.x, 5);
  assert.match(element(denied.h, '.np-soko-status').textContent, /Tiến độ chưa lưu được/);
  close(denied.h, denied.ui);
});

test('session cleanup is idempotent and removes keyboard and pointer listeners', () => {
  const { h, ui } = setup();
  assert.equal(h.window.listenerCount(), 2);
  ui.destroy();
  h.context.NP_GameSession.stop();
  ui.destroy();
  assert.equal(h.window.listenerCount(), 0);
  assert.equal(h.container.children.length, 0);
});

test('repeated mounts do not accumulate window listeners', () => {
  for (let i = 0; i < 8; i += 1) {
    const { h, ui } = setup();
    assert.equal(h.window.listenerCount(), 2);
    close(h, ui);
  }
});

test('responsive styling preserves touch targets and limits help text', () => {
  const css = read('scripts/games/day-thung-sokoban.css');
  const view = read('scripts/games/day-thung-sokoban.js');
  assert.match(css, /min-width:\s*44px/);
  assert.match(css, /min-height:\s*44px/);
  assert.match(css, /prefers-reduced-motion/);
  assert.ok(view.match(/<p class="np-soko-help">([^<]+)/)[1].length < 100);
  assert.doesNotMatch(view, /Kenney|Sokoban Online|University of Alberta/);
});

test('exact catalog route opens the original room and project cover',()=>{const h=harness();assert.equal(h.context.openGameById('day-thung-sokoban'),true);assert.ok(h.container.querySelector('.np-soko-board'));assert.match(read('app.js'),/'day-thung-sokoban': 'assets\/day-thung-sokoban-original\.svg'/);assert.doesNotMatch(h.container.innerHTML,/Sokoban Online|commercial/i);h.context.closeGameModal();assert.equal(h.frames.size,0);assert.equal(h.window.listenerCount(),0);assert.deepEqual(h.errors,[]);});
