// DOM/event and Canvas doubles cover launch, input, replay, pause and lifecycle; they are not browser QA.
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');
const{harness,assertStopped,read}=require('./support/browser-harness.cjs');
const M=require('../scripts/games/flappy-bird-model.js');
const el=(h,id)=>h.container.querySelector('#'+id);
function launch(){const h=harness({loadEngines:false,loadApp:false});h.context.NP_FlappyBirdModel=M;vm.runInContext(read('scripts/games/flappy-bird.js'),h.context,{filename:'scripts/games/flappy-bird.js'});h.mount=()=>h.mountResult=h.context.NP_FlappyBird.mount(h.container,h.context.NP_GameSession.start());h.mount();return h;}
function close(h){h.context.NP_GameSession.stop();h.container.innerHTML='';assertStopped(h);assert.deepEqual(h.errors,[]);}

test('one-screen view exposes score, tries, next gap and touch/Space instructions',()=>{const h=launch();for(const id of ['fgCanvas','fgScore','fgLives','fgNext','fgPause','fgOverlay','fgStart'])assert.ok(el(h,id),id);assert.equal(h.mountResult.getModel().view().status,'ready');assert.equal(el(h,'fgCanvas').focused,true);assert.match(el(h,'fgCanvas').getAttribute('aria-label'),/Space/);assert.match(read('scripts/games/flappy-bird.css'),/min-height:44px/);assert.match(read('scripts/games/flappy-bird.css'),/\.fg-help summary\{[^}]*width:44px;height:44px/);assert.match(read('scripts/games/flappy-bird.css'),/pointer-events:none/);assert.match(read('scripts/games/flappy-bird.css'),/prefers-reduced-motion/);close(h);});

test('pointer and Space inputs flap, while repeated keydown is ignored',()=>{const h=launch(),canvas=el(h,'fgCanvas');canvas.dispatch('pointerdown',{pointerId:1,preventDefault(){}});assert.equal(h.mountResult.getModel().view().status,'playing');const first=h.mountResult.getModel().view().player.vy;h.container.dispatch('keydown',{key:' ',repeat:true,target:canvas});assert.equal(h.mountResult.getModel().view().player.vy,first);h.container.dispatch('keydown',{key:' ',repeat:false,target:canvas});assert.equal(h.mountResult.getModel().view().player.vy,M.FLAP);close(h);});

test('pause, continue, final replay, and close release scheduled work and listeners',()=>{const h=launch();el(h,'fgStart').click();assert.equal(h.mountResult.getModel().view().status,'playing');h.frame();h.window.dispatch('blur');assert.equal(h.mountResult.isPaused(),true);assert.equal(h.frames.size,0);el(h,'fgStart').click();assert.equal(h.mountResult.isPaused(),false);assert.equal(h.frames.size,1);el(h,'fgPause').click();assert.equal(h.mountResult.isPaused(),true);assert.equal(h.frames.size,0);el(h,'fgStart').click();assert.equal(h.mountResult.isPaused(),false);assert.equal(h.frames.size,1);
 for(let i=0;i<240&&h.mountResult.getModel().view().status!=='over';i++)h.frame();assert.equal(h.mountResult.getModel().view().status,'over');assert.equal(h.mountResult.getModel().view().lives,0);assert.equal(el(h,'fgOverlay').hidden,false);el(h,'fgStart').click();assert.equal(h.mountResult.getModel().view().status,'playing');assert.equal(h.mountResult.getModel().view().lives,3);assert.equal(h.frames.size,1);close(h);});

test('closing during active flight cancels RAF and removes handlers',()=>{const h=launch();el(h,'fgStart').click();assert.equal(h.frames.size,1);h.context.NP_GameSession.stop();h.container.innerHTML='';assertStopped(h);assert.deepEqual(h.errors,[]);});
