const test=require('node:test'),assert=require('node:assert/strict');
const M=require('../scripts/games/mosaic-match-model.js');
function legalMoves(board){const out=[];for(let r=0;r<M.ROWS;r++)for(let c=0;c<M.COLS;c++)for(const[dr,dc]of [[0,1],[1,0]]){const nr=r+dr,nc=c+dc;if(nr>=M.ROWS||nc>=M.COLS)continue;const b=structuredClone(board);[b[r][c],b[nr][nc]]=[b[nr][nc],b[r][c]];if(M.findMatches(b).length)out.push({r,c,nr,nc});}return out;}
function play(g,m){assert.equal(g.tap(m.r,m.c),true);assert.equal(g.tap(m.nr,m.nc),true);return g.drain();}

test('all stages deal a deterministic match-free board with a legal move',()=>{for(let stage=0;stage<M.STAGES.length;stage++)for(let seed=1;seed<=40;seed++){const a=M.create({stage,seed}),b=M.create({stage,seed}),v=a.view();assert.deepEqual(a.serialize(),b.serialize());assert.equal(v.board.length,M.ROWS);assert.equal(v.board[0].length,M.COLS);assert.equal(M.findMatches(v.board).length,0);assert.ok(M.boardHasLegalMove(v.board));for(const row of v.board)for(const color of row)assert.ok(color<M.STAGES[stage].colors);}});
test('three distinct stained-glass windows use simple original goals and no setup phase',()=>{assert.deepEqual(M.STAGES.map(s=>s.target),[45,60,75]);assert.equal(M.STAGES.length,3);assert.equal(M.MAX_MOVES,30);for(const s of M.STAGES)assert.ok(s.name.startsWith('Cửa'));const v=M.create().view();assert.equal(v.status,'playing');assert.equal(v.moves,0);assert.equal(v.selected,null);});
test('adjacent same-window symbols clear, refill, award score and consume one valid move',()=>{const g=M.create({seed:71}),before=g.view().board,move=legalMoves(before)[0];assert.ok(move);const events=play(g,move),v=g.view();assert.ok(events.some(e=>e.kind==='match'&&e.count>=3));assert.equal(v.moves,1);assert.ok(v.cleared>=3);assert.ok(v.score>=30);assert.equal(M.findMatches(v.board).length,0);assert.ok(M.boardHasLegalMove(v.board));});
test('a non-matching swap rolls back and does not spend a move',()=>{const g=M.create({seed:5}),s=g.serialize(),move=(()=>{for(let r=0;r<M.ROWS;r++)for(let c=0;c<M.COLS;c++)for(const[dr,dc]of [[0,1],[1,0]]){const nr=r+dr,nc=c+dc;if(nr<M.ROWS&&nc<M.COLS){const b=structuredClone(s.board);[b[r][c],b[nr][nc]]=[b[nr][nc],b[r][c]];if(!M.findMatches(b).length)return{r,c,nr,nc};}}})();assert.ok(move);const events=play(g,move);assert.ok(events.some(e=>e.kind==='invalid'));assert.deepEqual(g.view().board,s.board);assert.equal(g.view().moves,0);});
test('same-cell deselect and a distant tap simply replace the selected cell',()=>{const g=M.create(),first={r:0,c:0};g.tap(first.r,first.c);g.tap(first.r,first.c);assert.equal(g.view().selected,null);g.tap(1,1);g.tap(5,5);assert.deepEqual(g.view().selected,{r:5,c:5});assert.equal(g.deselect(),true);assert.equal(g.view().selected,null);});
test('a four-glass line clears every matched tile and scores by actual count',()=>{const g=M.create().serialize();g.board=Array.from({length:M.ROWS},(_,r)=>Array.from({length:M.COLS},(_,c)=>(r*2+c)%4));g.board[0]=[0,1,0,0,1,2];g.board[1][1]=0;const board=M.restore(g);assert.ok(board);const before=board.view().board;const events=play(board,{r:0,c:1,nr:1,nc:1});const match=events.find(e=>e.kind==='match');assert.ok(match);assert.ok(match.count>=4);assert.ok(board.view().cleared>=4);assert.notDeepEqual(board.view().board,before);});
test('cascade refills resolve deterministically and leave no free matches',()=>{let found=null;for(let seed=1;seed<2500&&!found;seed++){const g=M.create({seed});for(const move of legalMoves(g.view().board)){const h=M.restore(g.serialize());const events=play(h,move),match=events.find(e=>e.kind==='match');if(match?.chain>1){found={seed,move,events,state:h.serialize()};break;}}}assert.ok(found,'find a deterministic cascade seed');const replay=M.create({seed:found.seed});assert.deepEqual(play(replay,found.move),found.events);assert.deepEqual(replay.serialize(),found.state);assert.equal(M.findMatches(replay.view().board).length,0);});
test('stage clear banks score, preserves it through retry, and reaches a final win',()=>{let s=M.create({seed:123}).serialize();s.cleared=M.STAGES[0].target-3;const a=M.restore(s);assert.ok(a);let m=legalMoves(a.view().board)[0];play(a,m);assert.equal(a.view().status,'cleared');const b=a.next();assert.equal(b.view().stage,1);assert.equal(b.view().bankScore,b.view().score);let lost=b.serialize();lost.moves=M.MAX_MOVES;lost.status='lost';const retry=M.restore(lost);assert.ok(retry);assert.equal(retry.retry().view().stage,1);assert.equal(retry.retry().view().score,retry.view().bankScore);let final=M.create({stage:2,seed:888}).serialize();final.cleared=M.STAGES[2].target-3;const last=M.restore(final);assert.ok(last);play(last,legalMoves(last.view().board)[0]);assert.equal(last.view().status,'won');assert.equal(last.next(),null);});
test('save restore keeps selection and produces identical next cascade',()=>{const a=M.create({seed:188}),move=legalMoves(a.view().board)[0];a.tap(move.r,move.c);const restored=M.restore(a.serialize());assert.ok(restored);assert.deepEqual(restored.view().selected,a.view().selected);const b=M.restore(a.serialize());a.tap(move.nr,move.nc);b.tap(move.nr,move.nc);assert.deepEqual(a.serialize(),b.serialize());});
test('corrupt, future, matched, dead-board and impossible snapshots reject without mutation',()=>{const src=M.create({seed:31}).serialize();const dead=[[2,1,0,3,3,1],[3,0,1,2,0,1],[0,2,3,0,2,3],[1,2,0,1,3,3],[1,1,3,2,0,1],[3,0,0,3,1,1]];assert.equal(M.findMatches(dead).length,0);assert.equal(M.boardHasLegalMove(dead),false);for(const edit of [s=>s.version=2,s=>s.stage=9,s=>s.seed=0,s=>s.moves=M.MAX_MOVES+1,s=>s.board[0][0]=M.STAGES[0].colors,s=>{s.board[0][0]=1;s.board[0][1]=1;s.board[0][2]=1;},s=>s.selected={r:99,c:0},s=>s.board=dead]){const bad=structuredClone(src);edit(bad);const before=structuredClone(bad);assert.equal(M.restore(bad),null);assert.deepEqual(bad,before);}});
