const test=require('node:test'),assert=require('node:assert/strict');
const M=require('../scripts/games/scrap-rover-model.js');
const fire=(g)=>{assert.equal(g.act('fire'),true);return g.drain();};

test('three authored arena grids keep spawns reachable and start instantly',()=>{for(let stage=0;stage<M.STAGES.length;stage++){const g=M.create({stage}),v=g.view();assert.equal(v.status,'playing');assert.equal(v.stageInfo.enemyCount,v.enemies.length);assert.equal(v.enemies.length,[4,5,6][stage]);assert.equal(M.validSave(g.serialize()),true);assert.notEqual(v.map[v.player.r][v.player.c],'#');for(const e of v.enemies)assert.notEqual(v.map[e.r][e.c],'#');}});
test('movement changes facing and advances one tile per action',()=>{const g=M.create();const p=g.view().player;g.act('move',1);assert.deepEqual(g.view().player,{r:p.r,c:p.c+1,dir:1});assert.equal(g.view().moves,1);});
test('a straight shot hits the first visible drone but not through stone',()=>{const g=M.create();let s=g.serialize();s.player.dir=3;const h=M.restore(s);assert.ok(h);const events=fire(h);assert.ok(events.some(e=>e.kind==='kill'));assert.equal(h.view().kills,1);assert.equal(h.view().score,100);let blocked=M.create().serialize();blocked.player.dir=0;const b=M.restore(blocked);const miss=fire(b);assert.ok(miss.some(e=>e.kind==='miss'));assert.equal(b.view().kills,0);});
test('patrol drones seek the signal core and a breach consumes one shield',()=>{let s=M.create().serialize();s.player={r:2,c:1,dir:0};s.enemies[0].r=3;s.enemies[0].c=4;const g=M.restore(s);assert.ok(g);const events=fire(g);assert.ok(events.some(e=>e.kind==='breach'&&e.core===2));assert.equal(g.view().core,2);assert.equal(g.view().breaches,1);assert.equal(g.view().enemies.length,3);});
test('the core breach limit loses even if the final patrol reaches it on the same turn',()=>{let s=M.create().serialize();s.player={r:2,c:1,dir:0};s.kills=1;s.breaches=2;s.core=1;s.enemies=[{id:3,r:3,c:4,spawn:{r:7,c:3}}];const g=M.restore(s);assert.ok(g);const events=fire(g);assert.ok(events.some(e=>e.kind==='lost'));assert.equal(g.view().status,'lost');assert.equal(g.view().core,0);assert.equal(g.view().enemies.length,0);});
test('a blocked move still turns the rover and lets patrols advance',()=>{let s=M.create().serialize();s.player={r:7,c:4,dir:0};const g=M.restore(s);assert.ok(g);const before=g.view().player;const events=(g.act('move',0),g.drain());assert.equal(g.view().player.r,before.r);assert.equal(g.view().player.c,before.c);assert.ok(events.some(e=>e.kind==='move'));assert.ok(g.view().moves===1);});
test('destroying the last drone clears a zone, carries score and allows a final win',()=>{let s=M.create({stage:0}).serialize();s.player={r:7,c:1,dir:0};s.kills=3;s.enemies=[{id:3,r:5,c:1,spawn:{r:7,c:3}}];const g=M.restore(s);assert.ok(g);const events=fire(g);assert.ok(events.some(e=>e.kind==='cleared'));assert.equal(g.view().status,'cleared');const next=g.next();assert.equal(next.view().stage,1);assert.equal(next.view().bankScore,g.view().score);let final=M.create({stage:2}).serialize();final.player={r:7,c:3,dir:0};final.kills=M.STAGES[2].spawns.length-1;final.enemies=[{id:5,r:5,c:3,spawn:{r:5,c:7}}];const last=M.restore(final);assert.ok(last);assert.ok(fire(last).some(e=>e.kind==='won'));assert.equal(last.view().status,'won');});
test('loss retry restores only the banked score and current stage',()=>{let s=M.create({stage:1,score:250,bankScore:250}).serialize();s.score=550;s.core=0;s.breaches=3;s.kills=2;s.enemies=[];s.moves=1;s.status='lost';const lost=M.restore(s);assert.ok(lost);const retry=lost.retry();assert.equal(retry.view().stage,1);assert.equal(retry.view().score,250);assert.equal(retry.view().core,M.CORE_INTEGRITY);});
test('save and restore produce the same next tactical turn',()=>{const a=M.create({seed:88}),p=a.view().player;const action=a.act('move',1);assert.equal(action,true);const b=M.restore(a.serialize());assert.ok(b);assert.deepEqual(a.view(),b.view());a.act('fire');b.act('fire');assert.deepEqual(a.serialize(),b.serialize());});
test('corrupt, future, impossible and terminal snapshots reject without mutation',()=>{const src=M.create().serialize();for(const edit of [s=>s.version=2,s=>s.stage=99,s=>s.player.r=99,s=>s.player.dir=5,s=>s.core=M.CORE_INTEGRITY+1,s=>s.enemies[0].r=0,s=>s.enemies.push(s.enemies[0]),s=>s.moves=M.MAX_TURNS+1,s=>s.status='won']){const bad=structuredClone(src);edit(bad);const before=structuredClone(bad);assert.equal(M.restore(bad),null);assert.deepEqual(bad,before);}});
