const test=require('node:test'),assert=require('node:assert/strict');
const M=require('../scripts/games/season-shed-model.js');
function card(suit,value,copy=0){return M.CARDS.find(c=>c.suit===suit&&c.value===value&&c.id.endsWith(':'+copy))?.id;}
function fixture({hand0=[],hand1=[],discard,activeSuit=null,phase='player',turn=0,drawTop=[],lastDrawId=null}={}){const s=M.create({seed:71}).serialize(),all=M.CARDS.map(c=>c.id);discard||=[card('spring',1)];const used=new Set([...hand0,...hand1,...discard,...drawTop]);if(used.size!==hand0.length+hand1.length+discard.length+drawTop.length)throw new Error('fixture repeats a card');s.hands=[ [...hand0],[...hand1] ];s.discard=[...discard];s.drawPile=[...all.filter(x=>!used.has(x)),...drawTop];s.activeSuit=activeSuit||M.CARDS.find(c=>c.id===discard.at(-1)).suit;s.phase=phase;s.turn=turn;s.lastDrawId=lastDrawId;s.status='playing';s.winner=null;return M.restore(s);}

test('original deck has four accessible season suits, two 1–8 copies, gusts and wild dewdrops',()=>{assert.equal(M.CARD_TOTAL,76);assert.equal(M.SUIT_KEYS.length,4);assert.equal(M.CARDS.filter(c=>c.kind==='number').length,64);assert.equal(M.CARDS.filter(c=>c.kind==='gust').length,8);assert.equal(M.CARDS.filter(c=>c.kind==='dew').length,4);assert.equal(new Set(M.CARDS.map(c=>c.id)).size,76);});
test('fresh play deals six cards, opens on a number and conserves every card',()=>{const g=M.create(),s=g.serialize(),v=g.view();assert.deepEqual(s.hands.map(h=>h.length),[6,6]);assert.equal(M.CARDS.find(c=>c.id===s.discard.at(-1)).kind,'number');assert.equal(s.drawPile.length+s.discard.length+s.hands[0].length+s.hands[1].length,M.CARD_TOTAL);assert.equal(v.opponentCount,6);assert.equal(v.hand.length,6);assert.ok(M.validSave(s));});
test('seeded shuffle produces repeatable but distinct starting hands',()=>{const a=M.create({seed:333}).serialize(),b=M.create({seed:333}).serialize(),c=M.create({seed:334}).serialize();assert.deepEqual(a,b);assert.notDeepEqual(a.hands,c.hands);});
test('matching a suit or rank is legal and changes the visible top card',()=>{const suit=fixture({hand0:[card('spring',4),card('winter',2)],hand1:[card('winter',8)],discard:[card('spring',1)]});assert.ok(suit);assert.equal(suit.act('play',card('spring',4)),true);assert.equal(suit.view().topCard.value,4);assert.equal(suit.view().phase,'ai');const rank=fixture({hand0:[card('winter',4),card('summer',2)],hand1:[card('summer',8)],discard:[card('spring',4)]});assert.equal(rank.act('play',card('winter',4)),true);assert.equal(rank.view().activeSuit,'winter');});
test('matching a gust action symbol is legal across suits',()=>{const g=fixture({hand0:[card('winter','gust'),card('summer',2)],hand1:[card('summer',4)],discard:[card('spring','gust')]});assert.ok(g);assert.equal(g.act('play',card('winter','gust')),true);assert.equal(g.view().phase,'player');assert.equal(g.view().opponentCount,3);});
test('wild dewdrop needs a chosen season and sets that season for the next turn',()=>{const g=fixture({hand0:['dew:0',card('winter',2)],hand1:[card('winter',5)],discard:[card('spring',2)]});assert.ok(g);assert.equal(g.act('play','dew:0'),false);assert.equal(g.view().hand.length,2);assert.equal(g.act('play',{cardId:'dew:0',suit:'autumn'}),true);assert.equal(g.view().activeSuit,'autumn');assert.equal(g.view().phase,'ai');});
test('illegal cards and a non-drawn card after drawing never mutate the hand',()=>{const g=fixture({hand0:[card('summer',7),card('winter',1)],hand1:[card('spring',4)],discard:[card('spring',3)]});const before=g.serialize();assert.equal(g.act('play',card('summer',7)),false);assert.deepEqual(g.serialize(),before);});
test('a gust card gives two cards and skips the opponent without stacking',()=>{const g=fixture({hand0:[card('spring','gust'),card('winter',3)],hand1:[card('summer',6)],discard:[card('spring',2)]});assert.ok(g);const before=g.view().drawCount;assert.equal(g.act('play',card('spring','gust')),true);assert.equal(g.view().phase,'player');assert.equal(g.view().opponentCount,3);assert.equal(g.view().drawCount,before-2);});
test('drawing a playable card allows only that card, and pass ends the turn',()=>{const drawn=card('summer',3),g=fixture({hand0:[card('winter',7)],hand1:[card('autumn',6)],discard:[card('spring',3)],drawTop:[drawn]});assert.ok(g);assert.equal(g.act('draw'),true);assert.equal(g.view().phase,'player-drawn');assert.deepEqual([...g.view().playableIds],[drawn]);assert.equal(g.act('play',card('winter',7)),false);assert.equal(g.act('pass'),true);assert.equal(g.view().phase,'ai');});
test('an unplayable draw passes automatically and is kept in the hand',()=>{const drawn=card('winter',8),g=fixture({hand0:[card('summer',1)],hand1:[card('autumn',2)],discard:[card('spring',3)],drawTop:[drawn]});assert.equal(g.act('draw'),true);assert.equal(g.view().phase,'ai');assert.equal(g.view().hand.length,2);assert.equal(g.view().lastDrawId,null);});
test('AI plays a legal card deterministically and cannot expose its hand through the view',()=>{const g=fixture({hand0:[card('winter',5)],hand1:[card('spring',4),card('spring',8)],discard:[card('spring',2)],phase:'ai',turn:1});assert.ok(g);assert.equal('opponentHand' in g.view(),false);const events=g.advanceAI();assert.ok(events.some(e=>e.kind==='play'&&e.player===1));assert.equal(g.view().phase,'player');assert.equal(g.view().opponentCount,1);});
test('AI draws once when it has no match, then returns control without repeated card loops',()=>{const g=fixture({hand0:[card('winter',2)],hand1:[card('summer',6)],discard:[card('spring',3)],phase:'ai',turn:1,drawTop:[card('autumn',8)]});assert.ok(g);const events=g.advanceAI();assert.ok(events.some(e=>e.kind==='drawn'&&e.player===1));assert.equal(g.view().phase,'player');assert.equal(g.view().opponentCount,2);});
test('playing the last card ends immediately and terminal state rejects further actions',()=>{const g=fixture({hand0:[card('spring',4)],hand1:[card('winter',8)],discard:[card('spring',2)]});assert.equal(g.act('play',card('spring',4)),true);assert.equal(g.view().status,'won');assert.equal(g.view().winner,0);const stopped=g.serialize();assert.equal(g.act('draw'),false);assert.deepEqual(g.advanceAI(),[]);assert.deepEqual(g.serialize(),stopped);});
test('AI can win the round and the hidden hand remains hidden in the player view',()=>{const g=fixture({hand0:[card('winter',8)],hand1:[card('spring',4)],discard:[card('spring',2)],phase:'ai',turn:1});g.advanceAI();assert.equal(g.view().status,'lost');assert.equal(g.view().winner,1);assert.equal(g.view().opponentCount,0);});
test('discard recycling preserves the active top card and full deck conservation',()=>{const discarded=[card('spring',2),card('summer',6),card('winter',4)];const g=fixture({hand0:[card('autumn',1)],hand1:[card('spring',7)],discard:discarded});const s=g.serialize();s.drawPile=[];const ids=new Set([...s.hands[0],...s.hands[1],...s.discard]);const fill=M.CARDS.map(c=>c.id).filter(x=>!ids.has(x));s.drawPile=fill;const reshuffled=M.restore(s);assert.ok(reshuffled);assert.equal(reshuffled.act('draw'),true);const after=reshuffled.serialize();assert.equal(after.discard.at(-1),discarded.at(-1));assert.equal(after.drawPile.length+after.discard.length+after.hands[0].length+after.hands[1].length,M.CARD_TOTAL);});
test('save/restore preserves a drawn-card decision and deterministic AI continuation',()=>{const g=fixture({hand0:[card('winter',3)],hand1:[card('summer',8)],discard:[card('spring',3)],drawTop:[card('autumn',3)]});g.act('draw');g.drain();const copy=M.restore(g.serialize());assert.ok(copy);assert.deepEqual(copy.view(),g.view());assert.equal(g.act('pass'),true);assert.equal(copy.act('pass'),true);assert.deepEqual(g.advanceAI(),copy.advanceAI());assert.deepEqual(g.serialize(),copy.serialize());});
test('invalid, future, duplicate-card and impossible saves are rejected without mutation',()=>{const original=M.create().serialize();for(const edit of [x=>x.version=2,x=>x.activeSuit='violet',x=>x.phase='nope',x=>x.drawPile[0]=x.hands[0][0],x=>x.lastDrawId='unknown',x=>x.status='won',x=>x.hands=[]]){const bad=structuredClone(original);edit(bad);const before=structuredClone(bad);assert.equal(M.restore(bad),null);assert.deepEqual(bad,before);}});
