// DOM/event doubles cover controls, storage and cleanup; they are not browser QA.
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');
const{harness,assertStopped,read}=require('./support/browser-harness.cjs');
const M=require('../scripts/games/season-shed-model.js');
const KEY='np_season_shed_v1',el=(h,id)=>h.container.querySelector('#'+id),view=h=>h.mountResult.getModel().view();
function fixture({hand0=[],hand1=[],discard,activeSuit=null,phase='player',turn=0,drawTop=[]}={}){const s=M.create({seed:91}).serialize(),all=M.CARDS.map(c=>c.id);discard||=[M.CARDS.find(c=>c.suit==='spring'&&c.value===1).id];const used=new Set([...hand0,...hand1,...discard,...drawTop]);s.hands=[[...hand0],[...hand1]];s.discard=[...discard];s.drawPile=[...all.filter(x=>!used.has(x)),...drawTop];s.activeSuit=activeSuit||M.CARDS.find(c=>c.id===discard.at(-1)).suit;s.phase=phase;s.turn=turn;s.lastDrawId=null;return M.restore(s).serialize();}
function launch(storage=new Map()){const h=harness({loadEngines:false,loadApp:false,storage});vm.runInContext(read('scripts/games/season-shed.js'),h.context,{filename:'scripts/games/season-shed.js'});h.mount=()=>{h.mountResult=h.context.NP_SeasonShed.mount(h.container,h.context.NP_GameSession.start());return h.mountResult;};h.mount();h.flushTimeouts();return h;}
function saved(game){return new Map([[KEY,JSON.stringify({version:1,game})]]);}
function close(h){h.context.NP_GameSession.stop();h.container.innerHTML='';h.flushTimeouts();assertStopped(h);assert.deepEqual(h.errors,[]);}
function click(h,id){el(h,id).dispatch('click',{detail:1});}
function clickCard(h,id){const button=h.container.querySelectorAll('.ss-card').find(b=>b.dataset.cardId===id);assert.ok(button,'card button exists');el(h,'ssHand').dispatch('click',{target:button});}

test('Sắc Chuyền opens directly with a compact visible hand, color-distinct symbols and a screen-reader announcement',()=>{const h=launch();assert.equal(view(h).hand.length,6);assert.equal(view(h).opponentCount,6);assert.equal(view(h).topCard.kind,'number');assert.equal(h.frames.size,0);for(const id of ['ssDraw','ssHand','ssTopCard','ssPause','ssNew','ssPass','ssWildChoices'])assert.ok(el(h,id),id);assert.equal(el(h,'ssAnnounce').getAttribute('aria-live'),'polite');assert.match(read('scripts/games/season-shed.css'),/min-height:44px/);assert.match(read('scripts/games/season-shed.css'),/prefers-reduced-motion/);assert.match(read('scripts/games/season-shed.css'),/overflow-x:auto/);close(h);});

test('a player may play a matching symbol/number card and AI returns control without locking the hand',()=>{const spring2=M.CARDS.find(c=>c.suit==='spring'&&c.value===2).id,summer4=M.CARDS.find(c=>c.suit==='summer'&&c.value===4).id,ai=M.CARDS.find(c=>c.suit==='winter'&&c.value===5).id,h=launch(saved(fixture({hand0:[spring2,summer4],hand1:[ai],discard:[M.CARDS.find(c=>c.suit==='spring'&&c.value===1).id]})));click(h,'ssContinue');assert.equal(h.mountResult.isPaused(),false);clickCard(h,spring2);assert.equal(view(h).phase,'ai');assert.equal(view(h).hand.length,1);h.flushTimeouts();assert.equal(view(h).phase,'player');assert.ok(view(h).opponentCount>=1);close(h);});

test('drawn playable card can be played or passed, with no second card after drawing',()=>{const top=M.CARDS.find(c=>c.suit==='spring'&&c.value===8).id,drawn=M.CARDS.find(c=>c.suit==='spring'&&c.value===8&&c.id.endsWith(':1')).id,held=M.CARDS.find(c=>c.suit==='winter'&&c.value===1).id,other=M.CARDS.find(c=>c.suit==='summer'&&c.value===4).id,s=fixture({hand0:[held,other],hand1:[M.CARDS.find(c=>c.suit==='autumn'&&c.value===3).id],discard:[top],drawTop:[drawn]}),h=launch(saved(s));click(h,'ssContinue');click(h,'ssDraw');assert.equal(view(h).phase,'player-drawn');assert.equal(el(h,'ssPass').hidden,false);assert.deepEqual([...view(h).playableIds],[drawn]);clickCard(h,other);assert.equal(view(h).phase,'player-drawn');assert.equal(view(h).hand.length,3);clickCard(h,drawn);assert.equal(view(h).phase,'ai');assert.equal(view(h).hand.length,2);close(h);});

test('wild color selection is short and cancel leaves the same card in hand',()=>{const h=launch(saved(fixture({hand0:['dew:0',M.CARDS.find(c=>c.suit==='winter'&&c.value===2).id],hand1:[M.CARDS.find(c=>c.suit==='summer'&&c.value===5).id],discard:[M.CARDS.find(c=>c.suit==='spring'&&c.value===3).id]})));click(h,'ssContinue');clickCard(h,'dew:0');assert.equal(el(h,'ssWildChoices').hidden,false);click(h,'ssWildCancel');assert.equal(view(h).hand.some(c=>c.id==='dew:0'),true);clickCard(h,'dew:0');const choose=h.container.querySelectorAll('.ss-season').find(b=>b.dataset.suit==='autumn');choose.click();assert.equal(view(h).activeSuit,'autumn');assert.equal(view(h).phase,'ai');close(h);});

test('restart cancellation keeps the same hand and confirmation resets the duel',()=>{const h=launch();click(h,'ssDraw');click(h,'ssNew');assert.equal(el(h,'ssOverlay').hidden,false);assert.equal(el(h,'ssConfirm').hidden,false);click(h,'ssConfirmNo');assert.equal(h.mountResult.isPaused(),false);assert.equal(view(h).hand.length,7);click(h,'ssNew');click(h,'ssConfirmYes');assert.equal(view(h).hand.length,6);assert.equal(view(h).phase,'player');close(h);});

test('saved duels reopen paused; future and corrupt snapshots are preserved',()=>{const s=fixture({hand0:[M.CARDS.find(c=>c.suit==='spring'&&c.value===4).id,M.CARDS.find(c=>c.suit==='winter'&&c.value===1).id],hand1:[M.CARDS.find(c=>c.suit==='autumn'&&c.value===4).id],discard:[M.CARDS.find(c=>c.suit==='spring'&&c.value===2).id]}),storage=saved(s),h=launch(storage);assert.equal(h.mountResult.isPaused(),true);const before=storage.get(KEY);click(h,'ssContinue');click(h,'ssPause');assert.equal(h.frames.size,0);assert.ok(storage.get(KEY));close(h);const broken=launch(new Map([[KEY,'not json']]));assert.equal(broken.stored.get(KEY+'_recovery'),'not json');close(broken);const raw=JSON.stringify({version:2,game:{version:2}}),future=launch(new Map([[KEY,raw]]));click(future,'ssDraw');assert.equal(future.stored.get(KEY),raw);assert.match(el(future,'ssStorage').textContent,/mới hơn/);close(future);assert.ok(before);});

test('exact legacy route launches Sắc Chuyền and close cancels the pending AI timer',()=>{const h=harness();assert.equal(h.context.openGameById('danh-bai-uno'),true);assert.ok(h.container.querySelector('#ssHand'));click(h,'ssDraw');click(h,'ssDraw');assert.ok([...h.timers.values()].length>0);h.context.closeGameModal();assertStopped(h);h.flushTimeouts();assert.deepEqual(h.errors,[]);close(h);assert.match(read('app.js'),/assets\/season-shed-original\.svg/);assert.doesNotMatch(read('scripts/engines-popcap.js').replace(/launchDanhBaiUno/g,''),/unoShouted|UNO Classic|HÔ UNO|UNO Card Game/i);});
