const test=require('node:test'),assert=require('node:assert/strict');
const M=require('../scripts/games/starlight-match-model.js');
const step=(g,n=1)=>{let e=[];for(let i=0;i<n;i++)e.push(...g.advance(M.STEP));return e;};
function fixture({color=0,board=null,projectile=null,stage=0,status='playing'}={}){const s=M.create({stage,seed:123}).serialize();s.board=board||Array.from({length:M.ROWS},()=>Array(M.COLS).fill(null));s.phase=projectile?'flying':'aim';s.projectile=projectile?{...projectile,color}:null;s.currentColor=color;s.status=status;s.shots=0;s.misses=0;s.pressureRows=0;return M.restore(s);}

test('original three-stage hex field uses five icon colors and an immediate launcher',()=>{const g=M.create(),v=g.view();assert.equal(M.STAGES.length,3);assert.equal(v.board.length,M.ROWS);assert.equal(v.board[0].length,M.COLS);assert.equal(v.colors.length,5);assert.equal(v.phase,'aim');assert.equal(v.status,'playing');assert.equal(M.validSave(g.serialize()),true);});
test('seeded shot-color bag and fixed level boards are deterministic',()=>{const a=M.create({seed:55}).serialize(),b=M.create({seed:55}).serialize(),c=M.create({seed:56}).serialize();assert.deepEqual(a,b);assert.deepEqual(a.board,c.board);assert.notDeepEqual([a.currentColor,a.nextColor],[c.currentColor,c.nextColor]);for(let color=0;color<M.COLOR_COUNT;color++)assert.equal(a.colorBag.filter(x=>x===color).length,4);});
test('aim is clamped and one fire creates a single projectile',()=>{const g=M.create();assert.equal(g.act('aim',40),true);assert.equal(g.view().angle,M.ANGLE_LIMIT);assert.equal(g.act('fire'),true);assert.equal(g.view().phase,'flying');assert.equal(g.view().projectile.color,g.view().currentColor);assert.equal(g.act('fire'),false);});
test('wall contact bounces the projectile without changing its color',()=>{const g=fixture({color:2,projectile:{x:80,y:500,vx:-12,vy:0}});assert.ok(g);step(g);assert.ok(g.view().projectile.vx>0);assert.equal(g.view().projectile.color,2);});
test('three adjacent matching fragments pop and score after the shot sticks',()=>{const board=Array.from({length:M.ROWS},()=>Array(M.COLS).fill(null));board[0][2]=0;board[0][3]=0;board[1][2]=1;const p={x: M.X0+4*M.X_STEP+M.X_STEP/2,y:M.Y0- M.CELL_RADIUS+8,vx:0,vy:-M.SHOT_SPEED};const g=fixture({color:0,board,projectile:p});assert.ok(g);const events=step(g);assert.ok(events.some(e=>e.kind==='pop'&&e.count===3));assert.equal(g.view().board[0][2],null);assert.equal(g.view().board[0][3],null);assert.ok(events.some(e=>e.kind==='pop'&&e.fall>=1));assert.ok(g.view().score>=40);});
test('a shot with fewer than three matches stays and counts toward tide pressure',()=>{const board=Array.from({length:M.ROWS},()=>Array(M.COLS).fill(null));board[0][2]=0;const p={x:M.X0+3*M.X_STEP+M.X_STEP/2,y:M.Y0-M.CELL_RADIUS+8,vx:0,vy:-M.SHOT_SPEED};const g=fixture({color:4,board,projectile:p});const events=step(g);assert.ok(events.some(e=>e.kind==='miss'));assert.equal(g.view().misses,1);assert.equal(g.view().board.flat().filter(x=>x!==null).length,2);});
test('four misses push the field down one authored tide row',()=>{const board=Array.from({length:M.ROWS},()=>Array(M.COLS).fill(null));board[0][3]=1;const p={x:M.X0+5*M.X_STEP,y:M.Y0-M.CELL_RADIUS+8,vx:0,vy:-M.SHOT_SPEED};const g=fixture({color:4,board,projectile:p});const s=g.serialize();s.misses=3;const pressured=M.restore(s);assert.ok(pressured);const events=step(pressured);assert.ok(events.some(e=>e.kind==='push'));assert.equal(pressured.view().pressureRows,1);assert.equal(pressured.view().board[1][3],1);assert.equal(pressured.view().misses,0);});
test('fourth miss loses only when the pushed fragments reach the danger edge',()=>{const board=Array.from({length:M.ROWS},()=>Array(M.COLS).fill(null));board[M.ROWS-2][3]=1;const p={x:M.X0+5*M.X_STEP,y:M.Y0-M.CELL_RADIUS+8,vx:0,vy:-M.SHOT_SPEED};const g=fixture({color:4,board,projectile:p});const s=g.serialize();s.misses=3;const last=M.restore(s);assert.ok(last);const events=step(last);assert.equal(last.view().status,'lost');assert.ok(events.some(e=>e.kind==='lost'));});
test('remaining fragments keep their score and an empty board clears the stage',()=>{const board=Array.from({length:M.ROWS},()=>Array(M.COLS).fill(null));board[0][2]=0;board[0][3]=0;const p={x:M.X0+4*M.X_STEP+M.X_STEP/2,y:M.Y0-M.CELL_RADIUS+8,vx:0,vy:-M.SHOT_SPEED};const g=fixture({color:0,board,projectile:p});step(g);assert.equal(g.view().status,'cleared');assert.ok(g.next());});
test('banked score carries between stages and retry removes only current-stage points',()=>{const s=M.create().serialize();s.board=Array.from({length:M.ROWS},()=>Array(M.COLS).fill(null));s.status='cleared';s.phase='over';s.score=150;const cleared=M.restore(s);assert.ok(cleared);const next=cleared.next();assert.equal(next.view().stage,1);assert.equal(next.view().bankScore,150);const retryState=next.serialize();retryState.status='lost';retryState.phase='over';retryState.score=350;retryState.timeTicks=M.STAGES[1].duration;const lost=M.restore(retryState);assert.ok(lost);assert.equal(lost.retry().view().score,150);});
test('final clear wins and terminal input cannot launch again',()=>{const s=M.create({stage:M.STAGES.length-1}).serialize();s.board=Array.from({length:M.ROWS},()=>Array(M.COLS).fill(null));s.status='won';s.phase='over';s.score=77;const win=M.restore(s);assert.ok(win);assert.equal(win.view().status,'won');assert.equal(win.act('fire'),false);assert.equal(win.next(),null);});
test('save/restore preserves flying shot, bag state and fixed-step outcomes',()=>{const g=M.create();g.act('aim',.4);g.act('fire');step(g,5);const h=M.restore(g.serialize());assert.ok(h);for(let i=0;i<150;i++)assert.deepEqual(g.advance(M.STEP),h.advance(M.STEP));assert.deepEqual(g.serialize(),h.serialize());});
test('corrupt, future, sparse and impossible board snapshots reject without mutation',()=>{const src=M.create().serialize();for(const edit of [s=>s.version=2,s=>s.stage=99,s=>s.seed=0x100000000,s=>s.colorBag.pop(),s=>s.colorBag.fill(0),s=>s.board[0][0]=99,s=>s.board[0].pop(),s=>s.angle=99,s=>s.currentColor=8,s=>{s.phase='flying';s.projectile={x:1,y:2,vx:1,vy:-1,color:1.5}},s=>s.status='lost',s=>s.misses=M.MISS_LIMIT]){const bad=structuredClone(src);edit(bad);const before=structuredClone(bad);assert.equal(M.restore(bad),null);assert.deepEqual(bad,before);}});
