/* Original Bờ Kè Sao lane-defense player interface. */
(function(){
 'use strict';
 const STORAGE='np_beacon_shore_v1',RECOVERY=STORAGE+'_recovery',TYPES=['lamp','fan','bell'];
 function mount(container,session){
  const M=window.NP_BeaconShoreModel;if(!M||!session)throw new Error('Bờ Kè Sao rules are not ready');
  const{listen,requestAnimationFrame,cancelAnimationFrame,setTimeout,onCleanup}=session;
  let raw=null,saved=null,storageOK=true,notice='';try{raw=localStorage.getItem(STORAGE);}catch(_){storageOK=false;notice='Ván này vẫn chơi được.';}
  if(raw){try{saved=JSON.parse(raw);}catch(_){saved=null;}}
  const future=Number.isInteger(saved?.version)&&saved.version>1;
  let model=!future&&saved?.version===1?M.restore(saved.game):null;
  if(raw&&!model&&!future){try{const old=localStorage.getItem(RECOVERY);if(old&&old!==raw)storageOK=false;else localStorage.setItem(RECOVERY,raw);}catch(_){storageOK=false;}notice='Bản lưu lỗi được giữ riêng.';}
  if(future){storageOK=false;notice='Bản lưu mới hơn được giữ nguyên.';}
  const restored=Boolean(model);model||=M.create();let alive=true,paused=restored&&model.view().status==='playing',confirm=false,pausedBeforeConfirm=false;
  let frame=null,lastFrame=null,accumulator=0,saveAccumulator=0,lastHUD='',lastBoard='';
  container.classList.add('bs-host');
  const cells=Array.from({length:M.ROWS},(_,r)=>Array.from({length:M.COLS},(_,c)=>`<button class="bs-cell" id="bsCell-${r}-${c}" data-row="${r}" data-col="${c}" type="button" role="gridcell" aria-label="Hành lang ${r+1}, ô ${c+1}, trống"></button>`).join('')).join('');
  container.innerHTML=`
   <section class="bs-game" aria-label="Bờ Kè Sao">
    <header class="bs-header"><h3>Bờ Kè Sao</h3><div class="bs-toolbar"><button class="bs-button" id="bsNew" type="button" aria-label="Ván mới" title="Ván mới">↻</button><button class="bs-button" id="bsPause" type="button" aria-label="Tạm dừng" title="Tạm dừng">Ⅱ</button></div></header>
    <div class="bs-hud"><div><span>Làn</span><strong id="bsWave">1 / 4</strong></div><div><span>Đèn</span><strong id="bsEnergy">100</strong></div><div><span>Lượt</span><strong id="bsLives">♥♥♥</strong></div><div><span>Điểm</span><strong id="bsScore">0</strong></div></div>
    <div class="bs-brief"><span class="bs-beacon" aria-hidden="true">✧</span><span>Chọn khí cụ, chạm ô trống. Làn sương đi từ phải qua trái.</span></div>
    <div class="bs-board-scroll"><div class="bs-grid" id="bsGrid" role="grid" aria-label="Năm hành lang bảo vệ hải đăng">${cells}</div></div>
    <div class="bs-devices" role="group" aria-label="Khí cụ phòng thủ"><button class="bs-button bs-device" id="bsSelect-lamp" data-type="lamp" type="button"><span aria-hidden="true">✦</span><span>Đèn dẫn</span><small id="bsCost-lamp">45</small></button><button class="bs-button bs-device" id="bsSelect-fan" data-type="fan" type="button"><span aria-hidden="true">≋</span><span>Quạt gió</span><small id="bsCost-fan">55</small></button><button class="bs-button bs-device" id="bsSelect-bell" data-type="bell" type="button"><span aria-hidden="true">◉</span><span>Chuông</span><small id="bsCost-bell">70</small></button></div>
    <p class="np-game-sr" id="bsStatus" role="status" aria-live="polite" aria-atomic="true">Đèn tự động chặn sương. Năng lượng tự hồi.</p><p class="bs-storage" id="bsStorage" hidden role="status"></p>
    <details class="bs-help"><summary aria-label="Cách chơi">?</summary><p>Đặt đèn để bắn, quạt để làm chậm hoặc chuông để dội sóng. Năng lượng tự hồi.</p></details>
    <div class="bs-overlay" id="bsOverlay" hidden><div class="bs-card"><strong id="bsOverlayTitle"></strong><p id="bsOverlayText" hidden></p><div class="bs-confirm" id="bsConfirm" hidden role="group" aria-label="Xác nhận ván mới"><span>Ván mới?</span><button class="bs-button bs-primary" id="bsConfirmYes" type="button">Bắt đầu</button><button class="bs-button" id="bsConfirmNo" type="button">Ở lại</button></div><button class="bs-button bs-primary" id="bsContinue" type="button">▶</button></div></div>
   </section>`;
  const el=id=>container.querySelector('#'+id);
  function announce(text){el('bsStatus').textContent=text;}
  function setNotice(text){if(!text)return;notice=text;el('bsStorage').hidden=false;el('bsStorage').textContent=text;}
  function save(){saveAccumulator=0;if(!alive||!storageOK){if(notice)setNotice(notice);return;}try{if(localStorage.getItem(STORAGE)!==raw){storageOK=false;setNotice('Bản lưu đã đổi ở tab khác; ván này không ghi đè.');return;}raw=JSON.stringify({version:1,best:model.view().score,game:model.serialize()});localStorage.setItem(STORAGE,raw);}catch(_){storageOK=false;setNotice('Không lưu được; ván này vẫn chơi được.');}}
  function action(type,value){if(!alive||paused||confirm||model.view().status!=='playing')return false;const ok=model.act(type,value);drain(model.drain());update();save();return ok;}
  function drain(events){for(const e of events||[]){if(e.kind==='blocked')announce(e.reason==='energy'?'Thiếu đèn năng lượng.':e.reason==='occupied'?'Ô đã có khí cụ.':'Không đặt được ở ô này.');else if(e.kind==='breach')announce(`Sương lọt qua. Còn ${e.lives} lượt.`);else if(e.kind==='wave')announce(`Làn ${e.wave+1}.`);else if(e.kind==='won')announce('Hải đăng an toàn!');else if(e.kind==='lost')announce('Sương đã qua đê.');}if(events?.length){update();save();}}
  function pause(message='Đã tạm dừng.'){if(model.view().status!=='playing')return;paused=true;accumulator=0;lastFrame=null;cancelAnimationFrame(frame);frame=null;update();save();announce(message);el('bsContinue').focus();}
  function resume(){if(!alive||confirm||model.view().status!=='playing'||document.hidden)return;paused=false;accumulator=0;lastFrame=null;update();save();el('bsCell-2-3').focus();if(frame===null)frame=requestAnimationFrame(loop);announce('Tiếp tục.');}
  function newRun(){cancelAnimationFrame(frame);frame=null;model=M.create();paused=false;confirm=false;accumulator=0;lastFrame=null;lastBoard='';el('bsConfirm').hidden=true;update();save();announce('Ván mới.');el('bsCell-2-3').focus();frame=requestAnimationFrame(loop);}
  function requestNew(){if(confirm)return;const v=model.view(),progressed=v.tick>0||v.score>0||v.towers.length>0;if(v.status==='playing'&&progressed){pausedBeforeConfirm=paused;confirm=true;paused=true;cancelAnimationFrame(frame);frame=null;el('bsConfirm').hidden=false;update();save();el('bsConfirmYes').focus();}else newRun();}
  function renderTray(v){for(const type of TYPES){const b=el('bsSelect-'+type),d=M.DEVICES[type];b.disabled=paused||confirm||v.status!=='playing';b.setAttribute('aria-pressed',String(v.selectedType===type));b.setAttribute('aria-label',`${d.name}, giá ${d.cost}${v.selectedType===type?', đã chọn':''}`);b.classList.toggle('bs-selected',v.selectedType===type);el('bsCost-'+type).textContent=String(d.cost);}}
  function renderBoard(v){const buckets=new Map();for(const e of v.enemies){const c=Math.max(0,Math.min(M.COLS-1,Math.floor(e.x))),key=e.row+':'+c,items=buckets.get(key)||[];items.push(e);buckets.set(key,items);}const towers=new Map(v.towers.map(t=>[t.row+':'+t.col,t]));const stamp=[...towers].map(([k,t])=>`${k}:${t.type}`).join('|')+'#'+[...buckets].map(([k,es])=>`${k}:${es.map(e=>e.id+'.'+e.hp).join(',')}`).join('|')+`#${paused}|${confirm}|${v.status}`;if(stamp===lastBoard)return;lastBoard=stamp;
   for(let r=0;r<M.ROWS;r++)for(let c=0;c<M.COLS;c++){const b=el(`bsCell-${r}-${c}`),key=r+':'+c,t=towers.get(key),es=buckets.get(key)||[],content=t?M.DEVICES[t.type].icon:'';b.disabled=paused||confirm||v.status!=='playing';b.dataset.tower=t?.type||'';b.dataset.threat=String(es.length);b.textContent=(content?content+' ':'')+es.map(e=>M.ENEMIES[e.type].icon).join('');b.setAttribute('aria-label',`Hành lang ${r+1}, ô ${c+1}${t?`, ${M.DEVICES[t.type].name}`:''}${es.length?`, ${es.map(e=>M.ENEMIES[e.type].name+' '+e.hp).join(', ')}`:', trống'}`);b.classList.toggle('bs-has-tower',!!t);b.classList.toggle('bs-threat',es.length>0);}}
  function update(){const v=model.view(),terminal=v.status!=='playing',stamp=[v.waveIndex,v.energy,v.lives,v.score,v.status,paused,confirm].join('|');if(stamp!==lastHUD){lastHUD=stamp;el('bsWave').textContent=`${Math.min(v.waveIndex+1,M.WAVES.length)} / ${M.WAVES.length}`;el('bsEnergy').textContent=String(v.energy);el('bsLives').textContent='♥'.repeat(v.lives)+'♡'.repeat(3-v.lives);el('bsScore').textContent=String(v.score);el('bsPause').disabled=terminal||confirm;el('bsPause').textContent=paused&&!terminal?'▶':'Ⅱ';el('bsPause').setAttribute('aria-label',paused&&!terminal?'Tiếp tục':'Tạm dừng');el('bsOverlay').hidden=!(paused||terminal||confirm);el('bsConfirm').hidden=!confirm;el('bsContinue').hidden=confirm;el('bsOverlayTitle').textContent=confirm?'Ván mới?':v.status==='won'?'Hải đăng an toàn':v.status==='lost'?'Làn sương đã tới':'Tạm dừng';el('bsOverlayText').hidden=!terminal;el('bsOverlayText').textContent=v.status==='won'?`${v.score} điểm.`:v.status==='lost'?`Đã giữ được ${v.score} điểm.`:'';el('bsContinue').textContent=v.status==='won'||v.status==='lost'?'Chơi lại':'▶';el('bsContinue').setAttribute('aria-label',v.status==='won'||v.status==='lost'?'Chơi lại':'Tiếp tục');}renderTray(v);renderBoard(v);}
  function loop(ts){frame=null;if(!alive||paused||confirm||model.view().status!=='playing')return;const dt=lastFrame===null?0:ts-lastFrame;lastFrame=ts;if(dt>250){pause('Đã tạm dừng sau khi rời tiệm.');return;}accumulator+=Math.max(0,dt);saveAccumulator+=Math.max(0,dt);while(accumulator+1e-7>=M.STEP&&model.view().status==='playing'){accumulator-=M.STEP;drain(model.advance(M.STEP));}update();if(!paused&&!confirm&&model.view().status==='playing')frame=requestAnimationFrame(loop);if(saveAccumulator>=750)save();}
  for(const type of TYPES)listen(el('bsSelect-'+type),'click',()=>action('select',type));
  for(let r=0;r<M.ROWS;r++)for(let c=0;c<M.COLS;c++)listen(el(`bsCell-${r}-${c}`),'click',()=>action('place',{row:r,col:c}));
  listen(el('bsNew'),'click',requestNew);listen(el('bsPause'),'click',()=>paused?resume():pause());listen(el('bsConfirmYes'),'click',newRun);listen(el('bsConfirmNo'),'click',()=>{confirm=false;paused=pausedBeforeConfirm;accumulator=0;lastFrame=null;update();save();if(paused)el('bsContinue').focus();else frame=requestAnimationFrame(loop);});listen(el('bsContinue'),'click',()=>{if(confirm)return;if(model.view().status!=='playing')newRun();else resume();});
  listen(container,'keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.repeat||e.target.closest?.('input,textarea,select,[contenteditable]'))return;if(String(e.key).toLowerCase()==='p'){e.preventDefault();paused?resume():pause();}});
  listen(window,'blur',()=>pause('Đã tạm dừng khi mất tiêu điểm.'));listen(document,'visibilitychange',()=>{if(document.hidden)pause('Đã tạm dừng khi chuyển tab.');});listen(window,'pagehide',()=>pause('Đã lưu ván đang chơi.'));
  onCleanup(()=>{cancelAnimationFrame(frame);frame=null;save();container.classList.remove('bs-host');alive=false;});
  if(paused)announce('Ván đã lưu. Bấm tiếp tục để chơi.');if(notice)setNotice(notice);update();save();if(!paused&&model.view().status==='playing')frame=requestAnimationFrame(loop);setTimeout(()=>{if(alive)el(paused?'bsContinue':'bsCell-2-3').focus({preventScroll:true});},0);return{getModel:()=>model,isPaused:()=>paused};
 }
 window.NP_BeaconShore=Object.freeze({mount});
 if(window.NP_Engines&&typeof window.NP_Engines.launchPvZ==='function')window.NP_Engines.launchPvZ=function(container){return mount(container,window.NP_GameSession.start());};
})();
