/* Original Vòm Mây platformer UI. Its small rules engine has no external art/audio dependencies. */
(function(){
 'use strict';
 const STORAGE='np_cloud_canopy_v1',RECOVERY=STORAGE+'_recovery';
 function mount(container,session,audio){
  const M=window.NP_CloudCanopyModel;
  if(!M||!session)throw new Error('Vòm Mây rules are not ready');
  const{listen,requestAnimationFrame,cancelAnimationFrame,setTimeout,onCleanup}=session;
  let raw=null,saved=null,storageOK=true,notice='';
  try{raw=localStorage.getItem(STORAGE);}catch(_){storageOK=false;notice='Ván này vẫn chơi được.';}
  if(raw){try{saved=JSON.parse(raw);}catch(_){saved=null;}}
  const future=Number.isInteger(saved?.version)&&saved.version>1||Number.isInteger(saved?.game?.version)&&saved.game.version>1;
  let model=!future&&saved?.version===1&&Number.isSafeInteger(saved.best)&&saved.best>=0?M.restore(saved.game):null;
  if(raw&&!model&&!future){try{const prior=localStorage.getItem(RECOVERY);if(prior&&prior!==raw)storageOK=false;else localStorage.setItem(RECOVERY,raw);}catch(_){storageOK=false;}notice='Bản lưu lỗi được giữ riêng.';}
  if(future){storageOK=false;notice='Bản lưu mới hơn được giữ nguyên.';}
  const restored=Boolean(model);model||=M.create();let best=restored?saved.best:0,alive=true,paused=restored&&model.view().status==='playing',confirm=false,pausedBeforeConfirm=false;
  let frame=null,lastFrame=null,accumulator=0,saveAccumulator=0,tapSerial=0,lastHUD='',userGesture=false,jumpTap=false;
  const held=new Map(),pointers=new Map(),suppressedClicks=new Set();
  container.classList.add('cc-host');
  container.innerHTML=`
   <section class="cc-game" aria-label="Vòm Mây">
    <header class="cc-header"><div><span class="cc-kicker">MỘT HÀNH TRÌNH TRÊN MÂY</span><h3>Vòm Mây</h3></div>
     <div class="cc-toolbar"><button class="cc-button" id="ccNew" type="button" aria-label="Ván mới" title="Ván mới">↻</button><button class="cc-button" id="ccPause" type="button" aria-label="Tạm dừng" title="Tạm dừng">Ⅱ</button></div>
    </header>
    <div class="cc-hud" aria-label="Trạng thái ván"><div><span>Chặng</span><strong id="ccStage">1 / 3</strong></div><div><span>Chuông</span><strong id="ccBells">0 / 3</strong></div><div><span>Mạng</span><strong id="ccLives">3</strong></div><div><span>Điểm</span><strong id="ccScore">0</strong></div></div>
    <div class="cc-board-wrap"><canvas id="ccCanvas" width="640" height="360" tabindex="0" role="img" aria-label="Bàn Vòm Mây. Dùng phím trái/phải và Space để nhảy." aria-describedby="ccInstructions">Bàn chơi Vòm Mây.</canvas>
     <div class="cc-overlay" id="ccOverlay" hidden><div class="cc-card"><strong id="ccTitle">Tạm dừng</strong><p id="ccText" hidden></p><button class="cc-button cc-primary" id="ccContinue" type="button">▶</button></div></div>
    </div>
    <div class="cc-controls" role="group" aria-label="Điều khiển Vòm Mây"><div class="cc-move"><button class="cc-button cc-dir" id="ccLeft" data-action="left" type="button" aria-label="Sang trái">←</button><button class="cc-button cc-dir" id="ccRight" data-action="right" type="button" aria-label="Sang phải">→</button></div><button class="cc-button cc-jump" id="ccJump" data-action="jump" type="button" aria-label="Nhảy">Nhảy</button></div>
    <p class="np-game-sr cc-sr" id="ccInstructions">Lướt qua các mỏm mây, gom ba chuông gió rồi tìm cổng sáng. Giữ trái/phải để chạy; giữ Space để nhảy cao hơn; P để tạm dừng.</p>
    <p class="np-game-sr cc-sr" id="ccStatus" role="status" aria-live="polite" aria-atomic="true">Gom chuông gió để mở cổng.</p>
    <p class="cc-storage" id="ccStorage" hidden role="status"></p>
    <details class="cc-help"><summary aria-label="Cách chơi">?</summary><p>Gom ba chuông gió để mở cổng.</p></details>
    <div class="cc-confirm" id="ccConfirm" hidden role="group" aria-label="Xác nhận ván mới"><span>Ván mới?</span><button class="cc-button cc-primary" id="ccConfirmYes" type="button">Bắt đầu</button><button class="cc-button" id="ccConfirmNo" type="button">Ở lại</button></div>
   </section>`;
  const el=id=>container.querySelector('#'+id),canvas=el('ccCanvas'),ctx=canvas.getContext('2d');
  if(!ctx){el('ccOverlay').hidden=false;el('ccTitle').textContent='Không mở được bàn chơi';el('ccContinue').hidden=true;onCleanup(()=>container.classList.remove('cc-host'));return null;}
  const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
  function sizeCanvas(){const dpr=Math.min(2,Math.max(1,Number(window.devicePixelRatio)||1));canvas.width=M.WIDTH*dpr;canvas.height=M.HEIGHT*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);}
  sizeCanvas();
  function setNotice(text){if(!text)return;notice=text;el('ccStorage').hidden=false;el('ccStorage').textContent=text;}
  function save(){saveAccumulator=0;if(!alive||!storageOK){if(notice)setNotice(notice);return;}const v=model.view();best=Math.max(best,v.score);try{if(localStorage.getItem(STORAGE)!==raw){storageOK=false;setNotice('Bản lưu đã đổi ở tab khác; ván này không ghi đè.');return;}raw=JSON.stringify({version:1,best,game:model.serialize()});localStorage.setItem(STORAGE,raw);}catch(_){storageOK=false;setNotice('Không lưu được; ván này vẫn chơi được.');}}
  function announce(text){el('ccStatus').textContent=text;}
  function unlockAudio(){userGesture=true;if(window.NEWPLAYGROUND_MUTED===true||window.NP_Audio?.isMuted)return;try{audio?.init?.();if(audio?.ctx?.state==='suspended')audio.ctx.resume()?.catch?.(()=>{});}catch(_) {}}
  function sound(kind){if(!userGesture||window.NEWPLAYGROUND_MUTED===true||window.NP_Audio?.isMuted)return;const pitch={jump:440,land:320,bell:740,checkpoint:580,locked:180,hurt:130,cleared:660,won:820,lost:110}[kind];if(!pitch)return;try{audio?.playTone?.(pitch,kind==='hurt'?'triangle':'sine',.07,.025);}catch(_) {}}
  function drain(events){for(const e of events||[])sound(e.kind);if(events?.some(e=>e.kind==='bell'))announce('Đã gom chuông gió.');if(events?.some(e=>e.kind==='checkpoint'))announce('Đã đến mỏm nghỉ.');if(events?.some(e=>e.kind==='locked'))announce(`Còn ${events.find(e=>e.kind==='locked').remaining} chuông gió.`);if(events?.some(e=>e.kind==='hurt'))announce('Gió đẩy bạn về mỏm nghỉ.');if(events?.some(e=>e.kind==='cleared'))announce('Đã qua chặng.');if(events?.some(e=>e.kind==='won'))announce('Đã chạm tới đỉnh Vòm Mây!');if(events?.length){update();save();}}
  function currentInput(){let left=false,right=false,jump=jumpTap;for(const action of held.values()){if(action==='left')left=true;else if(action==='right')right=true;else if(action==='jump')jump=true;}return{left,right,jump};}
  function clearInput(){for(const [id,p]of pointers){suppressedClicks.add(p.buttonId);try{p.button.releasePointerCapture?.(id);}catch(_) {}}pointers.clear();held.clear();jumpTap=false;}
  function releaseOwner(owner){held.delete(owner);}
  function releasePointer(event){const p=pointers.get(event.pointerId);if(!p)return;pointers.delete(event.pointerId);suppressedClicks.add(p.buttonId);try{p.button.releasePointerCapture?.(event.pointerId);}catch(_){}releaseOwner(p.owner);}
  function pause(message='Đã tạm dừng.'){if(model.view().status!=='playing')return;paused=true;accumulator=0;lastFrame=null;cancelAnimationFrame(frame);frame=null;clearInput();update();save();announce(message);el('ccContinue').focus();}
  function resume(){if(!alive||confirm||model.view().status!=='playing'||document.hidden)return;unlockAudio();paused=false;accumulator=0;lastFrame=null;update();save();canvas.focus({preventScroll:true});if(frame===null)frame=requestAnimationFrame(loop);announce('Chơi tiếp.');}
  function newGame(){cancelAnimationFrame(frame);frame=null;clearInput();model=M.create();paused=false;confirm=false;accumulator=0;lastFrame=null;el('ccConfirm').hidden=true;update();draw();save();announce('Ván mới. Gom chuông gió để mở cổng.');canvas.focus({preventScroll:true});frame=requestAnimationFrame(loop);}
  function retry(){const next=model.retry();if(!next)return newGame();cancelAnimationFrame(frame);frame=null;clearInput();model=next;paused=false;confirm=false;accumulator=0;lastFrame=null;update();draw();save();announce('Thử lại chặng này.');canvas.focus({preventScroll:true});frame=requestAnimationFrame(loop);}
  function nextStage(){const next=model.next();if(!next)return;model=next;paused=false;confirm=false;accumulator=0;lastFrame=null;update();draw();save();announce(`Chặng ${model.view().stage+1}.`);canvas.focus({preventScroll:true});frame=requestAnimationFrame(loop);}
  function requestNew(){const v=model.view(),progressed=v.ticks>0||v.score>v.bankScore||v.stage>0||v.player.x>v.level.spawn.x;if(v.status==='playing'&&progressed){pausedBeforeConfirm=paused;confirm=true;paused=true;cancelAnimationFrame(frame);frame=null;clearInput();el('ccConfirm').hidden=false;update();save();el('ccConfirmYes').focus();}else newGame();}
  function rounded(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath();}
  function drawCloud(x,y,scale=1,alpha=.45){ctx.save();ctx.globalAlpha=alpha;ctx.fillStyle='#ffffff';ctx.beginPath();ctx.ellipse(x,y,42*scale,17*scale,0,0,Math.PI*2);ctx.ellipse(x-22*scale,y+4*scale,22*scale,13*scale,0,0,Math.PI*2);ctx.ellipse(x+21*scale,y+3*scale,24*scale,14*scale,0,0,Math.PI*2);ctx.fill();ctx.restore();}
  function drawBell(x,y){ctx.save();ctx.strokeStyle='#7da6aa';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y-2,9,Math.PI,Math.PI*2);ctx.moveTo(x-9,y-2);ctx.lineTo(x+9,y-2);ctx.moveTo(x,y+1);ctx.lineTo(x,y+12);ctx.moveTo(x-6,y+2);ctx.lineTo(x-6,y+10);ctx.moveTo(x+6,y+2);ctx.lineTo(x+6,y+9);ctx.stroke();ctx.fillStyle='#f4c15f';ctx.beginPath();ctx.arc(x,y+12,3,0,Math.PI*2);ctx.arc(x-6,y+10,2,0,Math.PI*2);ctx.arc(x+6,y+9,2,0,Math.PI*2);ctx.fill();ctx.restore();}
  function drawPlayer(p){ctx.save();ctx.translate(p.x+M.PLAYER_W/2,p.y+M.PLAYER_H/2);ctx.scale(p.facing,1);if(p.invulnerable>0&&Math.floor(p.invulnerable/5)%2===0)ctx.globalAlpha=.42;ctx.fillStyle='#254b55';ctx.beginPath();ctx.moveTo(0,-13);ctx.lineTo(11,0);ctx.lineTo(0,13);ctx.lineTo(-11,0);ctx.closePath();ctx.fill();ctx.fillStyle='#f4f1df';ctx.beginPath();ctx.moveTo(0,-8);ctx.lineTo(6,0);ctx.lineTo(0,8);ctx.lineTo(-6,0);ctx.closePath();ctx.fill();ctx.strokeStyle='#d27c6e';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-7,6);ctx.quadraticCurveTo(-18,10,-13,18);ctx.stroke();ctx.fillStyle='#d27c6e';ctx.beginPath();ctx.arc(-13,18,3,0,Math.PI*2);ctx.fill();ctx.restore();}
  function drawEnemy(enemy){ctx.save();ctx.fillStyle='#758b88';ctx.beginPath();ctx.ellipse(enemy.x+9,enemy.y+10,10,8,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#526e70';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(enemy.x+4,enemy.y+3);ctx.lineTo(enemy.x+1,enemy.y-4);ctx.moveTo(enemy.x+14,enemy.y+3);ctx.lineTo(enemy.x+17,enemy.y-4);ctx.stroke();ctx.fillStyle='#fff7dd';ctx.beginPath();ctx.arc(enemy.x+6,enemy.y+8,2,0,Math.PI*2);ctx.arc(enemy.x+12,enemy.y+8,2,0,Math.PI*2);ctx.fill();ctx.restore();}
  function draw(){const v=model.view(),L=v.level,p=v.player,camera=clamp(p.x-220,0,L.width-M.WIDTH);ctx.clearRect(0,0,M.WIDTH,M.HEIGHT);ctx.fillStyle=L.sky;ctx.fillRect(0,0,M.WIDTH,M.HEIGHT);ctx.save();ctx.translate(-camera*.22,0);for(let i=0;i<8;i++)drawCloud(i*210+90,55+(i%3)*28,.9+(i%2)*.2,.4);ctx.restore();ctx.save();ctx.translate(-camera,0);
    // Far cloud shelf silhouettes.
    ctx.fillStyle=L.color;for(let i=0;i<5;i++){ctx.beginPath();ctx.ellipse(i*360+180,346,160,42,0,Math.PI,Math.PI*2);ctx.fill();}
    for(const [x,y,w]of L.platforms){ctx.fillStyle='#d6ece8';rounded(x,y,w,15,8);ctx.fill();ctx.fillStyle=L.color;rounded(x+4,y+10,w-8,12,7);ctx.fill();ctx.strokeStyle='#52817e';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x+8,y+13);ctx.lineTo(x+w-8,y+13);ctx.stroke();}
    for(const [x,y,w,h,fx,fy]of L.winds){ctx.strokeStyle='rgba(87,146,160,.45)';ctx.lineWidth=2;for(let k=0;k<3;k++){ctx.beginPath();ctx.moveTo(x,y+20+k*24);ctx.bezierCurveTo(x+w*.28,y+4+k*24,x+w*.62,y+36+k*24,x+w,y+16+k*24);ctx.stroke();}}
    L.bells.forEach(([x,y],i)=>{if(!v.collected[i])drawBell(x,y);});
    // Closed/open wind arch is original scenery; no copied goal marker.
    const gx=L.gate.x,gy=L.gate.y,open=v.remaining===0;ctx.strokeStyle=open?'#427e73':'#718a86';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(gx,312);ctx.lineTo(gx,gy+18);ctx.quadraticCurveTo(gx+28,gy-16,gx+56,gy+18);ctx.lineTo(gx+56,312);ctx.stroke();ctx.strokeStyle=open?'#e9bd61':'#aebcba';ctx.lineWidth=3;ctx.beginPath();ctx.arc(gx+28,gy+18,13,0,Math.PI*2);ctx.stroke();
    v.enemies.forEach(e=>drawEnemy(e));if(v.status!=='lost')drawPlayer(p);ctx.restore();
  }
  function update(){const v=model.view(),s=v.status,terminal=s!=='playing',stamp=[v.stage,v.collectedCount,v.lives,v.score,s,paused,confirm].join('/');if(stamp!==lastHUD){lastHUD=stamp;el('ccStage').textContent=`${v.stage+1} / ${M.LEVELS.length}`;el('ccBells').textContent=`${v.collectedCount} / ${v.bellCount}`;el('ccLives').textContent=String(v.lives);el('ccScore').textContent=v.score.toLocaleString('vi-VN');el('ccStage').setAttribute('aria-label',`Chặng ${v.stage+1}: ${v.level.name}`);el('ccBells').setAttribute('aria-label',`${v.collectedCount} trong ${v.bellCount} chuông gió`);el('ccLives').setAttribute('aria-label',`${v.lives} mạng`);el('ccOverlay').hidden=!(paused||terminal||confirm);el('ccConfirm').hidden=!confirm;el('ccContinue').hidden=confirm;el('ccPause').disabled=terminal||confirm;el('ccPause').textContent=paused&&!terminal?'▶':'Ⅱ';el('ccPause').setAttribute('aria-label',paused&&!terminal?'Chơi tiếp':'Tạm dừng');el('ccTitle').textContent=confirm?'Ván mới?':s==='cleared'?'Qua chặng!':s==='won'?'Đỉnh Vòm Mây!':s==='lost'?'Thử lại chặng?':'Tạm dừng';el('ccText').hidden=!terminal;el('ccText').textContent=s==='cleared'?`Đã qua ${v.level.name}.`:s==='won'?`${v.score.toLocaleString('vi-VN')} điểm`:`${v.score.toLocaleString('vi-VN')} điểm · còn ${v.lives} mạng`;el('ccContinue').textContent=s==='cleared'?'Chặng tiếp':s==='lost'?'Thử lại':s==='won'?'Ván mới':'▶';el('ccContinue').setAttribute('aria-label',s==='cleared'?'Sang chặng tiếp':s==='lost'?'Thử lại chặng này':s==='won'?'Chơi ván mới':'Chơi tiếp');for(const b of container.querySelectorAll('.cc-dir,.cc-jump'))b.disabled=paused||confirm||terminal;canvas.tabIndex=paused||terminal||confirm?-1:0;canvas.setAttribute('aria-label',`Vòm Mây, chặng ${v.stage+1} trên ${M.LEVELS.length}. Gom ${v.remaining} chuông gió để mở cổng. ${v.lives} mạng.`);}draw();}
  function loop(ts){frame=null;if(!alive||paused||confirm||model.view().status!=='playing')return;const dt=lastFrame===null?0:ts-lastFrame;lastFrame=ts;if(dt>250){pause('Đã tạm dừng sau khi rời màn chơi.');return;}accumulator+=Math.max(0,dt);saveAccumulator+=Math.max(0,dt);while(accumulator+1e-7>=M.STEP&&model.view().status==='playing'){accumulator-=M.STEP;const events=model.advance(M.STEP,currentInput());jumpTap=false;if(events.length)drain(events);}update();if(!paused&&!confirm&&model.view().status==='playing')frame=requestAnimationFrame(loop);if(saveAccumulator>=750)save();}
  function requestLoop(){if(frame===null&&!paused&&!confirm&&model.view().status==='playing'){lastFrame=null;frame=requestAnimationFrame(loop);}}
  listen(el('ccNew'),'click',requestNew);listen(el('ccPause'),'click',()=>paused?resume():pause());listen(el('ccContinue'),'click',()=>{if(confirm)return;const s=model.view().status;if(s==='cleared')nextStage();else if(s==='lost')retry();else if(s==='won')newGame();else resume();});listen(el('ccConfirmYes'),'click',newGame);listen(el('ccConfirmNo'),'click',()=>{confirm=false;paused=pausedBeforeConfirm;update();save();if(paused)el('ccContinue').focus();else{canvas.focus({preventScroll:true});requestLoop();}});
  for(const button of container.querySelectorAll('.cc-dir,.cc-jump')){const action=button.dataset.action;listen(button,'pointerdown',e=>{if(button.disabled||e.button>0)return;e.preventDefault();const id=e.pointerId,owner=`pointer:${id}`;pointers.set(id,{owner,buttonId:button.id,button});held.set(owner,action);suppressedClicks.add(button.id);if(action==='jump')jumpTap=true;unlockAudio();requestLoop();try{button.setPointerCapture?.(id);}catch(_) {}});listen(button,'click',e=>{if(suppressedClicks.has(button.id)&&(e.detail>0||e.pointerType)){suppressedClicks.delete(button.id);return;}if(!e.detail&&!e.pointerType&&!button.disabled){const owner=`tap:${button.id}:${++tapSerial}`;held.set(owner,action);if(action==='jump')jumpTap=true;unlockAudio();requestLoop();setTimeout(()=>held.delete(owner),M.STEP*7);}});listen(button,'lostpointercapture',releasePointer);}
  listen(window,'pointerup',releasePointer);listen(window,'pointercancel',releasePointer);
  const dirs={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'jump',w:'jump',' ':'jump'};
  listen(container,'keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.repeat||e.target.closest?.('input,textarea,select,[contenteditable]'))return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(k==='p'){e.preventDefault();paused?resume():pause();return;}const action=dirs[k];if(!action||paused||confirm||e.target.tagName==='BUTTON'&&(k===' '||k==='Enter'))return;e.preventDefault();const owner=`key:${e.code||k}`;held.set(owner,action);if(action==='jump')jumpTap=true;unlockAudio();requestLoop();});
  listen(window,'keyup',e=>held.delete(`key:${e.code||String(e.key).toLowerCase()}`));listen(window,'blur',()=>pause('Đã tạm dừng khi mất tiêu điểm.'));listen(document,'visibilitychange',()=>{if(document.hidden)pause('Đã tạm dừng khi rời màn chơi.');});listen(window,'pagehide',()=>pause('Đã lưu ván đang chơi.'));
  onCleanup(()=>{cancelAnimationFrame(frame);frame=null;clearInput();save();container.classList.remove('cc-host');alive=false;});
  if(paused){model.advance(0,{});announce('Ván đã lưu. Bấm Chơi tiếp để tiếp tục.');}if(notice)setNotice(notice);update();save();if(!paused&&model.view().status==='playing')frame=requestAnimationFrame(loop);setTimeout(()=>{if(alive)el(paused?'ccContinue':'ccCanvas').focus({preventScroll:true});},0);return{getModel:()=>model,isPaused:()=>paused};
 }
 window.NP_CloudCanopy=Object.freeze({mount});
 if(window.NP_Engines&&typeof window.NP_Engines.launchMario==='function')window.NP_Engines.launchMario=function(container){return mount(container,window.NP_GameSession.start(),window.NP_AudioEngine);};
})();
