/* Original Xe Săn Bụi grid rover interface. */
(function(){
 'use strict';
 const STORAGE='np_scrap_rover_v1',RECOVERY=STORAGE+'_recovery';
 function mount(container,session,audio){
  const M=window.NP_ScrapRoverModel;if(!M)throw new Error('Xe Săn Bụi rules are not ready');
  const{listen,cancelAnimationFrame,onCleanup}=session;
  let raw=null,saved=null,storageOK=true,notice='';try{raw=localStorage.getItem(STORAGE);if(raw)saved=JSON.parse(raw);}catch(_){storageOK=false;notice='Ván này vẫn chơi được.';}
  const future=Number.isInteger(saved?.version)&&saved.version>1;let model=!future&&saved?.version===1?M.restore(saved.game):null;
  if(raw&&!model&&!future){try{const old=localStorage.getItem(RECOVERY);if(old&&old!==raw)storageOK=false;else localStorage.setItem(RECOVERY,raw);}catch(_){storageOK=false;}notice='Bản lưu lỗi được giữ riêng.';}
  if(future){storageOK=false;notice='Bản lưu mới hơn được giữ nguyên.';}
  const restored=Boolean(model);model||=M.create();let alive=true,paused=restored&&model.view().status==='playing',confirm=false,pausedBeforeConfirm=false,raf=null,lastHud='';container.classList.add('rv-host');
  container.innerHTML=`
   <section class="rv-game" aria-label="Xe Săn Bụi">
    <header class="rv-header"><h3>Xe Săn Bụi</h3><div class="rv-toolbar"><button class="rv-button" id="rvNew" type="button" aria-label="Ván mới" title="Ván mới">↻</button><button class="rv-button" id="rvPause" type="button" aria-label="Tạm dừng" title="Tạm dừng">Ⅱ</button></div></header>
    <div class="rv-hud"><div><span>Bãi</span><strong id="rvStage">1 / 3</strong></div><div><span>Drone</span><strong id="rvTargets">0 / 4</strong></div><div><span>Lõi</span><strong id="rvCore">3</strong></div><div><span>Lượt</span><strong id="rvMoves">0 / 36</strong></div></div>
    <div class="rv-board-wrap"><canvas id="rvCanvas" width="400" height="400" role="img" tabindex="0" aria-label="Bản đồ lưới. Dùng phím mũi tên để lái, Space để bắn. D-pad và nút bắn dùng được trên cảm ứng."></canvas></div>
    <div class="rv-controls"><div class="rv-dpad" role="group" aria-label="Lái xe"><span></span><button class="rv-button" id="rvUp" data-dir="0" type="button" aria-label="Lái lên">▲</button><span></span><button class="rv-button" id="rvLeft" data-dir="3" type="button" aria-label="Lái trái">◀</button><button class="rv-button" id="rvDown" data-dir="2" type="button" aria-label="Lái xuống">▼</button><button class="rv-button" id="rvRight" data-dir="1" type="button" aria-label="Lái phải">▶</button></div><button class="rv-button rv-fire" id="rvFire" type="button">Bắn</button></div>
    <p class="np-game-sr" id="rvStatus" role="status" aria-live="polite" aria-atomic="true">Bảo vệ lõi tín hiệu, dọn drone tuần tra.</p><p class="rv-storage" id="rvStorage" hidden role="status"></p>
    <details class="rv-help"><summary aria-label="Cách chơi">?</summary><p>Drone tìm lõi tín hiệu. Mũi tên di chuyển và ngắm; bắn trúng drone cùng hàng hoặc cột. Đá chắn đạn.</p></details>
    <div class="rv-overlay" id="rvOverlay" hidden><div class="rv-overlay-card"><strong id="rvOverlayTitle"></strong><p id="rvOverlayText" hidden></p><div class="rv-confirm" id="rvConfirm" hidden role="group" aria-label="Xác nhận ván mới"><span>Ván mới?</span><button class="rv-button rv-primary" id="rvYes" type="button">Bắt đầu</button><button class="rv-button" id="rvNo" type="button">Ở lại</button></div><button class="rv-button rv-primary" id="rvContinue" type="button">▶</button></div></div>
   </section>`;
  const el=id=>container.querySelector('#'+id),canvas=el('rvCanvas'),ctx=canvas.getContext('2d');
  function announce(text){el('rvStatus').textContent=text;}
  function setNotice(text){if(!text)return;notice=text;el('rvStorage').hidden=false;el('rvStorage').textContent=text;}
  function save(){if(!alive||!storageOK){if(notice)setNotice(notice);return;}try{if(localStorage.getItem(STORAGE)!==raw){storageOK=false;setNotice('Bản lưu đã đổi ở tab khác; ván này không ghi đè.');return;}raw=JSON.stringify({version:1,game:model.serialize()});localStorage.setItem(STORAGE,raw);}catch(_){storageOK=false;setNotice('Không lưu được; ván này vẫn chơi được.');}}
  function sound(kind){if(window.NEWPLAYGROUND_MUTED===true||window.NP_Audio?.isMuted)return;try{if(kind==='kill')audio?.playTone?.(590,'square',.055,.018);else if(kind==='hit')audio?.playTone?.(135,'triangle',.09,.025);}catch(_) {}}
  function drain(){for(const e of model.drain()){sound(e.kind);if(e.kind==='move'&&!e.moved)announce('Tảng đá chắn đường.');else if(e.kind==='kill')announce('Drone tắt máy.');else if(e.kind==='miss')announce('Đạn trượt.');else if(e.kind==='breach')announce(`Drone chạm lõi. Còn ${e.core} lớp.`);else if(e.kind==='cleared')announce('Bãi đã sạch.');else if(e.kind==='won')announce('Ba bãi đã sạch!');else if(e.kind==='lost')announce('Lõi mất hoặc hết lượt.');}}
  function action(type,value){if(!alive||paused||confirm||model.view().status!=='playing')return false;const ok=model.act(type,value);drain();update();save();return ok;}
  function pause(message='Đã tạm dừng.'){if(model.view().status!=='playing')return;paused=true;cancelAnimationFrame(raf);raf=null;update();save();announce(message);el('rvContinue').focus();}
  function resume(){if(!alive||confirm||model.view().status!=='playing'||document.hidden)return;paused=false;update();save();announce('Tiếp tục.');el('rvFire').focus();}
  function newRun(){model=M.create();paused=false;confirm=false;lastHud='';update();save();announce('Ván mới.');el('rvFire').focus();}
  function requestNew(){if(confirm)return;const v=model.view();if(v.status==='playing'&&(v.moves>0||v.stage>0)){pausedBeforeConfirm=paused;confirm=true;paused=true;update();save();el('rvYes').focus();}else newRun();}
  function cell(r,c){return{x:20+c*40,y:20+r*40};}
  function draw(){const v=model.view();ctx.clearRect(0,0,400,400);ctx.fillStyle='#173a4b';ctx.fillRect(0,0,400,400);
   for(let r=0;r<M.ROWS;r++)for(let c=0;c<M.COLS;c++){const p=cell(r,c);ctx.fillStyle=(r+c)%2?'#20495a':'#1d4352';ctx.fillRect(p.x-19,p.y-19,38,38);if(v.map[r][c]==='#'){ctx.fillStyle='#6c7770';ctx.fillRect(p.x-16,p.y-16,32,32);ctx.strokeStyle='#b0b99e';ctx.lineWidth=2;ctx.strokeRect(p.x-16,p.y-16,32,32);ctx.fillStyle='#879187';ctx.fillRect(p.x-10,p.y-8,8,3);ctx.fillRect(p.x+2,p.y+5,9,3);}}
   const base=cell(v.coreCell.r,v.coreCell.c);ctx.fillStyle='#d7ac63';ctx.beginPath();ctx.arc(base.x,base.y,15,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff0c2';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#284c55';ctx.beginPath();ctx.arc(base.x,base.y,6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff0c2';ctx.font='700 9px Calibri, sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(v.core),base.x,base.y+23);
   for(const e of v.enemies){const p=cell(e.r,e.c);ctx.fillStyle='#da8062';ctx.beginPath();ctx.moveTo(p.x,p.y-13);ctx.lineTo(p.x+12,p.y);ctx.lineTo(p.x,p.y+13);ctx.lineTo(p.x-12,p.y);ctx.closePath();ctx.fill();ctx.strokeStyle='#f8e4c3';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#572f39';ctx.fillRect(p.x-3,p.y-3,6,6);}
   const p=cell(v.player.r,v.player.c),d=M.DIRS[v.player.dir];ctx.fillStyle='#5fc1a7';ctx.fillRect(p.x-13,p.y-11,26,22);ctx.fillStyle='#c9f0d9';ctx.fillRect(p.x-7,p.y-6,14,12);ctx.strokeStyle='#a9e0cf';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+d.dc*18,p.y+d.dr*18);ctx.stroke();ctx.fillStyle='#173a4b';ctx.beginPath();ctx.arc(p.x,p.y,3,0,Math.PI*2);ctx.fill();
  }
  function update(){if(!alive)return;const v=model.view(),terminal=v.status!=='playing',stamp=[v.stage,v.score,v.kills,v.core,v.breaches,v.moves,v.status,paused,confirm].join('|');if(stamp!==lastHud){lastHud=stamp;el('rvStage').textContent=`${v.stage+1} / ${M.STAGES.length}`;el('rvTargets').textContent=`${v.kills} / ${v.stageInfo.enemyCount}`;el('rvCore').textContent=String(v.core);el('rvMoves').textContent=`${v.moves} / ${M.MAX_TURNS}`;el('rvPause').disabled=terminal||confirm;el('rvPause').textContent=paused&&!terminal?'▶':'Ⅱ';el('rvPause').setAttribute('aria-label',paused&&!terminal?'Tiếp tục':'Tạm dừng');el('rvOverlay').hidden=!(paused||terminal||confirm);el('rvConfirm').hidden=!confirm;el('rvContinue').hidden=confirm;el('rvOverlayTitle').textContent=confirm?'Ván mới?':v.status==='cleared'?`Bãi ${v.stage+1} sạch!`:v.status==='won'?'Đường đã thông!':v.status==='lost'?'Lõi dừng':'Tạm dừng';el('rvOverlayText').hidden=!terminal;el('rvOverlayText').textContent=terminal?`${v.score} điểm.`:'';el('rvContinue').textContent=v.status==='cleared'?'Bãi tiếp':v.status==='lost'?'Thử lại':v.status==='won'?'Chơi lại':'▶';}draw();}
  for(const[id,dir]of [['rvUp',0],['rvRight',1],['rvDown',2],['rvLeft',3]])listen(el(id),'click',()=>action('move',dir));listen(el('rvFire'),'click',()=>action('fire'));listen(el('rvNew'),'click',requestNew);listen(el('rvPause'),'click',()=>paused?resume():pause());listen(el('rvYes'),'click',newRun);listen(el('rvNo'),'click',()=>{confirm=false;paused=pausedBeforeConfirm;update();save();if(paused)el('rvContinue').focus();else el('rvCanvas').focus();});
  listen(el('rvContinue'),'click',()=>{if(confirm)return;const v=model.view();if(v.status==='cleared'){model=model.next();paused=false;lastHud='';update();save();el('rvCanvas').focus();}else if(v.status==='lost'){model=model.retry();paused=false;lastHud='';update();save();el('rvCanvas').focus();}else if(v.status==='won')newRun();else resume();});
  listen(container,'keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.repeat||e.target.closest?.('input,textarea,select,[contenteditable]'))return;const key=String(e.key).toLowerCase(),dirs={arrowup:0,w:0,arrowright:1,d:1,arrowdown:2,s:2,arrowleft:3,a:3};if(Object.hasOwn(dirs,key)){e.preventDefault();action('move',dirs[key]);}else if((e.code==='Space'||e.key===' ')&&e.target.tagName!=='BUTTON'){e.preventDefault();action('fire');}else if(key==='p'){e.preventDefault();paused?resume():pause();}});
  listen(window,'blur',()=>pause('Đã tạm dừng khi mất tiêu điểm.'));listen(document,'visibilitychange',()=>{if(document.hidden)pause('Đã tạm dừng khi chuyển tab.');});listen(window,'pagehide',()=>pause('Đã lưu ván đang chơi.'));
  onCleanup(()=>{cancelAnimationFrame(raf);raf=null;save();alive=false;container.classList.remove('rv-host');});if(paused)announce('Ván đã lưu. Bấm tiếp tục để chơi.');if(notice)setNotice(notice);update();save();if(!paused)el('rvCanvas').focus({preventScroll:true});return{getModel:()=>model,isPaused:()=>paused};
 }
 window.NP_ScrapRover=Object.freeze({mount});
 if(window.NP_Engines&&typeof window.NP_Engines.launchXeTang1990==='function')window.NP_Engines.launchXeTang1990=function(container){return mount(container,window.NP_GameSession.start(),window.NP_AudioEngine);};
})();
