/* Original Sắc Chuyền interface; concise 1v1 play with an original seasonal deck. */
(function(){
 'use strict';
 const STORAGE='np_season_shed_v1',RECOVERY=STORAGE+'_recovery',SUITS=['spring','summer','autumn','winter'];
 function mount(container,session){
  const M=window.NP_SeasonShedModel;if(!M||!session)throw new Error('Sắc Chuyền rules are not ready');
  const{listen,setTimeout,clearTimeout,onCleanup}=session;
  let raw=null,saved=null,storageOK=true,notice='';try{raw=localStorage.getItem(STORAGE);}catch(_){storageOK=false;notice='Ván này vẫn chơi được.';}
  if(raw){try{saved=JSON.parse(raw);}catch(_){saved=null;}}
  const future=Number.isInteger(saved?.version)&&saved.version>1;
  let model=!future&&saved?.version===1?M.restore(saved.game):null;
  if(raw&&!model&&!future){try{const old=localStorage.getItem(RECOVERY);if(old&&old!==raw)storageOK=false;else localStorage.setItem(RECOVERY,raw);}catch(_){storageOK=false;}notice='Bản lưu lỗi được giữ riêng.';}
  if(future){storageOK=false;notice='Bản lưu mới hơn được giữ nguyên.';}
  const restored=Boolean(model);model||=M.create();let alive=true,paused=restored&&model.view().status==='playing',confirm=false,pausedBeforeConfirm=false,pendingWildId=null,aiTimer=null,lastStamp='';
  container.classList.add('ss-host');
  container.innerHTML=`
   <section class="ss-game" aria-label="Sắc Chuyền">
    <header class="ss-header"><h3>Sắc Chuyền</h3><div class="ss-toolbar"><button class="ss-button" id="ssNew" type="button" aria-label="Ván mới" title="Ván mới">↻</button><button class="ss-button" id="ssPause" type="button" aria-label="Tạm dừng" title="Tạm dừng">Ⅱ</button></div></header>
    <div class="ss-rivals"><div><span>Đối thủ</span><strong id="ssOpponentCount">6</strong><div class="ss-backs" aria-hidden="true">▰ ▰ ▰</div></div><div class="ss-table"><span class="ss-pile-label">Lượt</span><div class="ss-top-card" id="ssTopCard" data-suit="spring" aria-live="polite"></div><div class="ss-suit-now" id="ssSuitNow"></div></div><div><span>Rút</span><button class="ss-button ss-draw-pile" id="ssDraw" type="button" aria-label="Rút một lá">＋<small id="ssDrawCount">63</small></button></div></div>
    <p class="ss-status" id="ssStatus" role="status" aria-live="polite" aria-atomic="true">Ghép biểu tượng hoặc số.</p>
    <div class="ss-hand-wrap"><div class="ss-hand-heading"><strong>Bạn</strong><span id="ssHandCount">6 lá</span></div><div class="ss-hand" id="ssHand" role="group" aria-label="Lá bài trên tay"></div></div>
    <div class="ss-actions"><button class="ss-button" id="ssPass" type="button" hidden>Bỏ lượt</button></div>
    <div class="ss-wild" id="ssWildChoices" hidden><div class="ss-wild-head"><span>Chọn mùa</span><button class="ss-button" id="ssWildCancel" type="button" aria-label="Hủy chọn lá">↩</button></div><div class="ss-suit-choices"><button class="ss-button ss-season" data-suit="spring" type="button" aria-label="Lá non">✿</button><button class="ss-button ss-season" data-suit="summer" type="button" aria-label="Nắng">☼</button><button class="ss-button ss-season" data-suit="autumn" type="button" aria-label="Lá thu">❋</button><button class="ss-button ss-season" data-suit="winter" type="button" aria-label="Băng">❄</button></div></div>
    <p class="np-game-sr" id="ssAnnounce" role="status" aria-live="polite" aria-atomic="true"></p><p class="ss-storage" id="ssStorage" hidden role="status"></p>
    <details class="ss-help"><summary aria-label="Cách chơi">?</summary><p>Ghép mùa hoặc số. Gió khiến đối thủ rút hai lá; giọt sương đổi mùa.</p></details>
    <div class="ss-overlay" id="ssOverlay" hidden><div class="ss-overlay-card"><strong id="ssOverlayTitle"></strong><p id="ssOverlayText" hidden></p><div class="ss-confirm" id="ssConfirm" hidden role="group" aria-label="Xác nhận ván mới"><span>Ván mới?</span><button class="ss-button ss-primary" id="ssConfirmYes" type="button">Bắt đầu</button><button class="ss-button" id="ssConfirmNo" type="button">Ở lại</button></div><button class="ss-button ss-primary" id="ssContinue" type="button">▶</button></div></div>
   </section>`;
  const el=id=>container.querySelector('#'+id);
  function announce(text){el('ssAnnounce').textContent=text;}
  function setNotice(text){if(!text)return;notice=text;el('ssStorage').hidden=false;el('ssStorage').textContent=text;}
  function save(){if(!alive||!storageOK){if(notice)setNotice(notice);return;}try{if(localStorage.getItem(STORAGE)!==raw){storageOK=false;setNotice('Bản lưu đã đổi ở tab khác; ván này không ghi đè.');return;}raw=JSON.stringify({version:1,game:model.serialize()});localStorage.setItem(STORAGE,raw);}catch(_){storageOK=false;setNotice('Không lưu được; ván này vẫn chơi được.');}}
  function clearAI(){if(aiTimer!==null){clearTimeout(aiTimer);aiTimer=null;}}
  function scheduleAI(){clearAI();if(!alive||paused||confirm||model.view().status!=='playing'||model.view().phase!=='ai')return;aiTimer=setTimeout(()=>{aiTimer=null;if(!alive||paused||confirm)return;const events=model.advanceAI();drain(events);update();save();scheduleAI();},420);}
  function drain(events){for(const e of events||[]){if(e.kind==='blocked')announce(e.reason==='choose-suit'?'Chọn một mùa.':'Lá đó chưa khớp.');else if(e.kind==='drawn-playable')announce('Lá vừa rút có thể đánh.');else if(e.kind==='drawn-pass')announce('Lá đã rút; lượt đối thủ.');else if(e.kind==='gust')announce('Gió đưa hai lá sang đối thủ.');else if(e.kind==='pass')announce('Lượt đối thủ.');else if(e.kind==='finish')announce(e.winner===0?'Bạn thắng ván!':'Đối thủ thắng ván.');}if(events?.length)update();}
  function act(action,value){if(!alive||paused||confirm||model.view().status!=='playing')return false;const ok=model.act(action,value);drain(model.drain());update();save();scheduleAI();return ok;}
  function playCard(id){const c=M.CARDS.find(x=>x.id===id);if(!c)return;if(c.kind==='dew'){pendingWildId=id;update();announce('Chọn một mùa.');return;}act('play',id);}
  function playWild(suit){if(!pendingWildId||!SUITS.includes(suit))return;const id=pendingWildId;pendingWildId=null;act('play',{cardId:id,suit});}
  function pause(message='Đã tạm dừng.'){if(model.view().status!=='playing')return;paused=true;pendingWildId=null;clearAI();update();save();announce(message);el('ssContinue').focus();}
  function resume(){if(!alive||confirm||model.view().status!=='playing'||document.hidden)return;paused=false;update();save();announce('Tiếp tục.');scheduleAI();el('ssDraw').focus();}
  function newRun(){clearAI();model=M.create();paused=false;confirm=false;pendingWildId=null;update();save();announce('Ván mới.');el('ssDraw').focus();}
  function requestNew(){if(confirm)return;const v=model.view(),progressed=v.hand.length!==6||v.discardCount>1||v.phase!=='player';if(v.status==='playing'&&progressed){pausedBeforeConfirm=paused;confirm=true;paused=true;pendingWildId=null;clearAI();update();save();el('ssConfirmYes').focus();}else newRun();}
  function renderHand(v){el('ssHandCount').textContent=`${v.hand.length} lá`;el('ssOpponentCount').textContent=String(v.opponentCount);el('ssDrawCount').textContent=String(v.drawCount);el('ssTopCard').dataset.suit=v.topCard.kind==='dew'?v.activeSuit:v.topCard.suit;el('ssTopCard').textContent=v.topCard.kind==='dew'?`◉ ${v.suitInfo[v.activeSuit].symbol}`:v.topCard.kind==='gust'?`${v.suitInfo[v.topCard.suit].symbol} ↝`: `${v.suitInfo[v.topCard.suit].symbol} ${v.topCard.value}`;el('ssSuitNow').textContent=`Mùa ${v.suitInfo[v.activeSuit].name}`;
   const legal=new Set(v.playableIds);el('ssHand').innerHTML=v.hand.map(c=>{const label=c.kind==='dew'?'Giọt sương, đổi mùa':c.kind==='gust'?`${v.suitInfo[c.suit].name}, gió rút hai lá`:`${v.suitInfo[c.suit].name}, số ${c.value}`,enabled=!paused&&!confirm&&v.phase!=='ai'&&v.status==='playing'&&legal.has(c.id)&&(!pendingWildId||pendingWildId===c.id);return`<button class="ss-card" id="ssCard-${c.id}" data-card-id="${c.id}" data-suit="${c.suit||'dew'}" data-kind="${c.kind}" type="button" aria-label="${label}${enabled?', có thể đánh':''}" aria-disabled="${!enabled}" ${enabled?'':'disabled'}>${c.kind==='dew'?'◉':c.kind==='gust'?`↝ ${v.suitInfo[c.suit].symbol}`:`${v.suitInfo[c.suit].symbol} ${c.value}`}</button>`;}).join('');
   const canDraw=!paused&&!confirm&&v.status==='playing'&&v.phase==='player',canPass=!paused&&!confirm&&v.status==='playing'&&v.phase==='player-drawn';el('ssDraw').disabled=!canDraw;el('ssPass').hidden=!canPass;el('ssPass').disabled=!canPass;el('ssWildChoices').hidden=!pendingWildId||paused||confirm;}
  function update(){if(!alive)return;const v=model.view(),terminal=v.status!=='playing',stamp=[v.status,v.phase,v.winner,paused,confirm,pendingWildId,v.activeSuit,v.topCard.id,v.opponentCount,v.drawCount,v.hand.map(c=>c.id).join(','),v.playableIds.join(',')].join('|');if(stamp===lastStamp)return;lastStamp=stamp;renderHand(v);el('ssPause').disabled=terminal||confirm;el('ssPause').textContent=paused&&!terminal?'▶':'Ⅱ';el('ssPause').setAttribute('aria-label',paused&&!terminal?'Tiếp tục':'Tạm dừng');el('ssOverlay').hidden=!(paused||terminal||confirm);el('ssConfirm').hidden=!confirm;el('ssContinue').hidden=confirm;el('ssOverlayTitle').textContent=confirm?'Ván mới?':v.status==='won'?'Bạn thắng!':v.status==='lost'?'Đối thủ thắng':'Tạm dừng';el('ssOverlayText').hidden=!terminal;el('ssOverlayText').textContent=terminal?'Sắc Chuyền · một ván nhanh.':'';el('ssContinue').textContent=terminal?'Chơi lại':'▶';el('ssContinue').setAttribute('aria-label',terminal?'Chơi lại':'Tiếp tục');}
  listen(el('ssHand'),'click',e=>{const id=e.target?.dataset?.cardId;if(id)playCard(id);});listen(el('ssDraw'),'click',()=>act('draw'));listen(el('ssPass'),'click',()=>act('pass'));for(const b of container.querySelectorAll('.ss-season'))listen(b,'click',()=>playWild(b.dataset.suit));listen(el('ssWildCancel'),'click',()=>{pendingWildId=null;update();});
  listen(el('ssNew'),'click',requestNew);listen(el('ssPause'),'click',()=>paused?resume():pause());listen(el('ssConfirmYes'),'click',newRun);listen(el('ssConfirmNo'),'click',()=>{confirm=false;paused=pausedBeforeConfirm;update();save();if(paused)el('ssContinue').focus();else scheduleAI();});listen(el('ssContinue'),'click',()=>{if(confirm)return;if(model.view().status!=='playing')newRun();else resume();});
  listen(container,'keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.repeat||e.target.closest?.('input,textarea,select,[contenteditable]'))return;if(String(e.key).toLowerCase()==='p'){e.preventDefault();paused?resume():pause();}});listen(window,'blur',()=>pause('Đã tạm dừng khi mất tiêu điểm.'));listen(document,'visibilitychange',()=>{if(document.hidden)pause('Đã tạm dừng khi chuyển tab.');});listen(window,'pagehide',()=>pause('Đã lưu ván đang chơi.'));
  onCleanup(()=>{clearAI();save();container.classList.remove('ss-host');alive=false;});if(paused)announce('Ván đã lưu. Bấm tiếp tục để chơi.');if(notice)setNotice(notice);update();save();if(!paused)scheduleAI();setTimeout(()=>{if(alive)el(paused?'ssContinue':'ssDraw').focus({preventScroll:true});},0);return{getModel:()=>model,isPaused:()=>paused};
 }
 window.NP_SeasonShed=Object.freeze({mount});
 if(window.NP_Engines&&typeof window.NP_Engines.launchDanhBaiUno==='function')window.NP_Engines.launchDanhBaiUno=function(container){return mount(container,window.NP_GameSession.start());};
})();
