/* Original Mảnh Sao constellation-shooter interface. */
(function(){
 'use strict';
 const STORAGE='np_starlight_match_v1',RECOVERY=STORAGE+'_recovery';
 function mount(container,session,audio){
  const M=window.NP_StarlightMatchModel;if(!M||!session)throw new Error('Mảnh Sao rules are not ready');
  const{listen,requestAnimationFrame,cancelAnimationFrame,setTimeout,onCleanup}=session;
  let raw=null,saved=null,storageOK=true,notice='';try{raw=localStorage.getItem(STORAGE);if(raw)saved=JSON.parse(raw);}catch(_){storageOK=false;notice='Ván này vẫn chơi được.';}
  const future=Number.isInteger(saved?.version)&&saved.version>1;let model=!future&&saved?.version===1?M.restore(saved.game):null;
  if(raw&&!model&&!future){try{const old=localStorage.getItem(RECOVERY);if(old&&old!==raw)storageOK=false;else localStorage.setItem(RECOVERY,raw);}catch(_){storageOK=false;}notice='Bản lưu lỗi được giữ riêng.';}
  if(future){storageOK=false;notice='Bản lưu mới hơn được giữ nguyên.';}
  const restored=Boolean(model);model||=M.create();let alive=true,paused=restored&&model.view().status==='playing',confirm=false,pausedBeforeConfirm=false,frame=null,lastFrame=null,accumulator=0,saveAccumulator=0,lastHud='';
  const COLORS=['#df7d68','#77a98e','#a08bc7','#6b9bbc','#d3a451'];container.classList.add('sm-host');container.innerHTML=`
   <section class="sm-game" aria-label="Mảnh Sao">
    <header class="sm-header"><h3>Mảnh Sao</h3><div class="sm-toolbar"><button class="sm-button" id="smNew" type="button" aria-label="Ván mới" title="Ván mới">↻</button><button class="sm-button" id="smPause" type="button" aria-label="Tạm dừng" title="Tạm dừng">Ⅱ</button></div></header>
    <div class="sm-hud"><div><span>Chòm</span><strong id="smStage">1 / 3</strong></div><div><span>Mảnh</span><strong id="smCount">0</strong></div><div><span>Rơi</span><strong id="smPressure">0 / 4</strong></div><div><span>Điểm</span><strong id="smScore">0</strong></div></div>
    <div class="sm-canvas-wrap"><canvas id="smCanvas" width="640" height="640" role="img" tabindex="0" aria-label="Bảng mảnh sao; nối cụm cùng biểu tượng, dùng mũi tên để ngắm và Space để bắn."></canvas></div>
    <div class="sm-controls"><div class="sm-aim"><button class="sm-button" id="smAimLeft" type="button" aria-label="Ngắm trái">◀</button><button class="sm-button" id="smAimRight" type="button" aria-label="Ngắm phải">▶</button></div><span id="smAimLabel">Ngắm</span><button class="sm-button sm-fire" id="smFire" type="button">Bắn</button></div>
    <p class="np-game-sr" id="smStatus" role="status" aria-live="polite" aria-atomic="true">Nối ba mảnh cùng biểu tượng.</p><p class="sm-storage" id="smStorage" hidden role="status"></p>
    <details class="sm-help"><summary aria-label="Cách chơi">?</summary><p>Ngắm rồi bắn. Nối ba mảnh cùng loại; mảnh không còn bám sẽ rơi. Bốn lượt trượt đẩy triều lên.</p></details>
    <div class="sm-overlay" id="smOverlay" hidden><div class="sm-overlay-card"><strong id="smOverlayTitle"></strong><p id="smOverlayText" hidden></p><div class="sm-confirm" id="smConfirm" hidden role="group" aria-label="Xác nhận ván mới"><span>Ván mới?</span><button class="sm-button sm-primary" id="smConfirmYes" type="button">Bắt đầu</button><button class="sm-button" id="smConfirmNo" type="button">Ở lại</button></div><button class="sm-button sm-primary" id="smContinue" type="button">▶</button></div></div>
   </section>`;
  const el=id=>container.querySelector('#'+id),canvas=el('smCanvas'),ctx=canvas.getContext('2d');
  function announce(text){el('smStatus').textContent=text;}
  function setNotice(text){if(!text)return;notice=text;el('smStorage').hidden=false;el('smStorage').textContent=text;}
  function save(){if(!alive||!storageOK){if(notice)setNotice(notice);return;}try{if(localStorage.getItem(STORAGE)!==raw){storageOK=false;setNotice('Bản lưu đã đổi ở tab khác; ván này không ghi đè.');return;}raw=JSON.stringify({version:1,game:model.serialize()});localStorage.setItem(STORAGE,raw);}catch(_){storageOK=false;setNotice('Không lưu được; ván này vẫn chơi được.');}}
  function sound(kind){if(window.NEWPLAYGROUND_MUTED===true||window.NP_Audio?.isMuted)return;try{if(kind==='pop')audio?.playTone?.(600,'sine',.045,.018);else if(kind==='push')audio?.playTone?.(160,'triangle',.07,.02);}catch(_) {}}
  function drain(events){for(const e of events||[]){sound(e.kind);if(e.kind==='pop')announce('Cụm tan; mảnh rời cũng rơi.');else if(e.kind==='miss')announce(`Lượt trượt ${e.count} / ${M.MISS_LIMIT}.`);else if(e.kind==='push')announce('Triều đẩy mảnh xuống.');else if(e.kind==='cleared')announce('Chòm đã sáng!');else if(e.kind==='lost')announce('Mảnh đã chạm vùng nguy hiểm.');else if(e.kind==='won')announce('Bầu trời đã thông!');}if(events?.length){update();save();}}
  function action(name,value){if(!alive||paused||confirm||model.view().status!=='playing')return false;const ok=model.act(name,value);drain(model.drain());update();if(name!=='aim')save();return ok;}
  function launch(){return action('fire');}
  function pause(message='Đã tạm dừng.'){if(model.view().status!=='playing')return;paused=true;accumulator=0;lastFrame=null;cancelAnimationFrame(frame);frame=null;update();save();announce(message);el('smContinue').focus();}
  function schedule(){if(!alive||paused||confirm||model.view().status!=='playing'||frame!==null)return;frame=requestAnimationFrame(loop);}
  function resume(){if(!alive||confirm||model.view().status!=='playing'||document.hidden)return;paused=false;accumulator=0;lastFrame=null;update();save();announce('Tiếp tục.');el('smFire').focus();schedule();}
  function newRun(){cancelAnimationFrame(frame);frame=null;model=M.create();paused=false;confirm=false;accumulator=0;lastFrame=null;update();save();announce('Ván mới.');el('smFire').focus();schedule();}
  function requestNew(){if(confirm)return;const v=model.view(),progressed=v.shots>0||v.pressureRows>0||v.stage>0;if(v.status==='playing'&&progressed){pausedBeforeConfirm=paused;confirm=true;paused=true;cancelAnimationFrame(frame);frame=null;update();save();el('smConfirmYes').focus();}else newRun();}
  function cellPoint(r,c){return{x:M.X0+c*M.X_STEP+(r%2?M.X_STEP/2:0),y:M.Y0+r*M.ROW_STEP};}
  function drawOrb(x,y,color,r=M.CELL_RADIUS){ctx.fillStyle=COLORS[color];ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#edf4df';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#ffffe8';ctx.font='700 17px Calibri, sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(M.COLORS[color].symbol,x,y+1);}
  function aimFromPoint(clientX,clientY){const rect=canvas.getBoundingClientRect(),sx=canvas.width/rect.width,sy=canvas.height/rect.height,x=(clientX-rect.left)*sx,y=(clientY-rect.top)*sy,angle=Math.atan2(x-M.SHOOTER.x,M.SHOOTER.y-y);action('aim',angle);}
  function draw(){const v=model.view(),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const bg=ctx.createLinearGradient(0,0,0,h);bg.addColorStop(0,'#152f57');bg.addColorStop(.58,'#234f71');bg.addColorStop(1,'#152f48');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);
   ctx.fillStyle='#1e4163';ctx.beginPath();ctx.ellipse(w/2,530,290,90,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#6794a4';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(w/2,530,290,90,0,Math.PI,Math.PI*2);ctx.stroke();
   for(let r=0;r<M.ROWS;r++)for(let c=0;c<M.COLS;c++){const color=v.board[r][c];if(color===null)continue;const p=cellPoint(r,c);drawOrb(p.x,p.y,color);}
   ctx.fillStyle='#d7e5c9';ctx.font='700 12px Calibri, sans-serif';ctx.textAlign='center';ctx.fillText('VÙNG AN TOÀN',w/2,510);ctx.strokeStyle='#dbb486';ctx.setLineDash([6,6]);ctx.beginPath();ctx.moveTo(100,490);ctx.lineTo(540,490);ctx.stroke();ctx.setLineDash([]);
   const bubble=v.projectile;
   if(bubble){drawOrb(bubble.x,bubble.y,bubble.color);}
   else{const dx=Math.sin(v.angle),dy=-Math.cos(v.angle),x=M.SHOOTER.x+dx*150,y=M.SHOOTER.y+dy*150;ctx.strokeStyle='#f7e8b4';ctx.lineWidth=2;ctx.setLineDash([8,8]);ctx.beginPath();ctx.moveTo(M.SHOOTER.x,M.SHOOTER.y);ctx.lineTo(x,y);ctx.stroke();ctx.setLineDash([]);drawOrb(M.SHOOTER.x,M.SHOOTER.y-10,v.currentColor,19);drawOrb(M.SHOOTER.x+47,M.SHOOTER.y-8,v.nextColor,13);}
   ctx.fillStyle='#f3efd8';ctx.beginPath();ctx.arc(M.SHOOTER.x,M.SHOOTER.y+14,29,Math.PI,0);ctx.fill();ctx.fillStyle='#d4c7a3';ctx.fillRect(M.SHOOTER.x-35,M.SHOOTER.y+14,70,16);
  }
  function update(){if(!alive)return;const v=model.view(),terminal=v.status!=='playing',stamp=[v.stage,v.score,v.phase,v.status,v.pressureRows,v.shots,v.angle,paused,confirm].join('|');if(stamp!==lastHud){lastHud=stamp;el('smStage').textContent=`${v.stage+1} / ${M.STAGES.length}`;el('smCount').textContent=String(v.board.flat().filter(x=>x!==null).length);el('smPressure').textContent=`${v.misses} / ${M.MISS_LIMIT}`;el('smScore').textContent=String(v.score);el('smAimLabel').textContent=`${Math.round(v.angle*180/Math.PI)}°`;el('smPause').disabled=terminal||confirm;el('smPause').textContent=paused&&!terminal?'▶':'Ⅱ';el('smPause').setAttribute('aria-label',paused&&!terminal?'Tiếp tục':'Tạm dừng');el('smFire').disabled=paused||confirm||terminal||v.phase!=='aim';el('smOverlay').hidden=!(paused||terminal||confirm);el('smConfirm').hidden=!confirm;el('smContinue').hidden=confirm;el('smOverlayTitle').textContent=confirm?'Ván mới?':v.status==='cleared'?`Chòm ${v.stage+1} sáng!`:v.status==='won'?'Bầu trời đã thông!':v.status==='lost'?'Triều đã dâng':'Tạm dừng';el('smOverlayText').hidden=!terminal;el('smOverlayText').textContent=terminal?`${v.score} điểm.`:'';el('smContinue').textContent=v.status==='cleared'?'Chòm tiếp':v.status==='lost'?'Thử lại':v.status==='won'?'Chơi lại':'▶';}draw();}
  function loop(ts){frame=null;if(!alive||paused||confirm||model.view().status!=='playing')return;const dt=lastFrame===null?0:ts-lastFrame;lastFrame=ts;if(dt>250){pause('Đã tạm dừng sau khi rời màn hình.');return;}accumulator+=Math.max(0,dt);saveAccumulator+=Math.max(0,dt);while(accumulator+1e-7>=M.STEP&&model.view().status==='playing'){accumulator-=M.STEP;drain(model.advance(M.STEP));}update();if(!paused&&!confirm&&model.view().status==='playing')schedule();if(saveAccumulator>=750){saveAccumulator=0;save();}}
  listen(el('smFire'),'click',launch);listen(el('smAimLeft'),'click',()=>action('aim',model.view().angle-.14));listen(el('smAimRight'),'click',()=>action('aim',model.view().angle+.14));listen(canvas,'pointermove',e=>aimFromPoint(e.clientX,e.clientY));listen(canvas,'pointerdown',e=>aimFromPoint(e.clientX,e.clientY));listen(el('smNew'),'click',requestNew);listen(el('smPause'),'click',()=>paused?resume():pause());listen(el('smConfirmYes'),'click',newRun);listen(el('smConfirmNo'),'click',()=>{confirm=false;paused=pausedBeforeConfirm;accumulator=0;lastFrame=null;update();save();if(paused)el('smContinue').focus();else schedule();});listen(el('smContinue'),'click',()=>{if(confirm)return;const v=model.view();if(v.status==='cleared'){model=model.next();paused=false;accumulator=0;lastFrame=null;lastHud='';update();save();schedule();}else if(v.status==='lost'){model=model.retry();paused=false;accumulator=0;lastFrame=null;lastHud='';update();save();schedule();}else if(v.status==='won')newRun();else resume();});
  listen(container,'keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.repeat||e.target.closest?.('input,textarea,select,[contenteditable]'))return;if(e.code==='Space'&&e.target.tagName!=='BUTTON'){e.preventDefault();launch();}else if(e.key==='ArrowLeft'){e.preventDefault();action('aim',model.view().angle-.1);}else if(e.key==='ArrowRight'){e.preventDefault();action('aim',model.view().angle+.1);}else if(String(e.key).toLowerCase()==='p'){e.preventDefault();paused?resume():pause();}});listen(window,'blur',()=>pause('Đã tạm dừng khi mất tiêu điểm.'));listen(document,'visibilitychange',()=>{if(document.hidden)pause('Đã tạm dừng khi chuyển tab.');});listen(window,'pagehide',()=>pause('Đã lưu ván đang chơi.'));
  onCleanup(()=>{cancelAnimationFrame(frame);frame=null;save();container.classList.remove('sm-host');alive=false;});if(paused)announce('Ván đã lưu. Bấm tiếp tục để chơi.');if(notice)setNotice(notice);update();save();if(!paused&&model.view().status==='playing')schedule();setTimeout(()=>{if(alive)el(paused?'smContinue':'smFire').focus({preventScroll:true});},0);return{getModel:()=>model,isPaused:()=>paused};
 }
 window.NP_StarlightMatch=Object.freeze({mount});
 if(window.NP_Engines&&typeof window.NP_Engines.launchBanTrung==='function')window.NP_Engines.launchBanTrung=function(container){return mount(container,window.NP_GameSession.start(),window.NP_AudioEngine);};
})();
