/* Original Tiệm Lá Trà time-management loop. */
(function(){
 'use strict';
 const STORAGE='np_tea_service_v1',RECOVERY=STORAGE+'_recovery';
 function mount(container,session,audio){
  const M=window.NP_TeaServiceModel;if(!M||!session)throw new Error('Tiệm Lá Trà rules are not ready');
  const{listen,requestAnimationFrame,cancelAnimationFrame,setTimeout,onCleanup}=session;
  let raw=null,saved=null,storageOK=true,notice='';try{raw=localStorage.getItem(STORAGE);}catch(_){storageOK=false;notice='Ca này vẫn chơi được.';}
  if(raw){try{saved=JSON.parse(raw);}catch(_){saved=null;}}
  const future=Number.isInteger(saved?.version)&&saved.version>1||Number.isInteger(saved?.game?.version)&&saved.game.version>1;
  let model=!future&&saved?.version===1&&Number.isSafeInteger(saved.best)&&saved.best>=0?M.restore(saved.game):null;
  if(raw&&!model&&!future){try{const old=localStorage.getItem(RECOVERY);if(old&&old!==raw)storageOK=false;else localStorage.setItem(RECOVERY,raw);}catch(_){storageOK=false;}notice='Bản lưu lỗi được giữ riêng.';}
  if(future){storageOK=false;notice='Bản lưu mới hơn được giữ nguyên.';}
  const restored=Boolean(model);model||=M.create();let best=restored?saved.best:0,alive=true,paused=restored&&model.view().status==='playing',confirm=false,pausedBeforeConfirm=false;
  let frame=null,lastFrame=null,accumulator=0,saveAccumulator=0,lastHUD='',userGesture=false;
  container.classList.add('ts-host');
  container.innerHTML=`
   <section class="ts-game" aria-label="Tiệm Lá Trà">
    <header class="ts-header"><div><span class="ts-kicker">PHỤC VỤ MỘT CA NHẸ NHÀNG</span><h3>Tiệm Lá Trà</h3></div><div class="ts-toolbar"><button class="ts-button" id="tsNew" type="button" aria-label="Ca mới" title="Ca mới">↻</button><button class="ts-button" id="tsPause" type="button" aria-label="Tạm dừng" title="Tạm dừng">Ⅱ</button></div></header>
    <div class="ts-hud"><div><span>Ca</span><strong id="tsShift">1 / 3</strong></div><div><span>Điểm</span><strong id="tsScore">0 / 320</strong></div><div><span>Chờ</span><strong id="tsWaiting">0</strong></div><div><span>Còn</span><strong id="tsTime">0:30</strong></div></div>
    <div class="ts-service">
     <section class="ts-panel" aria-label="Khách đang chờ"><h4>Khách</h4><div class="ts-queue">
      <button class="ts-button ts-guest" id="tsGuest0" type="button"><span class="ts-face" id="tsGuest0Face"></span><span class="ts-party" id="tsGuest0Party"></span><span class="ts-patience"><i id="tsGuest0Patience"></i></span></button>
      <button class="ts-button ts-guest" id="tsGuest1" type="button"><span class="ts-face" id="tsGuest1Face"></span><span class="ts-party" id="tsGuest1Party"></span><span class="ts-patience"><i id="tsGuest1Patience"></i></span></button>
      <button class="ts-button ts-guest" id="tsGuest2" type="button"><span class="ts-face" id="tsGuest2Face"></span><span class="ts-party" id="tsGuest2Party"></span><span class="ts-patience"><i id="tsGuest2Patience"></i></span></button>
     </div><p class="ts-kitchen-note" id="tsQueueMore"></p></section>
     <section class="ts-panel" aria-label="Bếp"><h4>Bếp</h4><button class="ts-button ts-kitchen-action" id="tsKitchen" type="button">Bếp sẵn</button><p class="ts-kitchen-note" id="tsKitchenNote">Đơn vào bếp theo thứ tự.</p></section>
    </div>
    <div class="ts-tables" role="group" aria-label="Các bàn trong tiệm"><button class="ts-button ts-table" id="tsTable0" data-state="empty" type="button"><strong>Bàn 1</strong><span id="tsTable0State"></span></button><button class="ts-button ts-table" id="tsTable1" data-state="empty" type="button"><strong>Bàn 2</strong><span id="tsTable1State"></span></button><button class="ts-button ts-table" id="tsTable2" data-state="empty" type="button"><strong>Bàn 3</strong><span id="tsTable2State"></span></button></div>
    <p class="np-game-sr" id="tsStatus" role="status" aria-live="polite" aria-atomic="true">Chọn khách, xếp bàn, nhận đơn rồi giao món.</p><p class="ts-storage" id="tsStorage" hidden role="status"></p>
    <details class="ts-help"><summary aria-label="Cách chơi">?</summary><p>Chọn khách, xếp bàn, lấy món ở bếp rồi giao tới bàn.</p></details>
    <div class="ts-overlay" id="tsOverlay" hidden><div class="ts-card"><strong id="tsOverlayTitle"></strong><p id="tsOverlayText" hidden></p><div class="ts-confirm" id="tsConfirm" hidden role="group" aria-label="Xác nhận ca mới"><span>Ca mới?</span><button class="ts-button ts-primary" id="tsConfirmYes" type="button">Bắt đầu</button><button class="ts-button" id="tsConfirmNo" type="button">Ở lại</button></div><button class="ts-button ts-primary" id="tsContinue" type="button">▶</button></div></div>
   </section>`;
  const el=id=>container.querySelector('#'+id);
  function setNotice(text){if(!text)return;notice=text;el('tsStorage').hidden=false;el('tsStorage').textContent=text;}
  function save(){saveAccumulator=0;if(!alive||!storageOK){if(notice)setNotice(notice);return;}const v=model.view();best=Math.max(best,v.score);try{if(localStorage.getItem(STORAGE)!==raw){storageOK=false;setNotice('Bản lưu đã đổi ở tab khác; ca này không ghi đè.');return;}raw=JSON.stringify({version:1,best,game:model.serialize()});localStorage.setItem(STORAGE,raw);}catch(_){storageOK=false;setNotice('Không lưu được; ca này vẫn chơi được.');}}
  function announce(text){el('tsStatus').textContent=text;}
  function unlockAudio(){userGesture=true;if(window.NEWPLAYGROUND_MUTED===true||window.NP_Audio?.isMuted)return;try{audio?.init?.();if(audio?.ctx?.state==='suspended')audio.ctx.resume()?.catch?.(()=>{});}catch(_) {}}
  function sound(kind){if(!userGesture||window.NEWPLAYGROUND_MUTED===true||window.NP_Audio?.isMuted)return;const pitch={arrive:380,seat:420,order:500,ready:650,pickup:560,serve:590,payment:760,clear:340,leave:180,cleared:680,won:820,lost:130}[kind];if(!pitch)return;try{audio?.playTone?.(pitch,kind==='leave'||kind==='lost'?'triangle':'sine',.055,.022);}catch(_) {}}
  function drain(events){for(const e of events||[])sound(e.kind);for(const e of events||[]){if(e.kind==='blocked'){announce(e.reason==='capacity'?'Bàn không đủ chỗ.':e.reason==='choose-customer'?'Chọn khách trước.':'Món chưa sẵn.');}else if(e.kind==='leave')announce('Khách đã rời vì chờ lâu.');else if(e.kind==='payment')announce('Khách xong, bàn đã sẵn.');else if(e.kind==='cleared')announce('Ca hoàn thành!');else if(e.kind==='won')announce('Tiệm đã qua cả ba ca!');else if(e.kind==='lost')announce('Chưa đạt mục tiêu ca.');}if(events?.length){update();save();}}
  function pause(message='Đã tạm dừng.'){if(model.view().status!=='playing')return;paused=true;accumulator=0;lastFrame=null;cancelAnimationFrame(frame);frame=null;update();save();announce(message);el('tsContinue').focus();}
  function resume(){if(!alive||confirm||model.view().status!=='playing'||document.hidden)return;unlockAudio();paused=false;accumulator=0;lastFrame=null;update();save();el('tsKitchen').focus();if(frame===null)frame=requestAnimationFrame(loop);announce('Chơi tiếp.');}
  function newRun(){cancelAnimationFrame(frame);frame=null;model=M.create();paused=false;confirm=false;accumulator=0;lastFrame=null;el('tsConfirm').hidden=true;update();save();announce('Ca mới.');el('tsGuest0').focus();frame=requestAnimationFrame(loop);}
  function retry(){const next=model.retry();if(!next)return newRun();cancelAnimationFrame(frame);frame=null;model=next;paused=false;confirm=false;accumulator=0;lastFrame=null;update();save();announce('Thử lại ca này.');frame=requestAnimationFrame(loop);}
  function nextShift(){const next=model.next();if(!next)return;model=next;paused=false;confirm=false;accumulator=0;lastFrame=null;update();save();announce(`Bắt đầu ca ${model.view().shift+1}.`);frame=requestAnimationFrame(loop);}
  function requestNew(){const v=model.view(),progressed=v.ticks>0||v.score>v.bankScore||v.shift>0||v.customers.length>0;if(v.status==='playing'&&progressed){pausedBeforeConfirm=paused;confirm=true;paused=true;cancelAnimationFrame(frame);frame=null;el('tsConfirm').hidden=false;update();save();el('tsConfirmYes').focus();}else newRun();}
  function action(type,index){if(!alive||paused||confirm||model.view().status!=='playing')return false;unlockAudio();const ok=model.act(type,index);drain(model.drain());update();save();return ok;}
  function recipeName(index){return M.RECIPES[index]?.name||'Món';}
  function renderQueue(v){const guests=v.queue.slice(0,3);for(let i=0;i<3;i++){const b=el('tsGuest'+i),c=guests[i];b.hidden=!c;b.disabled=paused||confirm||v.status!=='playing'||!c;if(!c)continue;b.dataset.customerId=String(c.id);b.setAttribute('aria-pressed',String(v.selectedCustomerId===c.id));b.setAttribute('aria-label',`Nhóm ${c.size} người, gọi ${recipeName(c.recipe)}, còn ${c.patience} nhịp`);el(`tsGuest${i}Face`).textContent=['●','◆','✦'][c.recipe];el(`tsGuest${i}Party`).innerHTML=`${c.size} người<span class="ts-recipe">${recipeName(c.recipe)}</span>`;el(`tsGuest${i}Patience`).style.width=`${Math.max(0,Math.round(c.patience/c.maxPatience*100))}%`;}el('tsQueueMore').textContent=v.queue.length>3?`+${v.queue.length-3} nhóm nữa`:v.queue.length?`Đang chờ: ${v.queue.length}`:'Chưa có khách.';}
  function renderKitchen(v){const ready=v.tickets.find(x=>x.status==='ready'),held=v.heldTicket,cooking=v.cooking;const b=el('tsKitchen');b.disabled=paused||confirm||v.status!=='playing'||!ready||!!held;b.textContent=held?`Đã nhận · bàn ${held.tableIndex+1}`:ready?`Nhận: ${recipeName(ready.recipe)}`:cooking?`Đang pha: ${recipeName(v.tickets.find(x=>x.id===cooking.ticketId)?.recipe)}`:'Bếp sẵn';el('tsKitchenNote').textContent=held?`Đưa ${recipeName(held.recipe)} tới bàn ${held.tableIndex+1}.`:cooking?`Đơn còn ${Math.ceil(cooking.remaining/60)} nhịp.`:'Đơn vào bếp theo thứ tự.';}
  const stateText={empty:'Trống',order:'Nhận đơn',ordered:'Chờ món',eating:'Khách đang ăn'};
  function renderTables(v){v.tables.forEach((t,i)=>{const b=el('tsTable'+i),c=v.customers.find(x=>x.id===t.customerId);b.dataset.state=t.state;b.disabled=paused||confirm||v.status!=='playing'||t.state==='eating'||t.state==='ordered'&&v.heldTicket?.tableIndex!==i;b.setAttribute('aria-label',t.state==='empty'?`Bàn ${i+1}, trống, ${t.capacity} chỗ`:c?`Bàn ${i+1}, nhóm ${c.size} người, ${stateText[t.state]}`:`Bàn ${i+1}, ${stateText[t.state]}`);let label=stateText[t.state];if(t.state==='empty')label=`Trống · ${t.capacity} chỗ`;else if(t.state==='order')label=`${c?.size||1} người · Nhận đơn`;else if(t.state==='ordered'){const order=v.tickets.find(x=>x.id===t.ticketId);label=v.heldTicket?.tableIndex===i?`Giao ${recipeName(order?.recipe)}`:`${recipeName(order?.recipe)} · ${order?.status==='ready'?'món sẵn':'đang pha'}`;}else if(t.state==='eating')label=`${c?.size||1} người · đang ăn`;el(`tsTable${i}State`).textContent=label;});}
  function update(){const v=model.view(),status=v.status,terminal=status!=='playing',stamp=[v.shift,v.ticks,v.score,v.queue.map(c=>c.id+':'+c.patience).join(','),v.tables.map(t=>t.state+':'+t.customerId+':'+t.ticketId+':'+t.eatLeft).join(','),v.tickets.map(t=>t.id+':'+t.status).join(','),v.heldTicketId,v.status,paused,confirm].join('|');if(stamp!==lastHUD){lastHUD=stamp;const earned=v.score-v.bankScore,seconds=Math.max(0,Math.ceil((v.shiftInfo.duration-v.ticks)*M.STEP/1000));el('tsShift').textContent=`${v.shift+1} / ${M.SHIFTS.length}`;el('tsScore').textContent=`${earned} / ${v.shiftInfo.target}`;el('tsWaiting').textContent=String(v.queue.length);el('tsTime').textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;el('tsScore').setAttribute('aria-label',`${earned} điểm, mục tiêu ${v.shiftInfo.target}`);el('tsPause').disabled=terminal||confirm;el('tsPause').textContent=paused&&!terminal?'▶':'Ⅱ';el('tsPause').setAttribute('aria-label',paused&&!terminal?'Chơi tiếp':'Tạm dừng');el('tsOverlay').hidden=!(paused||terminal||confirm);el('tsConfirm').hidden=!confirm;el('tsContinue').hidden=confirm;el('tsOverlayTitle').textContent=confirm?'Ca mới?':status==='cleared'?'Đạt mục tiêu!':status==='won'?'Tiệm Lá Trà!':status==='lost'?'Kết ca':'Tạm dừng';el('tsOverlayText').hidden=!terminal;el('tsOverlayText').textContent=status==='cleared'?`${v.shiftInfo.name} · ${earned} điểm.`:status==='won'?`${v.score} điểm sau ba ca.`:`${earned} / ${v.shiftInfo.target} điểm.`;el('tsContinue').textContent=status==='cleared'?'Ca tiếp':status==='lost'?'Thử lại':status==='won'?'Ca mới':'▶';el('tsContinue').setAttribute('aria-label',status==='cleared'?'Bắt đầu ca tiếp':status==='lost'?'Thử lại ca này':status==='won'?'Chơi ca mới':'Chơi tiếp');}renderQueue(v);renderKitchen(v);renderTables(v);}
  function loop(ts){frame=null;if(!alive||paused||confirm||model.view().status!=='playing')return;const dt=lastFrame===null?0:ts-lastFrame;lastFrame=ts;if(dt>250){pause('Đã tạm dừng sau khi rời tiệm.');return;}accumulator+=Math.max(0,dt);saveAccumulator+=Math.max(0,dt);while(accumulator+1e-7>=M.STEP&&model.view().status==='playing'){accumulator-=M.STEP;const events=model.advance(M.STEP);if(events.length)drain(events);}update();if(!paused&&!confirm&&model.view().status==='playing')frame=requestAnimationFrame(loop);if(saveAccumulator>=750)save();}
  listen(el('tsNew'),'click',requestNew);listen(el('tsPause'),'click',()=>paused?resume():pause());listen(el('tsConfirmYes'),'click',newRun);listen(el('tsConfirmNo'),'click',()=>{confirm=false;paused=pausedBeforeConfirm;update();save();if(paused)el('tsContinue').focus();else{frame=requestAnimationFrame(loop);}});listen(el('tsContinue'),'click',()=>{if(confirm)return;const v=model.view();if(v.status==='cleared')nextShift();else if(v.status==='lost')retry();else if(v.status==='won')newRun();else resume();});
  for(let i=0;i<3;i++){listen(el('tsGuest'+i),'click',()=>action('queue',Number(el('tsGuest'+i).dataset.customerId)));listen(el('tsTable'+i),'click',()=>action('table',i));}listen(el('tsKitchen'),'click',()=>action('kitchen'));
  listen(container,'keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.repeat||e.target.closest?.('input,textarea,select,[contenteditable]'))return;if(String(e.key).toLowerCase()==='p'&&e.target.tagName!=='BUTTON'){e.preventDefault();paused?resume():pause();}});
  listen(window,'blur',()=>pause('Đã tạm dừng khi mất tiêu điểm.'));listen(document,'visibilitychange',()=>{if(document.hidden)pause('Đã tạm dừng khi rời tiệm.');});listen(window,'pagehide',()=>pause('Đã lưu ca đang chơi.'));
  onCleanup(()=>{cancelAnimationFrame(frame);frame=null;save();container.classList.remove('ts-host');alive=false;});
  if(paused)announce('Ca đã lưu. Bấm Chơi tiếp để tiếp tục.');if(notice)setNotice(notice);update();save();if(!paused&&model.view().status==='playing')frame=requestAnimationFrame(loop);setTimeout(()=>{if(alive)el(paused?'tsContinue':'tsGuest0').focus({preventScroll:true});},0);return{getModel:()=>model,isPaused:()=>paused};
 }
 window.NP_TeaService=Object.freeze({mount});
 if(window.NP_Engines&&typeof window.NP_Engines.launchDinerDash==='function')window.NP_Engines.launchDinerDash=function(container){return mount(container,window.NP_GameSession.start(),window.NP_AudioEngine);};
})();
